name = "Fabulously Create"
author = "kieranholroyd"
version = "2.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bbe513f8b7b44e8a34356d6c9c366a17bad3dbc1ac0ada6bfeae2ec52f9684f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
