name = "Fabulously Create"
author = "kieranholroyd"
version = "2.1.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e3a86aa8e879040a6fc953c52b955cbe9b696e0e71add8afd7bb0118367f480"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
