"""4. Wires & Wits quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import C_BRASS


def chapter() -> Chapter:
    return Chapter(
        key='automation',
        base=400,
        chapter_id='A200000000000004',
        icon='integrateddynamics:cable',
        title='4. Wires & Wits',
        subtitle='ID networks, diesel, FE, and factory enchanting',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='integrateddynamics:menril_log',
                title='Menril Wood',
                desc=[
                    '&6Goal:&r Collect &616 menril logs&r.',
                    '',
                    "Menril fuels Integrated Dynamics crafting. Find menril trees / berries in the world (Nature's Compass helps).",
                    '',
                    '&7Tip:&r Crystalized menril chunks also drop — keep them for cables and variables.',
                    '&7Next:&r Spin up a cable network, then learn variables.',
                ],
                task_count=16,
                links=require(C_BRASS),
                rewards=[item('integrateddynamics:crystalized_menril_chunk', 16), xp_levels(1)],
                size=1.5,
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='integrateddynamics:cable',
                title='Logic Network',
                desc=[
                    '&6Goal:&r Craft &632 Integrated Dynamics cables&r.',
                    '',
                    "ID is this pack's programmable logistics brain — readers, writers, and terminals plug into cable.",
                    '',
                    '&7Tip:&r Think of cables like a tiny computer bus running through your base.',
                ],
                task_count=32,
                deps=[0],
                rewards=[item('integrateddynamics:crystalized_menril_chunk', 16), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='integrateddynamics:logic_programmer',
                title='Logic Programmer',
                desc=[
                    '&6Goal:&r Craft a Logic Programmer.',
                    '',
                    'The desk where you write variable cards — numbers, items, lists, operators, and filters.',
                    '',
                    "&7Tip:&r There's also a portable programmer for field work.",
                ],
                deps=[1],
                rewards=[item('integrateddynamics:variable', 16), xp_levels(1)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='integrateddynamics:variable',
                title='Variables',
                desc=[
                    '&6Goal:&r Craft &616 variables&r.',
                    '',
                    'Store numbers, items, lists, and logic — programming cards for your network.',
                ],
                task_count=16,
                deps=[2],
                rewards=[item('integrateddynamics:cable', 8)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='integrateddynamics:part_inventory_reader',
                title='Inventory Reader',
                desc=[
                    '&6Goal:&r Craft an Inventory Reader part.',
                    '',
                    'Attach to a cable facing an inventory to read contents into variables — the eyes of your network.',
                ],
                deps=[3],
                rewards=[item('integrateddynamics:variable', 8), xp_levels(1)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0,
                task='integrateddynamics:part_display_panel',
                title='Display Panel',
                desc=[
                    '&6Goal:&r Craft a display panel.',
                    '',
                    'Show variable values on the wall — debug your logic without guessing.',
                ],
                deps=[3],
                rewards=[item('minecraft:glass_pane', 16)],
                optional=True,
                subtitle='Integrated Dynamics',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=5,
                y=2.5,
                task='integratedtunnels:part_interface_item',
                title='Item Tunnels',
                desc=[
                    '&6Goal:&r Craft &64 item interfaces&r (Integrated Tunnels).',
                    '',
                    "Pull and push items with filters — ID's version of import/export buses.",
                    '',
                    '&7Next:&r Importers automate continuous transfer; terminals let you browse the network.',
                ],
                task_count=4,
                deps=[1],
                rewards=[item('minecraft:hopper', 4)],
                subtitle='Tunnels',
            ),
            Quest(
                n=7,
                x=7.5,
                y=2.5,
                task='integratedtunnels:part_importer_item',
                title='Item Importer',
                desc=[
                    '&6Goal:&r Craft an item importer.',
                    '',
                    'Continuously pull items into the network with filters and conditions.',
                ],
                deps=[6],
                rewards=[item('integrateddynamics:variable', 8), xp_levels(1)],
                subtitle='Tunnels',
            ),
            Quest(
                n=8,
                x=10,
                y=2.5,
                task='integratedtunnels:part_interface_fluid',
                title='Fluid Tunnels',
                desc=[
                    '&6Goal:&r Craft &62 fluid interfaces&r.',
                    '',
                    'Move Create fluids, diesel fuels, and liquid XP through the ID network.',
                ],
                task_count=2,
                deps=[6],
                rewards=[item('minecraft:bucket', 4)],
                optional=True,
                subtitle='Tunnels',
                hide_until_deps=True,
            ),
            Quest(
                n=9,
                x=7.5,
                y=4.5,
                task='integratedterminals:part_terminal_storage',
                title='Storage Terminal',
                desc=[
                    '&6Goal:&r Craft a Storage Terminal.',
                    '',
                    'Browse and craft from everything your tunnels can see — the AE2 vibe without AE2.',
                    '',
                    '&7Tip:&r Portable terminal exists for on-the-go access once unlocked.',
                ],
                deps=[7],
                rewards=[item('minecraft:ender_eye', 4), xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Terminals',
            ),
            Quest(
                n=10,
                x=10,
                y=4.5,
                task='integratedcrafting:part_interface_crafting',
                title='Crafting Interface',
                desc=[
                    '&6Goal:&r Craft a Crafting Interface.',
                    '',
                    'Request autocrafting through your ID terminal once patterns / recipes are set up.',
                    '',
                    "&7Next:&r You're ready for factory-scale enchanting and fuel systems.",
                ],
                deps=[9],
                rewards=[item('minecraft:crafting_table'), xp_levels(2)],
                size=1.5,
                subtitle='Autocrafting',
            ),
            Quest(
                n=11,
                x=2.5,
                y=-2.5,
                task='createaddition:alternator',
                title='Alternator',
                desc=[
                    '&6Goal:&r Build a Create Crafts & Additions Alternator.',
                    '',
                    'Spin it with SU to generate FE (Forge Energy) for electric addons and jetpack charging.',
                ],
                deps=[1],
                rewards=[item('createaddition:capacitor', 2), xp_levels(1)],
                subtitle='Power',
            ),
            Quest(
                n=12,
                x=5,
                y=-2.5,
                task='createaddition:electric_motor',
                title='Electric Motor',
                desc=[
                    '&6Goal:&r Build an Electric Motor.',
                    '',
                    'Turn FE back into SU — great for remote bases powered by diesel or New Age electricity.',
                ],
                deps=[11],
                rewards=[item('createaddition:copper_spool', 4), xp_levels(1)],
                subtitle='Power',
            ),
            Quest(
                n=13,
                x=7.5,
                y=-2.5,
                task='createaddition:rolling_mill',
                title='Rolling Mill',
                desc=[
                    '&6Goal:&r Build a CCA Rolling Mill.',
                    '',
                    'Roll rods and wires for electrical crafting — pairs with the alternator line.',
                ],
                deps=[12],
                rewards=[item('minecraft:iron_ingot', 16)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=10,
                y=-2.5,
                task='createdieselgenerators:oil_scanner',
                title='Oil Scanner',
                desc=[
                    '&6Goal:&r Craft an oil scanner (Create Diesel Generators).',
                    '',
                    'Find crude oil deposits before committing to a pumpjack.',
                ],
                deps=[12],
                rewards=[item('createdieselgenerators:plant_oil_bucket', 2), xp_levels(1)],
                subtitle='Diesel',
            ),
            Quest(
                n=15,
                x=12.5,
                y=-2.5,
                task='createdieselgenerators:diesel_engine',
                title='Diesel Engine',
                desc=[
                    '&6Goal:&r Build a Diesel Engine.',
                    '',
                    "Process plant oil / crude into fuel and burn it for strong kinetic power — Create's combustion route.",
                    '',
                    '&7Tip:&r Distillation controller + pumpjacks scale this into a fuel empire.',
                ],
                deps=[14],
                rewards=[item('createdieselgenerators:engine_piston', 2), xp_levels(2)],
                size=1.5,
                subtitle='Diesel',
            ),
            Quest(
                n=16,
                x=15,
                y=-2.5,
                task='createdieselgenerators:distillation_controller',
                title='Distillation',
                desc=[
                    '&6Goal:&r Craft a distillation controller.',
                    '',
                    'Refine crude into diesel, gasoline, and other fractions for engines and asphalt builds.',
                ],
                deps=[15],
                rewards=[item('createdieselgenerators:oil_barrel', 2), xp_levels(1)],
                optional=True,
                subtitle='Diesel',
                hide_until_deps=True,
            ),
            Quest(
                n=17,
                x=12.5,
                y=2.5,
                task='create_enchantment_industry:experience_hatch',
                title='Experience Hatch',
                desc=[
                    '&6Goal:&r Craft an experience hatch (Enchantment Industry).',
                    '',
                    'Get liquid XP into Create fluid networks — the fuel for automated enchanting.',
                ],
                deps=[9],
                rewards=[item('minecraft:experience_bottle', 8), xp_levels(1)],
                subtitle='Enchanting',
            ),
            Quest(
                n=18,
                x=15,
                y=2.5,
                task='create_enchantment_industry:blaze_enchanter',
                title='Blaze Enchanter',
                desc=[
                    '&6Goal:&r Build a Blaze Enchanter.',
                    '',
                    'Pump liquid experience and automate enchanted books / gear — factory magic.',
                    '',
                    '&7Tip:&r Printers copy enchanted books once you have templates.',
                ],
                deps=[17],
                rewards=[item('create_enchantment_industry:enchanting_template', 2), xp_levels(2)],
                size=1.5,
                subtitle='Enchanting',
            ),
            Quest(
                n=19,
                x=17.5,
                y=2.5,
                task='create_enchantment_industry:printer',
                title='Enchantment Printer',
                desc=[
                    '&6Goal:&r Craft an Enchantment Industry printer.',
                    '',
                    'Copy enchantments onto books/gear with liquid XP — mass-produce your favorite setups.',
                ],
                deps=[18],
                rewards=[item('minecraft:book', 16), xp_levels(2)],
                optional=True,
                subtitle='Enchanting',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=15,
                y=4.5,
                task='sliceanddice:slicer',
                title='Slice & Dice',
                desc=[
                    '&6Goal:&r Craft a Slice & Dice slicer.',
                    '',
                    "Pair with Create to automate Farmer's Delight cutting — salads on a conveyor belt.",
                ],
                deps=[9],
                rewards=[item('farmersdelight:cutting_board'), xp_levels(1)],
                optional=True,
                subtitle='Food automation',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=17.5,
                y=4.5,
                task='sliceanddice:sprinkler',
                title='Sprinkler',
                desc=[
                    '&6Goal:&r Craft a Slice & Dice sprinkler.',
                    '',
                    'Automate crop hydration / fertilizer vibes for bigger farms.',
                ],
                deps=[20],
                rewards=[item('minecraft:bone_meal', 32)],
                optional=True,
                subtitle='Food automation',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=-2.5,
                task='create_connected:brake',
                title='Kinetic Brake',
                desc=[
                    '&6Goal:&r Craft a Brake (Create: Connected).',
                    '',
                    'Connected adds practical kinetic utilities — brakes, clutches, copycats-adjacent helpers, and more.',
                ],
                deps=[11],
                rewards=[item('create:electron_tube', 2), xp_levels(1)],
                optional=True,
                subtitle='Create extras',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=12.5,
                y=-4.5,
                task='create_connected:parallel_gearbox',
                title='Parallel Gearbox',
                desc=[
                    '&6Goal:&r Craft a parallel gearbox (Create: Connected).',
                    '',
                    'Compact kinetic routing for dense factory floors — squeeze more shafts into less space.',
                ],
                deps=[22],
                rewards=[item('create:cogwheel', 8)],
                optional=True,
                subtitle='Create extras',
                hide_until_deps=True,
            ),
        ],
    )

