"""4. Wires & Wits quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import C_BRASS
from ftb_quests.text import overview, tutorial


def chapter() -> Chapter:
    return Chapter(
        key='automation',
        base=400,
        chapter_id='A200000000000004',
        icon='integrateddynamics:cable',
        title='4. Wires & Wits',
        subtitle='ID networks, diesel, FE, and factory enchanting',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='integrateddynamics:menril_log',
                title='Menril Wood',
                desc=overview(
                    "Menril fuels Integrated Dynamics crafting — this chapter's programmable logistics brain, plus diesel power and factory enchanting.",
                    you_will=[
                        'Gather menril and spin up an ID cable network',
                        'Read inventories, tunnel items/fluids, and browse from a storage terminal',
                        'Generate FE with alternators and burn diesel for kinetic power',
                    ],
                    tip="Nature's Compass helps find menril biomes. Crystalized menril chunks also drop — keep them.",
                )
                + [""]
                + tutorial(
                    'Collect &616 Menril Logs&r.',
                    why='Menril is the wood/crystal backbone of Integrated Dynamics — cables, logic, and terminals all start here.',
                    steps=[
                        "Use Nature's Compass (or explore) to find a menril biome / menril trees.",
                        'Chop &616 Menril Logs&r; keep crystalized menril chunks that drop.',
                        'Haul the logs home and leave space for an ID cable spine through storage.',
                    ],
                    tip='Saplings replant near base so you are not hiking for every cable batch.',
                    nxt='Craft ID cables and form your first logic network.',
                ),
                task_count=16,
                links=require(C_BRASS),
                rewards=[item('integrateddynamics:crystalized_menril_chunk', 16), xp_levels(1)],
                size=1.5,
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='integrateddynamics:cable',
                title='Logic Network',
                desc=tutorial(
                    'Craft &632 Integrated Dynamics cables&r.',
                    why="ID is this pack's programmable logistics brain — readers, writers, and terminals plug into cable.",
                    steps=[
                        'Craft 32 ID cables from menril materials (JEI).',
                        'Place a continuous cable line through your storage / factory area.',
                        'Think of cables like a tiny computer bus — every part must touch the network.',
                        'Leave branches toward chests you want to automate later.',
                    ],
                    tip='Break and replace cables carefully — orphaned segments lose network access.',
                ),
                task_count=32,
                deps=[0],
                rewards=[item('integrateddynamics:crystalized_menril_chunk', 16), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='integrateddynamics:logic_programmer',
                title='Logic Programmer',
                desc=tutorial(
                    'Craft a Logic Programmer.',
                    why='The desk where you write variable cards — numbers, items, lists, operators, and filters.',
                    steps=[
                        'Craft a Logic Programmer and place it near your cable network.',
                        'Open it and create a simple variable (e.g. an item type or number).',
                        'Write the variable onto a blank variable card.',
                        'Keep the programmer accessible — you will iterate filters often.',
                    ],
                    tip="There's also a portable programmer for field work.",
                ),
                deps=[1],
                rewards=[item('integrateddynamics:variable', 16), xp_levels(1)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='integrateddynamics:variable',
                title='Variables',
                desc=tutorial(
                    'Craft &616 variables&r.',
                    why='Store numbers, items, lists, and logic — programming cards for your network.',
                    steps=[
                        'Craft 16 blank variable cards.',
                        'Use the Logic Programmer to label a few: item filters, integers, operators.',
                        'Insert written cards into readers / panels / tunnels as you build them.',
                        'Keep blanks on hand — every new filter needs a card.',
                    ],
                ),
                task_count=16,
                deps=[2],
                rewards=[item('integrateddynamics:cable', 8)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='integrateddynamics:part_inventory_reader',
                title='Inventory Reader',
                desc=tutorial(
                    'Craft an Inventory Reader part.',
                    why='Attach to a cable facing an inventory to read contents into variables — the eyes of your network.',
                    steps=[
                        'Craft an Inventory Reader part.',
                        'Place it on a cable block facing a chest or drawer controller.',
                        'Insert a variable card configured to read items / counts.',
                        'Verify with a display panel that the network sees the inventory.',
                    ],
                ),
                deps=[3],
                rewards=[item('integrateddynamics:variable', 8), xp_levels(1)],
                subtitle='Integrated Dynamics',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0,
                task='integrateddynamics:part_display_panel',
                title='Display Panel',
                desc=tutorial(
                    'Craft a display panel.',
                    why='Show variable values on the wall — debug your logic without guessing.',
                    steps=[
                        'Craft a display panel and place it on a cable.',
                        'Insert the variable card you want to visualize.',
                        'Watch values update as chests fill/empty — use this while tuning tunnels.',
                    ],
                ),
                deps=[3],
                rewards=[item('minecraft:glass_pane', 16)],
                optional=True,
                subtitle='Integrated Dynamics',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=5,
                y=2.5,
                task='integratedtunnels:part_interface_item',
                title='Item Tunnels',
                desc=tutorial(
                    'Craft &64 item interfaces&r (Integrated Tunnels).',
                    why="Pull and push items with filters — ID's version of import/export buses.",
                    steps=[
                        'Craft 4 item interface parts.',
                        'Place interfaces on cable facing the inventories you want to link.',
                        'Configure each interface with variable filters (which items to expose).',
                        'Confirm items appear to the network before adding importers.',
                    ],
                    nxt='Importers automate continuous transfer; terminals let you browse the network.',
                ),
                task_count=4,
                deps=[1],
                rewards=[item('minecraft:hopper', 4)],
                subtitle='Tunnels',
            ),
            Quest(
                n=7,
                x=7.5,
                y=2.5,
                task='integratedtunnels:part_importer_item',
                title='Item Importer',
                desc=tutorial(
                    'Craft an item importer.',
                    why='Continuously pull items into the network with filters and conditions.',
                    steps=[
                        'Craft an item importer part.',
                        'Place it on cable facing a machine output or chest to drain.',
                        'Set filter variables (item type, rate, conditions).',
                        'Watch items move into networked storage — tweak if the wrong items move.',
                    ],
                ),
                deps=[6],
                rewards=[item('integrateddynamics:variable', 8), xp_levels(1)],
                subtitle='Tunnels',
            ),
            Quest(
                n=8,
                x=10,
                y=2.5,
                task='integratedtunnels:part_interface_fluid',
                title='Fluid Tunnels',
                desc=tutorial(
                    'Craft &62 fluid interfaces&r.',
                    why='Move Create fluids, diesel fuels, and liquid XP through the ID network.',
                    steps=[
                        'Craft 2 fluid interface parts.',
                        'Place them on cable facing fluid tanks (Create tanks, barrels, etc.).',
                        'Configure fluid filters so only the intended liquid transfers.',
                        'Pair with importers/exporters when you automate diesel or XP lines.',
                    ],
                ),
                task_count=2,
                deps=[6],
                rewards=[item('minecraft:bucket', 4)],
                optional=True,
                subtitle='Tunnels',
                hide_until_deps=True,
            ),
            Quest(
                n=9,
                x=7.5,
                y=4.5,
                task='integratedterminals:part_terminal_storage',
                title='Storage Terminal',
                desc=tutorial(
                    'Craft a Storage Terminal.',
                    why='Browse and craft from everything your tunnels can see — the AE2 vibe without AE2.',
                    steps=[
                        'Craft a Storage Terminal part.',
                        'Place it on your cable network within reach of a working desk.',
                        'Open it — you should see items from every linked interface.',
                        'Pull / deposit items from the terminal like a digital chest.',
                    ],
                    tip='Portable terminal exists for on-the-go access once unlocked.',
                ),
                deps=[7],
                rewards=[item('minecraft:ender_eye', 4), xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Terminals',
            ),
            Quest(
                n=10,
                x=10,
                y=4.5,
                task='integratedcrafting:part_interface_crafting',
                title='Crafting Interface',
                desc=tutorial(
                    'Craft a Crafting Interface.',
                    why='Request autocrafting through your ID terminal once patterns / recipes are set up.',
                    steps=[
                        'Craft a Crafting Interface and place it on the network near crafting storage.',
                        'Register recipes / patterns the mod expects (JEI + interface UI).',
                        'Request a craft from the storage terminal.',
                        'Verify ingredients pull from networked chests and outputs return.',
                    ],
                    nxt="You're ready for factory-scale enchanting and fuel systems.",
                ),
                deps=[9],
                rewards=[item('minecraft:crafting_table'), xp_levels(2)],
                size=1.5,
                subtitle='Autocrafting',
            ),
            Quest(
                n=11,
                x=2.5,
                y=-2.5,
                task='createaddition:alternator',
                title='Alternator',
                desc=tutorial(
                    'Build a Create Crafts & Additions Alternator.',
                    why='Spin it with SU to generate FE (Forge Energy) for electric addons and jetpack charging.',
                    steps=[
                        'Craft an Alternator and place it on a shaft from your kinetic network.',
                        'Connect CCA energy connectors / wires / capacitors to the alternator output.',
                        'Spin the shaft — confirm FE appears in a connected energy buffer.',
                        'Route FE to chargers, electric motors, or energy pipes.',
                    ],
                    tip='More RPM / SU → more FE. Gear up if generation is weak.',
                ),
                deps=[1],
                rewards=[item('createaddition:capacitor', 2), xp_levels(1)],
                subtitle='Power',
            ),
            Quest(
                n=12,
                x=5,
                y=-2.5,
                task='createaddition:electric_motor',
                title='Electric Motor',
                desc=tutorial(
                    'Build an Electric Motor.',
                    why='Turn FE back into SU — great for remote bases powered by diesel or New Age electricity.',
                    steps=[
                        'Craft an Electric Motor.',
                        'Feed it FE from your alternator / battery line.',
                        'Attach a shaft to the motor and set speed in its UI.',
                        'Power a remote workshop without running long kinetic shafts.',
                    ],
                ),
                deps=[11],
                rewards=[item('createaddition:copper_spool', 4), xp_levels(1)],
                subtitle='Power',
            ),
            Quest(
                n=13,
                x=7.5,
                y=-2.5,
                task='createaddition:rolling_mill',
                title='Rolling Mill',
                desc=tutorial(
                    'Build a CCA Rolling Mill.',
                    why='Roll rods and wires for electrical crafting — pairs with the alternator line.',
                    steps=[
                        'Craft a Rolling Mill and power it with SU.',
                        'Insert ingots / plates per JEI to roll rods and wires.',
                        'Stock copper/electrum spools for more CCA machines.',
                    ],
                ),
                deps=[12],
                rewards=[item('minecraft:iron_ingot', 16)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=10,
                y=-2.5,
                task='createdieselgenerators:oil_scanner',
                title='Oil Scanner',
                desc=tutorial(
                    'Craft an oil scanner (Create Diesel Generators).',
                    why='Find crude oil deposits before committing to a pumpjack.',
                    steps=[
                        'Craft an oil scanner.',
                        'Use it in the world to locate crude oil pockets.',
                        'Mark the spot (Waystone / coords) for a pumpjack pad.',
                        'Return with pipes, tanks, and a diesel engine plan.',
                    ],
                ),
                deps=[12],
                rewards=[item('createdieselgenerators:plant_oil_bucket', 2), xp_levels(1)],
                subtitle='Diesel',
            ),
            Quest(
                n=15,
                x=12.5,
                y=-2.5,
                task='createdieselgenerators:diesel_engine',
                title='Diesel Engine',
                desc=tutorial(
                    'Build a Diesel Engine.',
                    why="Process plant oil / crude into fuel and burn it for strong kinetic power — Create's combustion route.",
                    steps=[
                        'Craft a Diesel Engine and place it with shaft clearance.',
                        'Supply fuel (plant oil early, diesel later) via buckets or fluid pipes.',
                        'Start the engine and connect its kinetic output to your network.',
                        'Scale fuel production before attaching high-stress machines.',
                    ],
                    tip='Distillation controller + pumpjacks scale this into a fuel empire.',
                ),
                deps=[14],
                rewards=[item('createdieselgenerators:engine_piston', 2), xp_levels(2)],
                size=1.5,
                subtitle='Diesel',
            ),
            Quest(
                n=16,
                x=15,
                y=-2.5,
                task='createdieselgenerators:distillation_controller',
                title='Distillation',
                desc=tutorial(
                    'Craft a distillation controller.',
                    why='Refine crude into diesel, gasoline, and other fractions for engines and asphalt builds.',
                    steps=[
                        'Craft a distillation controller.',
                        'Build the distillation tower multiblock per JEI / ponder.',
                        'Pump crude oil into the tower and heat / power as required.',
                        'Pipe diesel (and other fractions) into barrels feeding your engines.',
                    ],
                ),
                deps=[15],
                rewards=[item('createdieselgenerators:oil_barrel', 2), xp_levels(1)],
                optional=True,
                subtitle='Diesel',
                hide_until_deps=True,
            ),
            Quest(
                n=17,
                x=12.5,
                y=2.5,
                task='create_enchantment_industry:experience_hatch',
                title='Experience Hatch',
                desc=tutorial(
                    'Craft an experience hatch (Enchantment Industry).',
                    why='Get liquid XP into Create fluid networks — the fuel for automated enchanting.',
                    steps=[
                        'Craft an experience hatch.',
                        'Place it on a Create fluid tank / pipe line that will hold liquid XP.',
                        'Feed XP into the system (bottles, grinders, or farm drops per mod recipes).',
                        'Confirm liquid experience appears in the tank before building the enchanter.',
                    ],
                ),
                deps=[9],
                rewards=[item('minecraft:experience_bottle', 8), xp_levels(1)],
                subtitle='Enchanting',
            ),
            Quest(
                n=18,
                x=15,
                y=2.5,
                task='create_enchantment_industry:blaze_enchanter',
                title='Blaze Enchanter',
                desc=tutorial(
                    'Build a Blaze Enchanter.',
                    why='Pump liquid experience and automate enchanted books / gear — factory magic.',
                    steps=[
                        'Craft a Blaze Enchanter and place it with fluid access.',
                        'Pipe liquid XP into the enchanter.',
                        'Supply books / gear and set the enchanting mode in its UI.',
                        'Power / configure per JEI, then pull enchanted outputs with funnels or arms.',
                    ],
                    tip='Printers copy enchanted books once you have templates.',
                ),
                deps=[17],
                rewards=[item('create_enchantment_industry:enchanting_template', 2), xp_levels(2)],
                size=1.5,
                subtitle='Enchanting',
            ),
            Quest(
                n=19,
                x=17.5,
                y=2.5,
                task='create_enchantment_industry:printer',
                title='Enchantment Printer',
                desc=tutorial(
                    'Craft an Enchantment Industry printer.',
                    why='Copy enchantments onto books/gear with liquid XP — mass-produce your favorite setups.',
                    steps=[
                        'Craft the printer and place it on your XP fluid line.',
                        'Insert an enchanting template / source book.',
                        'Feed blank books or gear plus liquid XP.',
                        'Collect copies — duplicate your best tool enchants.',
                    ],
                ),
                deps=[18],
                rewards=[item('minecraft:book', 16), xp_levels(2)],
                optional=True,
                subtitle='Enchanting',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=15,
                y=4.5,
                task='sliceanddice:slicer',
                title='Slice & Dice',
                desc=tutorial(
                    'Craft a Slice & Dice slicer.',
                    why="Pair with Create to automate Farmer's Delight cutting — salads on a conveyor belt.",
                    steps=[
                        'Craft a slicer and place it in a Create kinetic line.',
                        'Power it and feed ingredients that need cutting-board recipes.',
                        'Collect outputs onto a belt toward cooking pots / chests.',
                    ],
                ),
                deps=[9],
                rewards=[item('farmersdelight:cutting_board'), xp_levels(1)],
                optional=True,
                subtitle='Food automation',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=17.5,
                y=4.5,
                task='sliceanddice:sprinkler',
                title='Sprinkler',
                desc=tutorial(
                    'Craft a Slice & Dice sprinkler.',
                    why='Automate crop hydration / fertilizer vibes for bigger farms.',
                    steps=[
                        'Craft a sprinkler.',
                        'Place it above farmland and supply fluid (water) as the mod requires.',
                        'Power / activate so crops stay hydrated across the plot.',
                    ],
                ),
                deps=[20],
                rewards=[item('minecraft:bone_meal', 32)],
                optional=True,
                subtitle='Food automation',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=-2.5,
                task='create_connected:brake',
                title='Kinetic Brake',
                desc=tutorial(
                    'Craft a Brake (Create: Connected).',
                    why='Connected adds practical kinetic utilities — brakes, clutches, copycats-adjacent helpers, and more.',
                    steps=[
                        'Craft a Brake.',
                        'Place it on a shaft line you want to stop on demand.',
                        'Power / redstone-control the brake to halt rotation without breaking the network.',
                        'Use it to pause crushers or assembly lines safely.',
                    ],
                ),
                deps=[11],
                rewards=[item('create:electron_tube', 2), xp_levels(1)],
                optional=True,
                subtitle='Create extras',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=12.5,
                y=-4.5,
                task='create_connected:parallel_gearbox',
                title='Parallel Gearbox',
                desc=tutorial(
                    'Craft a parallel gearbox (Create: Connected).',
                    why='Compact kinetic routing for dense factory floors — squeeze more shafts into less space.',
                    steps=[
                        'Craft a parallel gearbox.',
                        'Place it where two parallel shafts need to share rotation in a tight footprint.',
                        'Connect inputs/outputs and verify direction with a wrench.',
                        'Replace bulky cog towers on crowded floors.',
                    ],
                ),
                deps=[22],
                rewards=[item('create:cogwheel', 8)],
                optional=True,
                subtitle='Create extras',
                hide_until_deps=True,
            ),
        ],
    )
