"""2. Turning Gears quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, connected, item, require, xp_levels
from ftb_quests.ids import F_IRON, AUTOMATION_START, LATE_GAME_START, STORAGE_START
from ftb_quests.text import overview, tutorial


def chapter() -> Chapter:
    return Chapter(
        key='create_factory',
        base=200,
        chapter_id='A200000000000002',
        icon='create:cogwheel',
        title='2. Turning Gears',
        subtitle='Andesite → brass → drills, trains, and power',
        quest_links=[
            connected(STORAGE_START, 35.0, -2.5),
            connected(AUTOMATION_START, 35.0, 0.0),
            connected(LATE_GAME_START, 35.0, 2.5),
        ],
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='create:andesite_alloy',
                title='Andesite Alloy',
                desc=overview(
                    "Create's basic component. Everything kinetic — shafts, cogs, casings, presses — starts with andesite alloy.",
                    you_will=[
                        'Craft 32 andesite alloy (andesite + iron nuggets, or bulk-mix later)',
                        'Hand-crank early machines, then graduate to water wheels',
                        'Build a press → mixer → crushing → brass line',
                    ],
                    tip='Stockpile alloy now — every casing and cog spends it.',
                )
                + [""]
                + tutorial(
                    'Craft &632 Andesite Alloy&r.',
                    why='Every shaft, cogwheel, casing, and press recipe spends alloy. A 32-stack is the minimum starter kit.',
                    steps=[
                        'Mine &6andesite&r and smelt iron into &eingots/nuggets&r.',
                        'Craft alloy in a crafting table (andesite + iron nuggets) — JEI shows the exact shape.',
                        'Later, bulk-mix andesite with iron nuggets in a basin under a Mechanical Mixer for mass production.',
                    ],
                    tip='Keep a chest of alloy next to your first kinetic line.',
                    nxt='Hand crank a millstone or press to prove the network works.',
                ),
                task_count=32,
                links=require(F_IRON),
                rewards=[item('minecraft:andesite', 64), item('minecraft:iron_nugget', 64), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Create basics',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='create:hand_crank',
                title='Hand Crank',
                desc=tutorial(
                    'Craft a hand crank.',
                    why='Manually spin early machines before water wheels. Great for testing a press or millstone setup.',
                    steps=[
                        'Craft a hand crank from andesite alloy (JEI).',
                        'Place it on the end of a shaft connected to a machine.',
                        'Hold right-click to spin — watch the stressometer overlay (goggles help).',
                    ],
                    tip='Use the crank only to prove a machine works; swap to a water wheel next.',
                    nxt='Lay shafts so rotation can travel across your workshop.',
                ),
                deps=[0],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Kinetics',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='create:shaft',
                title='Shafts',
                desc=tutorial(
                    'Craft &616 shafts&r.',
                    why='Shafts carry rotation in a straight line — the backbone of every kinetic network.',
                    steps=[
                        'Craft 16 shafts from andesite alloy.',
                        'Place a shaft on your hand crank (or water wheel) output.',
                        'Extend the line: hold a shaft and look at another shaft to place long runs.',
                        'Use a Create wrench to reverse rotation direction when a machine spins the wrong way.',
                    ],
                    tip='Overstressed networks stop — add power or cut machines until SU balances.',
                ),
                task_count=16,
                deps=[1],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Kinetics',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='create:cogwheel',
                title='Cogwheels',
                desc=tutorial(
                    'Craft &616 cogwheels&r.',
                    why='Small cogs turn corners and change shaft axis — the elbows of your kinetic network.',
                    steps=[
                        'Craft 16 cogwheels (andesite alloy + planks).',
                        'Place a cog on the side of a shaft to branch rotation 90°.',
                        'Mesh two cogs to transfer power between parallel shafts.',
                        'Encasing a cog with andesite casing stops sideways interlocking when you need a clean run.',
                    ],
                    tip='Cogs also act as belt pulleys later — keep extras.',
                ),
                task_count=16,
                deps=[2],
                rewards=[item('minecraft:oak_planks', 64)],
                subtitle='Kinetics',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='create:large_cogwheel',
                title='Large Cogwheels',
                desc=tutorial(
                    'Craft &68 large cogwheels&r.',
                    why='Pair large + small for gear ratios — speed up or slow down machines (stress changes too).',
                    steps=[
                        'Craft 8 large cogwheels.',
                        'Mesh a large cog with a small cog: driving the large slows the small side; driving the small speeds the large side.',
                        'Use slow shafts for high-stress machines (crushing, presses) and fast shafts for belts / fans.',
                        'Check the stress overlay after each ratio change.',
                    ],
                    tip='If a machine needs more torque, gear down; if belts crawl, gear up.',
                ),
                task_count=8,
                deps=[3],
                rewards=[item('create:cogwheel', 8), xp_levels(1)],
                subtitle='Kinetics',
            ),
            Quest(
                n=5,
                x=5,
                y=-2.5,
                task='create:water_wheel',
                title='Water Power',
                desc=tutorial(
                    'Craft a water wheel.',
                    why='Flowing water against the blades generates free SU (stress units). One or two wheels power a whole andesite workshop.',
                    steps=[
                        'Craft a water wheel and place it with space for water on both faces.',
                        'Place water source blocks so water flows across the wheel blades (not still water).',
                        'Attach a shaft to the wheel hub and run it into your workshop.',
                        'Add a second wheel or large water wheel when stress capacity runs out.',
                    ],
                    tip="Later you'll want steam engines, diesel, or electricity for megabases.",
                    nxt='Build andesite casings into a press + mixer line.',
                ),
                deps=[2],
                rewards=[item('create:shaft', 16), item('minecraft:water_bucket', 2)],
                size=1.5,
                subtitle='Power',
            ),
            Quest(
                n=6,
                x=5,
                y=-4.5,
                task='create:windmill_bearing',
                title='Windmill Bearing',
                desc=tutorial(
                    'Craft a windmill bearing.',
                    why='Sail-powered SU when you have space for a big windmill — optional alternative to water wheels.',
                    steps=[
                        'Craft a windmill bearing and place it facing open sky / wind.',
                        'Build a sail structure (wool sails on a rotatable frame) attached to the bearing.',
                        'Assemble / start the bearing so the windmill spins and outputs rotation.',
                        'Connect a shaft from the bearing into your kinetic network.',
                    ],
                    tip='Bigger sail area = more SU. Keep the rotor clear of buildings.',
                ),
                deps=[5],
                rewards=[item('minecraft:white_wool', 32), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=7,
                x=5,
                y=2.5,
                task='create:andesite_casing',
                title='Andesite Casing',
                desc=tutorial(
                    'Craft &616 andesite casings&r.',
                    why='Stripped logs + andesite alloy. Almost every andesite machine is built on casing.',
                    steps=[
                        'Strip logs with an axe (right-click) for stripped wood.',
                        'Craft casings: stripped log + andesite alloy (or apply alloy to stripped logs in-world).',
                        'Stock 16+ — press, mixer, saw, fan, and gearbox recipes all spend them.',
                    ],
                    tip='A mechanical saw later makes plank/casing spam trivial.',
                ),
                task_count=16,
                deps=[2],
                rewards=[item('create:andesite_alloy', 16)],
                subtitle='Machines',
            ),
            Quest(
                n=8,
                x=7.5,
                y=2.5,
                task='create:mechanical_press',
                title='Mechanical Press',
                desc=tutorial(
                    'Build a Mechanical Press.',
                    why='Presses compact plates, smash items on a depot, and unlock sheet metal for pipes and casings.',
                    steps=[
                        'Craft a Mechanical Press and place it with clearance underneath.',
                        'Power the press from the side with a shaft / cog from your water wheel.',
                        'Put a depot (or basin) under the press head.',
                        'Drop iron ingots on the depot — the press stamps them into iron sheets.',
                    ],
                    tip='Sheets unlock fluid tanks, pipes, and many Create recipes — press a stack.',
                    nxt='Add a basin under mixers/presses for bulk crafting.',
                ),
                deps=[7],
                rewards=[item('minecraft:iron_block', 2), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=9,
                x=10,
                y=2.5,
                task='create:basin',
                title='Basin',
                desc=tutorial(
                    'Craft a Basin.',
                    why='Mixers, presses, and bulk crafting use basins — dough, alloys, concrete, brass later with heat.',
                    steps=[
                        'Craft a basin and place it on the ground (or on a depot-style spot under a machine).',
                        'Leave one block of air above for a mixer or press head.',
                        'Toss ingredients into the basin (or funnel them in once you have belts).',
                        'Outputs can be pulled with funnels on the sides once logistics exist.',
                    ],
                    tip='Basins hold both items and fluids — keep a spare for chocolate / dough later.',
                ),
                deps=[7],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Machines',
            ),
            Quest(
                n=10,
                x=12.5,
                y=2.5,
                task='create:mechanical_mixer',
                title='Mechanical Mixer',
                desc=tutorial(
                    'Build a Mechanical Mixer above a basin.',
                    why='Bulk-craft andesite alloy, dough, and (with a blaze burner) brass. Automate inputs with funnels once belts exist.',
                    steps=[
                        'Place a basin, then place the Mechanical Mixer in the block above it.',
                        'Power the mixer from the side (shaft/cog).',
                        'Drop andesite + iron nuggets into the basin — watch them bulk-mix into alloy.',
                        'Later: put a blaze burner under the basin for heated mixes (brass).',
                    ],
                    tip='JEI shows which mixes need heat — no burner means no brass.',
                ),
                deps=[9],
                rewards=[item('create:whisk'), xp_levels(1)],
                size=1.5,
                subtitle='Machines',
            ),
            Quest(
                n=11,
                x=7.5,
                y=4.5,
                task='create:millstone',
                title='Millstone',
                desc=tutorial(
                    'Build a Millstone.',
                    why='Mill wheat into flour and process early bulk goods with low stress cost.',
                    steps=[
                        'Craft and place a millstone.',
                        'Power it from the side with a shaft.',
                        'Drop wheat on top (or funnel in) to mill flour.',
                        'Collect outputs from the bottom / sides for dough mixes.',
                    ],
                ),
                deps=[7],
                rewards=[item('minecraft:wheat', 32)],
                optional=True,
                subtitle='Machines',
                hide_until_deps=True,
            ),
            Quest(
                n=12,
                x=10,
                y=4.5,
                task='create:mechanical_saw',
                title='Mechanical Saw',
                desc=tutorial(
                    'Build a Mechanical Saw.',
                    why='Auto-cut logs into planks and process wood at factory scale — huge for casing spam.',
                    steps=[
                        'Craft a Mechanical Saw and place it facing a processing spot.',
                        'Power it; drop logs onto a depot/belt in front of the blade.',
                        'Collect planks — feed stripped wood + alloy into more casings.',
                        'Optional: mount a saw on a contraption for tree farms later.',
                    ],
                ),
                deps=[7],
                rewards=[item('minecraft:oak_log', 32), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=13,
                x=12.5,
                y=4.5,
                task='create:encased_fan',
                title='Encased Fan',
                desc=tutorial(
                    'Build an Encased Fan.',
                    why='Fans blast items through processing paths — smoking, blasting, washing, and haunting.',
                    steps=[
                        'Craft an Encased Fan and power it so air blows forward.',
                        'Build a short tunnel of passable blocks in front of the fan.',
                        'For washing: place water in the path and drop gravel / crushed ore through it for nuggets.',
                        'For smoking/blasting: put fire / lava in the path (careful with lava). Haunting uses soul fire.',
                    ],
                    tip='Washing crushed ores after crushing wheels is a massive early ore multiplier.',
                ),
                deps=[7],
                rewards=[item('create:propeller', 2), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=14,
                x=10,
                y=-2.5,
                task='create:belt_connector',
                title='Belts',
                desc=tutorial(
                    'Craft &616 belt connectors&r.',
                    why='Belts move items between depots, basins, and inventories — Create\'s conveyor system.',
                    steps=[
                        'Craft belt connectors (dried kelp + andesite alloy).',
                        'Place two shafts (or cogs) apart, then right-click both with a belt connector to stretch a belt.',
                        'Power one shaft so the belt moves; drop items on top to convey them.',
                        'Slope belts with shafts at different heights for chutes between floors.',
                    ],
                    tip='Dried kelp farms pay for themselves once belts go wide.',
                ),
                task_count=16,
                deps=[3],
                rewards=[item('minecraft:dried_kelp', 32)],
                subtitle='Logistics',
            ),
            Quest(
                n=15,
                x=12.5,
                y=-2.5,
                task='create:depot',
                title='Depots',
                desc=tutorial(
                    'Craft &68 depots&r.',
                    why='Depots hold a single stack for presses, deployers, and belt handoff — the workbench of kinetics.',
                    steps=[
                        'Craft 8 depots and place them under presses or along belt lines.',
                        'Drop an item on a depot — a press above will process it in place.',
                        'Use belts + funnels to load/unload depots automatically.',
                        'Chain depot → belt → depot for assembly lines.',
                    ],
                ),
                task_count=8,
                deps=[14],
                rewards=[item('create:andesite_alloy', 8), xp_levels(1)],
                subtitle='Logistics',
            ),
            Quest(
                n=16,
                x=15,
                y=-2.5,
                task='create:andesite_funnel',
                title='Andesite Funnels',
                desc=tutorial(
                    'Craft &68 andesite funnels&r.',
                    why='Pull and push items onto belts and into inventories. Brass funnels come later with filters.',
                    steps=[
                        'Craft 8 andesite funnels.',
                        'Place a funnel on a chest/basin facing a belt to extract items onto the belt.',
                        'Place a funnel facing into an inventory to insert from a belt.',
                        'Use chutes for vertical drops when belts are overkill.',
                    ],
                    tip='Funnels only move when powered by kinetics on their belt/shaft side — check the goggles overlay.',
                ),
                task_count=8,
                deps=[15],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Logistics',
            ),
            Quest(
                n=17,
                x=15,
                y=0,
                task='create:crushing_wheel',
                title='Crushing Wheels',
                desc=tutorial(
                    'Craft &62 crushing wheels&r and place them as a pair.',
                    why="Crush ores for &amore output&r than a furnace — the pack's first real ore multiplier.",
                    steps=[
                        'Craft 2 crushing wheels.',
                        'Place them as a facing pair (JEI / ponder shows the gap) so items fall between.',
                        'Power both wheels so they rotate toward each other.',
                        'Drop raw ore into the gap; collect crushed ore below with a belt or hopper.',
                        'Wash crushed ore with a fan + water path for extra nuggets, then smelt.',
                    ],
                    tip='Wash crushed ores with a fan + water for extra nuggets.',
                    nxt='Hunt zinc, then blaze burners for brass.',
                ),
                task_count=2,
                deps=[8, 13],
                rewards=[item('minecraft:iron_ingot', 24), xp_levels(2)],
                size=1.5,
                subtitle='Ores',
            ),
            Quest(
                n=18,
                x=17.5,
                y=0,
                task='create:zinc_ingot',
                title='Zinc Stockpile',
                desc=tutorial(
                    'Produce &616 zinc ingots&r.',
                    why='Zinc + copper (+ heat) = brass. Mine zinc ore or crush raw zinc.',
                    steps=[
                        'Mine zinc ore (or find raw zinc) — check JEI for worldgen look.',
                        'Optional: crush zinc ore for better yields, then wash.',
                        'Smelt until you hold 16 zinc ingots.',
                        'Store next to copper — brass mixing will burn through both.',
                    ],
                ),
                task_count=16,
                deps=[17],
                rewards=[item('minecraft:copper_ingot', 32), xp_levels(1)],
                subtitle='Metals',
            ),
            Quest(
                n=19,
                x=17.5,
                y=2.5,
                task='create:fluid_tank',
                title='Fluid Tanks',
                desc=tutorial(
                    'Craft &64 fluid tanks&r.',
                    why='Store water, lava, chocolate, plant oil, diesel, and liquid XP later. Stack tanks into towers.',
                    steps=[
                        'Press copper into copper sheets, then craft fluid tanks.',
                        'Place tanks adjacent to each other to form a multiblock tank tower.',
                        'Right-click with a bucket to fill/empty for testing.',
                        'Pipe in with mechanical pumps once you craft them.',
                    ],
                    nxt='Mechanical pumps and hose pulleys move fluids around the factory.',
                ),
                task_count=4,
                deps=[8],
                rewards=[item('minecraft:copper_ingot', 16)],
                subtitle='Fluids',
            ),
            Quest(
                n=20,
                x=20,
                y=2.5,
                task='create:mechanical_pump',
                title='Mechanical Pump',
                desc=tutorial(
                    'Build a Mechanical Pump.',
                    why='Move fluids through Create pipes under SU power — water for steam, oil for diesel, XP for enchanting.',
                    steps=[
                        'Craft copper fluid pipes and a mechanical pump.',
                        'Connect pipe from a fluid tank (or source) through the pump to a destination tank.',
                        'Power the pump with a shaft — flow direction follows pump orientation (wrench to flip).',
                        'Verify transfer with a tank window or by bucket-testing the output.',
                    ],
                ),
                deps=[19],
                rewards=[item('create:copper_sheet', 8), xp_levels(1)],
                subtitle='Fluids',
            ),
            Quest(
                n=21,
                x=20,
                y=4.5,
                task='create:hose_pulley',
                title='Hose Pulley',
                desc=tutorial(
                    'Craft a hose pulley.',
                    why='Drain or fill lakes and infinite fluid sources into your tank network.',
                    steps=[
                        'Craft a hose pulley and place it above a fluid surface or tank.',
                        'Connect fluid pipes from the pulley to your tank farm.',
                        'Power the pulley; extend the hose into the fluid.',
                        'Use it to drain a lake into tanks or dump fluids back out.',
                    ],
                ),
                deps=[20],
                rewards=[item('minecraft:dried_kelp', 16)],
                optional=True,
                subtitle='Fluids',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=20,
                y=0,
                task='create:blaze_burner',
                title='Blaze Burner',
                desc=tutorial(
                    'Craft a Blaze Burner.',
                    why='Empty burner + blaze. Feed blaze cakes or fuel to &6superheat&r for brass and heated mixes.',
                    steps=[
                        'Go to a Nether fortress (Waystone home first) and collect blaze rods / catch a blaze.',
                        'Craft an empty blaze burner, then right-click it with a blaze to fill.',
                        'Place the burner under a basin that has a mixer above.',
                        'Feed fuel / blaze cakes until the burner reaches the heat level JEI shows for brass.',
                    ],
                    tip='Nether fortress or piglin trades. Place a Waystone before the trip.',
                    nxt='Mix copper + zinc with heat → brass age.',
                ),
                deps=[10],
                rewards=[item('minecraft:blaze_rod', 8), item('minecraft:nether_wart', 8)],
                size=1.5,
                subtitle='Brass gate',
            ),
            Quest(
                n=23,
                x=22.5,
                y=0,
                task='create:brass_ingot',
                title='Brass Age',
                desc=tutorial(
                    'Produce &632 brass ingots&r.',
                    why='Brass unlocks smart mechanisms, deployers, arms, trains, and most midgame Create addons.',
                    steps=[
                        'Set up basin + mixer + heated blaze burner underneath.',
                        'Insert copper ingots + zinc ingots into the basin (ratios per JEI).',
                        'Power the mixer until brass ingots craft; repeat until you have 32.',
                        'Automate with funnels: copper chest → basin ← zinc chest, output funnel to a brass chest.',
                    ],
                    tip='Automate brass early — precision mechanisms will eat it forever.',
                ),
                task_count=32,
                deps=[18, 22],
                rewards=[item('create:zinc_ingot', 16), item('minecraft:copper_ingot', 32), item('create:brass_sheet', 16), xp_levels(2)],
                size=1.75,
                shape='hexagon',
                subtitle='Brass',
            ),
            Quest(
                n=24,
                x=25,
                y=0,
                task='create:brass_casing',
                title='Brass Casing',
                desc=tutorial(
                    'Craft &616 brass casings&r.',
                    why='Frames deployers, mechanical arms, smart chutes, and precision machines.',
                    steps=[
                        'Press brass into brass sheets if the recipe needs them.',
                        'Craft brass casings from brass + stripped wood (same idea as andesite casing).',
                        'Stock 16+ before starting deployers and mechanical crafters.',
                    ],
                ),
                task_count=16,
                deps=[23],
                rewards=[item('create:brass_ingot', 8)],
                subtitle='Brass',
            ),
            Quest(
                n=25,
                x=27.5,
                y=0,
                task='create:electron_tube',
                title='Electron Tubes',
                desc=tutorial(
                    'Craft &68 electron tubes&r.',
                    why='Polished rose quartz + iron plates. The redstone-smart part inside precision builds.',
                    steps=[
                        'Craft rose quartz (quartz + redstone), then polish it (sandpaper / deployers).',
                        'Press iron sheets as needed.',
                        'Craft 8 electron tubes from JEI.',
                        'Keep extras — mechanical crafters and smart machines spend them.',
                    ],
                ),
                task_count=8,
                deps=[24],
                rewards=[item('minecraft:redstone', 32), item('create:rose_quartz', 8)],
                subtitle='Brass',
            ),
            Quest(
                n=26,
                x=30,
                y=0,
                task='create:mechanical_crafter',
                title='Mechanical Crafters',
                desc=tutorial(
                    'Craft &69 mechanical crafters&r.',
                    why='Arrange them into a crafting grid for sequenced assembly — how precision mechanisms are born.',
                    steps=[
                        'Craft 9 mechanical crafters.',
                        'Place them in a 3×3 grid facing the same way; connect with a crafter arrangement (wrench / ponder).',
                        'Power the bank of crafters from one kinetic input.',
                        'Set the crafting pattern for the next recipe (or prepare for sequenced assembly with deployers).',
                    ],
                    tip='JEI shows the assembly sequence. Automate inputs with funnels/arms.',
                ),
                task_count=9,
                deps=[25],
                rewards=[item('create:electron_tube', 4), xp_levels(2)],
                size=1.5,
                subtitle='Midgame',
            ),
            Quest(
                n=27,
                x=32.5,
                y=0,
                task='create:precision_mechanism',
                title='Precision Mechanisms',
                desc=tutorial(
                    'Assemble &68 precision mechanisms&r.',
                    why='Midgame Create currency — arms, consoles, trains, and many addons want them.',
                    steps=[
                        'Open JEI on Precision Mechanism and note the sequenced assembly steps.',
                        'Build a loop: belt + depot/belt chain with deployers holding the required parts (cogwheels, large cogs, electron tubes, etc.).',
                        'Insert incomplete mechanisms into the loop; deployers apply parts in order until complete.',
                        'Output finished mechanisms to a chest — craft 8 total (automate if hand-feeding hurts).',
                    ],
                    tip="If crafting these by hand hurts, your factory isn't finished yet.",
                    nxt='Deployers and arms next — then Ore Excavation for infinite ore.',
                ),
                task_count=8,
                deps=[26],
                rewards=[item('create:brass_sheet', 16), xp_levels(3)],
                size=1.75,
                shape='gear',
                subtitle='Midgame',
            ),
            Quest(
                n=28,
                x=27.5,
                y=2.5,
                task='create:deployer',
                title='Deployer',
                desc=tutorial(
                    'Build a Deployer.',
                    why='Auto-uses items: applying tools, placing blocks, assembly sequences, farming, and more.',
                    steps=[
                        'Craft a Deployer and place it facing a depot or belt lane.',
                        'Power it; put the held item (tool, cogwheel, electron tube…) in the deployer hand slot.',
                        'Filter/hand items so each deployer applies one assembly step.',
                        'Use on a depot: item arrives → deployer uses held item → item continues down the line.',
                    ],
                    tip='Deployers are the hands of sequenced assembly — one deployer per ingredient step.',
                ),
                deps=[24],
                rewards=[item('create:brass_hand'), xp_levels(1)],
                subtitle='Brass machines',
            ),
            Quest(
                n=29,
                x=30,
                y=2.5,
                task='create:mechanical_arm',
                title='Mechanical Arm',
                desc=tutorial(
                    'Build a Mechanical Arm.',
                    why='Program inputs/outputs to move items between inventories without belts everywhere.',
                    steps=[
                        'Craft a Mechanical Arm and place it within reach of two inventories/depots.',
                        'Power the arm; open its UI and set deposit/withdraw targets by clicking inventories.',
                        'Assign which slots / filters it should move.',
                        'Test with a single stack, then trust it for crafter feeding and mechanism outputs.',
                    ],
                ),
                deps=[27, 28],
                rewards=[item('create:precision_mechanism'), xp_levels(2)],
                size=1.5,
                subtitle='Brass machines',
            ),
            Quest(
                n=30,
                x=25,
                y=-2.5,
                task='create:steam_engine',
                title='Steam Engine',
                desc=tutorial(
                    'Build a Steam Engine.',
                    why='Serious SU from water tanks + blaze burners — the jump from water wheels to real factories.',
                    steps=[
                        'Build a fluid tank tower filled with water.',
                        'Attach blaze burners to heat the boiler / tank setup per JEI & ponder.',
                        'Place the steam engine against the heated tank and connect a shaft output.',
                        'Whisk / engine assembly produces high SU — gear it into your main network.',
                    ],
                    tip='Keep water topped up with a pump + hose pulley from a lake.',
                ),
                deps=[23],
                rewards=[item('create:copper_sheet', 16), xp_levels(2)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=31,
                x=22.5,
                y=4.5,
                task='createoreexcavation:vein_finder',
                title='Vein Finder',
                desc=tutorial(
                    'Craft a Vein Finder (Create Ore Excavation).',
                    why="Scan for infinite ore veins, then plant a drilling machine. The pack's answer to strip-mining forever.",
                    steps=[
                        'Craft the Vein Finder from JEI.',
                        'Right-click in the world to scan; note vein type and position.',
                        'Travel to the vein marker and clear a pad for the drilling machine.',
                        'Return once you have drills and SU to spare.',
                    ],
                    tip='Best once crushing wheels make processing cheap.',
                ),
                deps=[17],
                rewards=[item('createoreexcavation:drill'), xp_levels(1)],
                subtitle='Ores',
            ),
            Quest(
                n=32,
                x=25,
                y=4.5,
                task='createoreexcavation:drilling_machine',
                title='Drilling Machine',
                desc=tutorial(
                    'Build a Drilling Machine on a found vein.',
                    why='Feed it SU and drills for passive ore. Pair with crushing + washing for absurd ingot/hour.',
                    steps=[
                        'Place the Drilling Machine on the located vein.',
                        'Connect kinetic power (water wheels → steam/diesel later).',
                        'Insert drill heads and set fluid/drill requirements per JEI.',
                        'Pipe or funnel ore output into your crushing → washing → smelting line.',
                    ],
                ),
                deps=[31],
                rewards=[item('create:andesite_alloy', 32), xp_levels(2)],
                size=1.5,
                subtitle='Ores',
            ),
            Quest(
                n=33,
                x=27.5,
                y=-2.5,
                task='create_new_age:generator_coil',
                title='New Age Coil',
                desc=tutorial(
                    'Craft a Create: New Age generator coil.',
                    why='Magnets and electrical generation that pair with Create kinetics — another power path beside diesel and CCA.',
                    steps=[
                        'Craft a generator coil and the magnets / wires JEI lists.',
                        'Assemble the New Age generator structure (coil + magnets) per ponder/JEI.',
                        'Spin the kinetic input to generate electricity.',
                        'Route power to motors or FE machines as needed.',
                    ],
                ),
                deps=[23],
                rewards=[item('create_new_age:copper_wire', 8), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=34,
                x=30,
                y=-2.5,
                task='create_new_age:basic_motor',
                title='New Age Motor',
                desc=tutorial(
                    'Craft a basic motor (Create: New Age).',
                    why='Turn electrical power back into rotation for remote workshops.',
                    steps=[
                        'Craft a basic motor.',
                        'Supply it with New Age / FE electricity from your generator.',
                        'Attach a shaft to the motor output and power distant machines.',
                        'Use for outposts where water wheels are awkward.',
                    ],
                ),
                deps=[33],
                rewards=[item('create_new_age:magnetite_block', 2), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=35,
                x=15,
                y=6.5,
                task='createdeco:andesite_catwalk',
                title='Factory Catwalks',
                desc=tutorial(
                    'Craft an andesite catwalk (Create Deco).',
                    why='Industrial décor that makes factories readable — walkways, hulls, lamps, and sheet metal.',
                    steps=[
                        'Craft an andesite catwalk from JEI.',
                        'Place walkways above machine lines so you can service kinetics safely.',
                        'Add supports / lamps so the factory stays navigable at night.',
                    ],
                ),
                deps=[7],
                rewards=[item('createdeco:andesite_support', 8)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=36,
                x=17.5,
                y=6.5,
                task='copycats:copycat_block',
                title='Copycat Block',
                desc=tutorial(
                    'Craft a Copycats+ copycat block.',
                    why='Disguise technical blocks as any material — hide cables and machines inside pretty walls.',
                    steps=[
                        'Craft a copycat block.',
                        'Place it, then apply a material (right-click with a block) to copy its appearance.',
                        'Wrap shafts, pipes, or ugly machinery in matching walls.',
                    ],
                ),
                deps=[35],
                rewards=[item('copycats:copycat_slab', 8), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=37,
                x=20,
                y=6.5,
                task='interiors:seatwood_planks',
                title='Train Interiors',
                desc=tutorial(
                    'Craft seatwood planks (Create: Interiors).',
                    why='Furniture and seating for trains and stations — optional flair once tracks exist.',
                    steps=[
                        'Craft seatwood planks from JEI.',
                        'Build chairs / interiors inside a train carriage or station.',
                        'Ride in style once your track network is online.',
                    ],
                ),
                deps=[38],
                rewards=[item('interiors:white_chair', 2)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=38,
                x=32.5,
                y=2.5,
                task='create:track',
                title='Train Track',
                desc=tutorial(
                    'Craft &616 Create train tracks&r.',
                    why="Trains move bulk items and players across the map. Steam 'n' Rails adds more track styles and conductors later.",
                    steps=[
                        'Craft 16 tracks (andesite alloy + stone/andesite per JEI).',
                        'Place a track line by clicking sequentially along the path (shift for slopes/curves as prompted).',
                        'Add a station block / train assembly when you have a locomotive package.',
                        'Assemble a train on a robust track, define schedules, and haul items between bases.',
                    ],
                    tip="Trains need precision mechanisms and brass — finish those first if assembly is locked.",
                    nxt='Beyond Brass covers conductor whistles and fuel tanks.',
                ),
                task_count=16,
                deps=[27],
                rewards=[item('create:precision_mechanism'), xp_levels(1)],
                subtitle='Trains',
            ),
            Quest(
                n=39,
                x=22.5,
                y=-4.5,
                task='create_sa:copper_magnet',
                title='Copper Magnet',
                desc=tutorial(
                    "Craft a copper magnet (Stuff 'N Additions).",
                    why='Pull nearby items — great while mining or standing near crushing outputs.',
                    steps=[
                        'Craft a copper magnet from JEI.',
                        'Keep it in your inventory / Curios as the mod expects.',
                        'Stand near crushing-wheel outputs or ore drops to vacuum items.',
                    ],
                ),
                deps=[28],
                rewards=[item('minecraft:iron_ingot', 16)],
                optional=True,
                subtitle='Tools',
                hide_until_deps=True,
            ),
        ],
    )
