"""2. Turning Gears quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, connected, item, require, xp_levels
from ftb_quests.ids import F_IRON, AUTOMATION_START, LATE_GAME_START, STORAGE_START


def chapter() -> Chapter:
    return Chapter(
        key='create_factory',
        base=200,
        chapter_id='A200000000000002',
        icon='create:cogwheel',
        title='2. Turning Gears',
        subtitle='Andesite → brass → drills, trains, and power',
        quest_links=[
            connected(STORAGE_START, 35.0, -2.5),
            connected(AUTOMATION_START, 35.0, 0.0),
            connected(LATE_GAME_START, 35.0, 2.5),
        ],
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='create:andesite_alloy',
                title='Andesite Alloy',
                desc=[
                    '&6Goal:&r Craft &632 andesite alloy&r.',
                    '',
                    "Create's basic component. Everything kinetic — shafts, cogs, casings, presses — starts here.",
                    '',
                    '&7Tip:&r Recipe: andesite + iron nuggets in crafting, or bulk-mix later with a mixer + basin.',
                    '&7Next:&r Hand-crank a few machines, then build water wheels for free SU.',
                ],
                task_count=32,
                links=require(F_IRON),
                rewards=[item('minecraft:andesite', 64), item('minecraft:iron_nugget', 64), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Create basics',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='create:hand_crank',
                title='Hand Crank',
                desc=[
                    '&6Goal:&r Craft a hand crank.',
                    '',
                    'Manually spin early machines before water wheels. Great for testing a press or millstone setup.',
                ],
                deps=[0],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Kinetics',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='create:shaft',
                title='Shafts',
                desc=[
                    '&6Goal:&r Craft &616 shafts&r.',
                    '',
                    'Shafts carry rotation in a straight line. Hold a shaft and look at another to place long runs.',
                    '',
                    '&7Tip:&r Use a Create wrench to reverse rotation direction.',
                ],
                task_count=16,
                deps=[1],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Kinetics',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='create:cogwheel',
                title='Cogwheels',
                desc=[
                    '&6Goal:&r Craft &616 cogwheels&r.',
                    '',
                    'Small cogs turn corners and change shaft axis — the elbows of your kinetic network.',
                    '',
                    '&7Tip:&r Encasing cogs with andesite casing stops sideways interlocking.',
                ],
                task_count=16,
                deps=[2],
                rewards=[item('minecraft:oak_planks', 64)],
                subtitle='Kinetics',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='create:large_cogwheel',
                title='Large Cogwheels',
                desc=[
                    '&6Goal:&r Craft &68 large cogwheels&r.',
                    '',
                    'Pair large + small for gear ratios — speed up or slow down machines (stress changes too).',
                ],
                task_count=8,
                deps=[3],
                rewards=[item('create:cogwheel', 8), xp_levels(1)],
                subtitle='Kinetics',
            ),
            Quest(
                n=5,
                x=5,
                y=-2.5,
                task='create:water_wheel',
                title='Water Power',
                desc=[
                    '&6Goal:&r Craft a water wheel.',
                    '',
                    'Flowing water against the blades generates free SU (stress units). One or two wheels power a whole andesite workshop.',
                    '',
                    "&7Tip:&r Later you'll want steam engines, diesel, or electricity for megabases.",
                    '&7Next:&r Build andesite casings into a press + mixer line.',
                ],
                deps=[2],
                rewards=[item('create:shaft', 16), item('minecraft:water_bucket', 2)],
                size=1.5,
                subtitle='Power',
            ),
            Quest(
                n=6,
                x=5,
                y=-4.5,
                task='create:windmill_bearing',
                title='Windmill Bearing',
                desc=[
                    '&6Goal:&r Craft a windmill bearing.',
                    '',
                    'Sail-powered SU when you have space for a big windmill — optional alternative to water wheels.',
                ],
                deps=[5],
                rewards=[item('minecraft:white_wool', 32), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=7,
                x=5,
                y=2.5,
                task='create:andesite_casing',
                title='Andesite Casing',
                desc=[
                    '&6Goal:&r Craft &616 andesite casings&r.',
                    '',
                    'Stripped logs + andesite alloy. Almost every andesite machine is built on casing.',
                ],
                task_count=16,
                deps=[2],
                rewards=[item('create:andesite_alloy', 16)],
                subtitle='Machines',
            ),
            Quest(
                n=8,
                x=7.5,
                y=2.5,
                task='create:mechanical_press',
                title='Mechanical Press',
                desc=[
                    '&6Goal:&r Build a Mechanical Press.',
                    '',
                    'Presses compact plates, smash items on a depot, and unlock sheet metal for pipes and casings.',
                    '',
                    '&7Tip:&r Power from the side; put a depot or basin underneath.',
                ],
                deps=[7],
                rewards=[item('minecraft:iron_block', 2), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=9,
                x=10,
                y=2.5,
                task='create:basin',
                title='Basin',
                desc=[
                    '&6Goal:&r Craft a Basin.',
                    '',
                    'Mixers, presses, and bulk crafting use basins — dough, alloys, concrete, brass later with heat.',
                ],
                deps=[7],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Machines',
            ),
            Quest(
                n=10,
                x=12.5,
                y=2.5,
                task='create:mechanical_mixer',
                title='Mechanical Mixer',
                desc=[
                    '&6Goal:&r Build a Mechanical Mixer above a basin.',
                    '',
                    'Bulk-craft andesite alloy, dough, and (with a blaze burner) brass. Automate inputs with funnels once belts exist.',
                ],
                deps=[9],
                rewards=[item('create:whisk'), xp_levels(1)],
                size=1.5,
                subtitle='Machines',
            ),
            Quest(
                n=11,
                x=7.5,
                y=4.5,
                task='create:millstone',
                title='Millstone',
                desc=[
                    '&6Goal:&r Build a Millstone.',
                    '',
                    'Mill wheat into flour and process early bulk goods with low stress cost.',
                ],
                deps=[7],
                rewards=[item('minecraft:wheat', 32)],
                optional=True,
                subtitle='Machines',
                hide_until_deps=True,
            ),
            Quest(
                n=12,
                x=10,
                y=4.5,
                task='create:mechanical_saw',
                title='Mechanical Saw',
                desc=[
                    '&6Goal:&r Build a Mechanical Saw.',
                    '',
                    'Auto-cut logs into planks and process wood at factory scale — huge for casing spam.',
                ],
                deps=[7],
                rewards=[item('minecraft:oak_log', 32), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=13,
                x=12.5,
                y=4.5,
                task='create:encased_fan',
                title='Encased Fan',
                desc=[
                    '&6Goal:&r Build an Encased Fan.',
                    '',
                    'Point it at a processing path:',
                    '',
                    '• Over fire / lava → &6smoking / blasting&r',
                    '',
                    '• Through water → &6washing&r (nuggets from gravel!)',
                    '',
                    '• Through lava carefully → &6haunting&r',
                    '',
                    '&7Tip:&r Washing crushed ores after crushing wheels is a massive early ore multiplier.',
                ],
                deps=[7],
                rewards=[item('create:propeller', 2), xp_levels(1)],
                subtitle='Machines',
            ),
            Quest(
                n=14,
                x=10,
                y=-2.5,
                task='create:belt_connector',
                title='Belts',
                desc=[
                    '&6Goal:&r Craft &616 belt connectors&r.',
                    '',
                    'Belts move items between depots, basins, and inventories. Right-click two shafts to stretch a belt.',
                    '',
                    '&7Tip:&r Dried kelp farms pay for themselves once belts go wide.',
                ],
                task_count=16,
                deps=[3],
                rewards=[item('minecraft:dried_kelp', 32)],
                subtitle='Logistics',
            ),
            Quest(
                n=15,
                x=12.5,
                y=-2.5,
                task='create:depot',
                title='Depots',
                desc=[
                    '&6Goal:&r Craft &68 depots&r.',
                    '',
                    'Depots hold a single stack for presses, deployers, and belt handoff — the workbench of kinetics.',
                ],
                task_count=8,
                deps=[14],
                rewards=[item('create:andesite_alloy', 8), xp_levels(1)],
                subtitle='Logistics',
            ),
            Quest(
                n=16,
                x=15,
                y=-2.5,
                task='create:andesite_funnel',
                title='Andesite Funnels',
                desc=[
                    '&6Goal:&r Craft &68 andesite funnels&r.',
                    '',
                    'Pull and push items onto belts and into inventories. Brass funnels come later with filters.',
                ],
                task_count=8,
                deps=[15],
                rewards=[item('create:andesite_alloy', 8)],
                subtitle='Logistics',
            ),
            Quest(
                n=17,
                x=15,
                y=0,
                task='create:crushing_wheel',
                title='Crushing Wheels',
                desc=[
                    '&6Goal:&r Craft &62 crushing wheels&r and place them as a pair.',
                    '',
                    "Crush ores for &amore output&r than a furnace — the pack's first real ore multiplier.",
                    '',
                    '&7Tip:&r Wash crushed ores with a fan + water for extra nuggets.',
                    '&7Next:&r Hunt zinc, then blaze burners for brass.',
                ],
                task_count=2,
                deps=[8, 13],
                rewards=[item('minecraft:iron_ingot', 24), xp_levels(2)],
                size=1.5,
                subtitle='Ores',
            ),
            Quest(
                n=18,
                x=17.5,
                y=0,
                task='create:zinc_ingot',
                title='Zinc Stockpile',
                desc=[
                    '&6Goal:&r Produce &616 zinc ingots&r.',
                    '',
                    'Zinc + copper (+ heat) = brass. Mine zinc ore or crush raw zinc.',
                ],
                task_count=16,
                deps=[17],
                rewards=[item('minecraft:copper_ingot', 32), xp_levels(1)],
                subtitle='Metals',
            ),
            Quest(
                n=19,
                x=17.5,
                y=2.5,
                task='create:fluid_tank',
                title='Fluid Tanks',
                desc=[
                    '&6Goal:&r Craft &64 fluid tanks&r.',
                    '',
                    'Store water, lava, chocolate, plant oil, diesel, and liquid XP later. Stack tanks into towers.',
                    '',
                    '&7Next:&r Mechanical pumps and hose pulleys move fluids around the factory.',
                ],
                task_count=4,
                deps=[8],
                rewards=[item('minecraft:copper_ingot', 16)],
                subtitle='Fluids',
            ),
            Quest(
                n=20,
                x=20,
                y=2.5,
                task='create:mechanical_pump',
                title='Mechanical Pump',
                desc=[
                    '&6Goal:&r Build a Mechanical Pump.',
                    '',
                    'Move fluids through Create pipes under SU power — water for steam, oil for diesel, XP for enchanting.',
                ],
                deps=[19],
                rewards=[item('create:copper_sheet', 8), xp_levels(1)],
                subtitle='Fluids',
            ),
            Quest(
                n=21,
                x=20,
                y=4.5,
                task='create:hose_pulley',
                title='Hose Pulley',
                desc=[
                    '&6Goal:&r Craft a hose pulley.',
                    '',
                    'Drain or fill lakes and infinite fluid sources into your tank network.',
                ],
                deps=[20],
                rewards=[item('minecraft:dried_kelp', 16)],
                optional=True,
                subtitle='Fluids',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=20,
                y=0,
                task='create:blaze_burner',
                title='Blaze Burner',
                desc=[
                    '&6Goal:&r Craft a Blaze Burner.',
                    '',
                    'Empty burner + blaze. Feed blaze cakes or fuel to &6superheat&r for brass and heated mixes.',
                    '',
                    '&7Tip:&r Nether fortress or piglin trades. Place a Waystone before the trip.',
                    '&7Next:&r Mix copper + zinc with heat → brass age.',
                ],
                deps=[10],
                rewards=[item('minecraft:blaze_rod', 8), item('minecraft:nether_wart', 8)],
                size=1.5,
                subtitle='Brass gate',
            ),
            Quest(
                n=23,
                x=22.5,
                y=0,
                task='create:brass_ingot',
                title='Brass Age',
                desc=[
                    '&6Goal:&r Produce &632 brass ingots&r.',
                    '',
                    'Brass unlocks smart mechanisms, deployers, arms, trains, and most midgame Create addons.',
                    '',
                    '&7Tip:&r Automate brass early — precision mechanisms will eat it forever.',
                ],
                task_count=32,
                deps=[18, 22],
                rewards=[item('create:zinc_ingot', 16), item('minecraft:copper_ingot', 32), item('create:brass_sheet', 16), xp_levels(2)],
                size=1.75,
                shape='hexagon',
                subtitle='Brass',
            ),
            Quest(
                n=24,
                x=25,
                y=0,
                task='create:brass_casing',
                title='Brass Casing',
                desc=[
                    '&6Goal:&r Craft &616 brass casings&r.',
                    '',
                    'Frames deployers, mechanical arms, smart chutes, and precision machines.',
                ],
                task_count=16,
                deps=[23],
                rewards=[item('create:brass_ingot', 8)],
                subtitle='Brass',
            ),
            Quest(
                n=25,
                x=27.5,
                y=0,
                task='create:electron_tube',
                title='Electron Tubes',
                desc=[
                    '&6Goal:&r Craft &68 electron tubes&r.',
                    '',
                    'Polished rose quartz + iron plates. The redstone-smart part inside precision builds.',
                ],
                task_count=8,
                deps=[24],
                rewards=[item('minecraft:redstone', 32), item('create:rose_quartz', 8)],
                subtitle='Brass',
            ),
            Quest(
                n=26,
                x=30,
                y=0,
                task='create:mechanical_crafter',
                title='Mechanical Crafters',
                desc=[
                    '&6Goal:&r Craft &69 mechanical crafters&r.',
                    '',
                    'Arrange them into a crafting grid for sequenced assembly — how precision mechanisms are born.',
                    '',
                    '&7Tip:&r JEI shows the assembly sequence. Automate inputs with funnels/arms.',
                ],
                task_count=9,
                deps=[25],
                rewards=[item('create:electron_tube', 4), xp_levels(2)],
                size=1.5,
                subtitle='Midgame',
            ),
            Quest(
                n=27,
                x=32.5,
                y=0,
                task='create:precision_mechanism',
                title='Precision Mechanisms',
                desc=[
                    '&6Goal:&r Assemble &68 precision mechanisms&r.',
                    '',
                    'Midgame Create currency — arms, consoles, trains, and many addons want them.',
                    '',
                    "&7Tip:&r If crafting these by hand hurts, your factory isn't finished yet.",
                    '&7Next:&r Deployers and arms next — then Ore Excavation for infinite ore.',
                ],
                task_count=8,
                deps=[26],
                rewards=[item('create:brass_sheet', 16), xp_levels(3)],
                size=1.75,
                shape='gear',
                subtitle='Midgame',
            ),
            Quest(
                n=28,
                x=27.5,
                y=2.5,
                task='create:deployer',
                title='Deployer',
                desc=[
                    '&6Goal:&r Build a Deployer.',
                    '',
                    'Auto-uses items: applying tools, placing blocks, assembly sequences, farming, and more.',
                ],
                deps=[24],
                rewards=[item('create:brass_hand'), xp_levels(1)],
                subtitle='Brass machines',
            ),
            Quest(
                n=29,
                x=30,
                y=2.5,
                task='create:mechanical_arm',
                title='Mechanical Arm',
                desc=[
                    '&6Goal:&r Build a Mechanical Arm.',
                    '',
                    'Program inputs/outputs to move items between inventories without belts everywhere.',
                ],
                deps=[27, 28],
                rewards=[item('create:precision_mechanism'), xp_levels(2)],
                size=1.5,
                subtitle='Brass machines',
            ),
            Quest(
                n=30,
                x=25,
                y=-2.5,
                task='create:steam_engine',
                title='Steam Engine',
                desc=[
                    '&6Goal:&r Build a Steam Engine.',
                    '',
                    'Serious SU from water tanks + blaze burners — the jump from water wheels to real factories.',
                ],
                deps=[23],
                rewards=[item('create:copper_sheet', 16), xp_levels(2)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=31,
                x=22.5,
                y=4.5,
                task='createoreexcavation:vein_finder',
                title='Vein Finder',
                desc=[
                    '&6Goal:&r Craft a Vein Finder (Create Ore Excavation).',
                    '',
                    "Scan for infinite ore veins, then plant a drilling machine. The pack's answer to strip-mining forever.",
                    '',
                    '&7Tip:&r Best once crushing wheels make processing cheap.',
                ],
                deps=[17],
                rewards=[item('createoreexcavation:drill'), xp_levels(1)],
                subtitle='Ores',
            ),
            Quest(
                n=32,
                x=25,
                y=4.5,
                task='createoreexcavation:drilling_machine',
                title='Drilling Machine',
                desc=[
                    '&6Goal:&r Build a Drilling Machine on a found vein.',
                    '',
                    'Feed it SU and drills for passive ore. Pair with crushing + washing for absurd ingot/hour.',
                ],
                deps=[31],
                rewards=[item('create:andesite_alloy', 32), xp_levels(2)],
                size=1.5,
                subtitle='Ores',
            ),
            Quest(
                n=33,
                x=27.5,
                y=-2.5,
                task='create_new_age:generator_coil',
                title='New Age Coil',
                desc=[
                    '&6Goal:&r Craft a Create: New Age generator coil.',
                    '',
                    'Magnets and electrical generation that pair with Create kinetics — another power path beside diesel and CCA.',
                ],
                deps=[23],
                rewards=[item('create_new_age:copper_wire', 8), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=34,
                x=30,
                y=-2.5,
                task='create_new_age:basic_motor',
                title='New Age Motor',
                desc=[
                    '&6Goal:&r Craft a basic motor (Create: New Age).',
                    '',
                    'Turn electrical power back into rotation for remote workshops.',
                ],
                deps=[33],
                rewards=[item('create_new_age:magnetite_block', 2), xp_levels(1)],
                optional=True,
                subtitle='Power',
                hide_until_deps=True,
            ),
            Quest(
                n=35,
                x=15,
                y=6.5,
                task='createdeco:andesite_catwalk',
                title='Factory Catwalks',
                desc=[
                    '&6Goal:&r Craft an andesite catwalk (Create Deco).',
                    '',
                    'Industrial décor that makes factories readable — walkways, hulls, lamps, and sheet metal.',
                ],
                deps=[7],
                rewards=[item('createdeco:andesite_support', 8)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=36,
                x=17.5,
                y=6.5,
                task='copycats:copycat_block',
                title='Copycat Block',
                desc=[
                    '&6Goal:&r Craft a Copycats+ copycat block.',
                    '',
                    'Disguise technical blocks as any material — hide cables and machines inside pretty walls.',
                ],
                deps=[35],
                rewards=[item('copycats:copycat_slab', 8), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=37,
                x=20,
                y=6.5,
                task='interiors:seatwood_planks',
                title='Train Interiors',
                desc=[
                    '&6Goal:&r Craft seatwood planks (Create: Interiors).',
                    '',
                    'Furniture and seating for trains and stations — optional flair once tracks exist.',
                ],
                deps=[38],
                rewards=[item('interiors:white_chair', 2)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=38,
                x=32.5,
                y=2.5,
                task='create:track',
                title='Train Track',
                desc=[
                    '&6Goal:&r Craft &616 Create train tracks&r.',
                    '',
                    "Trains move bulk items and players across the map. Steam 'n' Rails adds more track styles and conductors later.",
                    '',
                    '&7Next:&r Beyond Brass covers conductor whistles and fuel tanks.',
                ],
                task_count=16,
                deps=[27],
                rewards=[item('create:precision_mechanism'), xp_levels(1)],
                subtitle='Trains',
            ),
            Quest(
                n=39,
                x=22.5,
                y=-4.5,
                task='create_sa:copper_magnet',
                title='Copper Magnet',
                desc=[
                    "&6Goal:&r Craft a copper magnet (Stuff 'N Additions).",
                    '',
                    'Pull nearby items — great while mining or standing near crushing outputs.',
                ],
                deps=[28],
                rewards=[item('minecraft:iron_ingot', 16)],
                optional=True,
                subtitle='Tools',
                hide_until_deps=True,
            ),
        ],
    )

