"""11. Extreme Reactors quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import A_ALTERNATOR


def chapter() -> Chapter:
    return Chapter(
        key='extreme_reactors',
        base=700,
        chapter_id='A20000000000000C',
        icon='bigreactors:basic_reactorcontroller',
        title='11. Extreme Reactors',
        subtitle='Yellorium reactors, steam turbines, and fuel reprocessing',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='bigreactors:yellorium_ingot',
                title='Yellorium',
                desc=[
                    '&6Goal:&r Smelt &616 Yellorium Ingots&r.',
                    '',
                    "Yellorite ore smelts into yellorium — Extreme Reactors' primary fuel metal.",
                    '',
                    "&7Tip:&r Deepslate yellorite appears underground; Nature's Compass won't help, so dig or use a Digital Miner filter.",
                ],
                task_count=16,
                links=require(A_ALTERNATOR),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Extreme Reactors · Fuel',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='bigreactors:graphite_ingot',
                title='Graphite Bars',
                desc=[
                    '&6Goal:&r Craft &616 Graphite Bars&r.',
                    '',
                    'Graphite is used throughout reactor and turbine crafting. Keep a chest reserved for it.',
                    '',
                    '&7Tip:&r JEI shows charcoal/coal coke routes depending on other mods present.',
                ],
                task_count=16,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Materials',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='bigreactors:basic_reactorcasing',
                title='Reactor Casing',
                desc=[
                    '&6Goal:&r Craft &624 Basic Reactor Casings&r.',
                    '',
                    'Casings form the hollow shell of a Basic reactor. Controllers, fuel rods, and ports replace face blocks.',
                    '',
                    '&7Tip:&r Start with a small cuboid; bigger reactors need proportional cooling and control rods.',
                ],
                task_count=24,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='bigreactors:basic_reactorcontroller',
                title='Reactor Controller',
                desc=[
                    '&6Goal:&r Craft a Basic Reactor Controller.',
                    '',
                    'The controller validates the multiblock and exposes heat, fuel, and power controls.',
                    '',
                    '&7Tip:&r If formation fails, check corners, hollow interior, and that only valid parts sit on the shell.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='bigreactors:basic_reactorfuelrod',
                title='Fuel Rods',
                desc=[
                    '&6Goal:&r Craft &64 Basic Reactor Fuel Rods&r.',
                    '',
                    'Fuel rods hold yellorium (and later fuels). More rods raise output and heat.',
                    '',
                    '&7Tip:&r Insert control rods above fuel columns so you can throttle the reaction.',
                ],
                task_count=4,
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='bigreactors:basic_reactorcontrolrod',
                title='Control Rods',
                desc=[
                    '&6Goal:&r Craft &62 Basic Reactor Control Rods&r.',
                    '',
                    'Control rods insert into fuel columns to moderate the reaction and prevent meltdowns.',
                    '',
                    '&7Tip:&r Keep insertion high until coolant and power taps are ready.',
                ],
                task_count=2,
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='bigreactors:basic_reactorpowertapfe_passive',
                title='Power Tap',
                desc=[
                    '&6Goal:&r Craft a Basic Passive FE Power Tap.',
                    '',
                    'Extract FE directly from a passively cooled reactor — the simplest Extreme Reactors power setup.',
                    '',
                    '&7Tip:&r Active taps and steam turbine loops unlock much higher efficiency later.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='bigreactors:basic_reactorsolidaccessport',
                title='Access Port',
                desc=[
                    '&6Goal:&r Craft a Basic Solid Access Port.',
                    '',
                    'Automate fuel insert and waste extract through the access port with pipes or transporters.',
                    '',
                    '&7Tip:&r Cyanite waste piles up — plan a reprocessor or storage before scaling fuel rods.',
                ],
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Reactor',
            ),
            Quest(
                n=8,
                x=0.0,
                y=2.5,
                task='bigreactors:cyanite_ingot',
                title='Cyanite Waste',
                desc=[
                    '&6Goal:&r Collect &68 Cyanite Ingots&r.',
                    '',
                    'Spent fuel becomes cyanite. Reprocess it toward blutonium or store it safely.',
                    '',
                    "&7Tip:&r Don't void it casually if you plan ludicrite-tier endgame fuels.",
                ],
                task_count=8,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Extreme Reactors · Fuel cycle',
            ),
            Quest(
                n=9,
                x=2.5,
                y=2.5,
                task='bigreactors:basic_turbinecasing',
                title='Turbine Housing',
                desc=[
                    '&6Goal:&r Craft &620 Basic Turbine Housings&r.',
                    '',
                    'Actively cooled reactors vent steam into a turbine multiblock for far more FE than a power tap.',
                    '',
                    '&7Tip:&r Rotor shafts, blades, coils, and a bearing complete the interior.',
                ],
                task_count=20,
                deps=[7],
                rewards=[xp_levels(2)],
                subtitle='Extreme Reactors · Turbine',
            ),
            Quest(
                n=10,
                x=5.0,
                y=2.5,
                task='bigreactors:basic_turbinecontroller',
                title='Turbine Controller',
                desc=[
                    '&6Goal:&r Craft a Basic Turbine Controller.',
                    '',
                    'Validates the turbine and shows RPM, intake, and energy output.',
                    '',
                    '&7Tip:&r Match coil count and blade count to steam supply — overspeed wastes efficiency.',
                ],
                deps=[9],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Extreme Reactors · Turbine',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='bigreactors:basic_turbinerotorblade',
                title='Rotor Blades',
                desc=[
                    '&6Goal:&r Craft &68 Basic Turbine Rotor Blades&r.',
                    '',
                    'Blades catch steam flow along the rotor shaft. Balance them with coil induction.',
                    '',
                    '&7Tip:&r Too many blades without coils stalls; too many coils without blades underproduce.',
                ],
                task_count=8,
                deps=[10],
                rewards=[xp_levels(2)],
                subtitle='Extreme Reactors · Turbine',
            ),
            Quest(
                n=12,
                x=10.0,
                y=2.5,
                task='bigreactors:reprocessorcontroller',
                title='Cyanite Reprocessor',
                desc=[
                    '&6Goal:&r Craft a Reprocessor Controller.',
                    '',
                    'The reprocessor multiblock turns cyanite waste back into useful fuels for the next tier.',
                    '',
                    '&7Tip:&r Bring fluid injectors, power ports, and casings — JEI/Patchouli show the full part list.',
                ],
                deps=[8],
                rewards=[xp_levels(2)],
                subtitle='Extreme Reactors · Fuel cycle',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='bigreactors:reinforced_reactorcontroller',
                title='Reinforced Reactor',
                desc=[
                    '&6Goal:&r Craft a Reinforced Reactor Controller.',
                    '',
                    'Reinforced parts support larger, hotter reactors and better late fuels like blutonium and ludicrite.',
                    '',
                    '&7Tip:&r Upgrade when Basic size or heat caps hold you back — not before the fuel cycle is stable.',
                ],
                deps=[12],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Extreme Reactors · Endgame',
            ),
            Quest(
                n=14,
                x=15.0,
                y=2.5,
                task='bigreactors:ludicrite_ingot',
                title='Ludicrite',
                desc=[
                    '&6Goal:&r Craft &64 Ludicrite Ingots&r.',
                    '',
                    'Ludicrite is an Extreme Reactors endgame material for top-tier components and bragging rights.',
                    '',
                    '&7Tip:&r Blutonium and End-dimension ingredients typically gate this craft — check JEI.',
                ],
                task_count=4,
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='Extreme Reactors · Endgame',
            ),
        ],
    )

