"""8. Flux Networks quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import RFTOOLS_DIMENSIONAL_CELL


def chapter() -> Chapter:
    return Chapter(
        key='flux_networks',
        base=470,
        chapter_id='A200000000000009',
        icon='fluxnetworks:flux_controller',
        title='8. Flux Networks',
        subtitle='Cross-dimensional wireless FE transfer, control, and storage',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=18.0,
                task='fluxnetworks:flux_dust',
                title='Flux from Bedrock',
                desc=[
                    '&6Goal:&r Produce &616 Flux Dust&r.',
                    '',
                    'Flux Dust is the foundation of a wireless FE network and is created through its special bedrock interaction recipe.',
                    '',
                    '&7Tip:&r Check JEI for the exact in-world process; bring enough redstone for a batch.',
                ],
                task_count=16,
                links=require(RFTOOLS_DIMENSIONAL_CELL),
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=18.0,
                task='fluxnetworks:flux_core',
                title='Flux Cores',
                desc=[
                    '&6Goal:&r Craft &68 Flux Cores&r.',
                    '',
                    'Cores turn Flux Dust into network devices and storage components.',
                    '',
                    '&7Tip:&r Keep them stocked in Refined Storage for future expansion.',
                ],
                task_count=8,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Components',
            ),
            Quest(
                n=2,
                x=5.0,
                y=18.0,
                task='fluxnetworks:flux_block',
                title='Flux Block',
                desc=[
                    '&6Goal:&r Craft &64 Flux Blocks&r.',
                    '',
                    'Flux Blocks compress network material and are used by the more capable devices.',
                    '',
                    '&7Tip:&r Automate dust and core production before building at scale.',
                ],
                task_count=4,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Components',
            ),
            Quest(
                n=3,
                x=7.5,
                y=18.0,
                task='fluxnetworks:flux_plug',
                title='Flux Plug',
                desc=[
                    '&6Goal:&r Craft a Flux Plug.',
                    '',
                    'A Plug takes FE from an attached generator, cell, or machine and inserts it into your selected wireless network.',
                    '',
                    '&7Tip:&r Attach it to the output side of Powah or RFTools storage, then set a transfer limit.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Flux Networks · Wireless input',
            ),
            Quest(
                n=4,
                x=10.0,
                y=18.0,
                task='fluxnetworks:flux_point',
                title='Flux Point',
                desc=[
                    '&6Goal:&r Craft a Flux Point.',
                    '',
                    'A Point extracts FE from the network into Refined Storage, RFTools, or Create Crafts & Additions machines.',
                    '',
                    '&7Tip:&r Use priorities and limits so one hungry machine cannot starve the entire base.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Flux Networks · Wireless output',
            ),
            Quest(
                n=5,
                x=12.5,
                y=18.0,
                task='fluxnetworks:flux_configurator',
                title='Flux Configurator',
                desc=[
                    '&6Goal:&r Craft a Flux Configurator.',
                    '',
                    'The Configurator makes network-device management quicker while building and troubleshooting.',
                    '',
                    '&7Tip:&r Name networks by purpose and use security settings on multiplayer servers.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Network tools',
            ),
            Quest(
                n=6,
                x=15.0,
                y=18.0,
                task='fluxnetworks:flux_controller',
                title='Flux Controller',
                desc=[
                    '&6Goal:&r Craft a Flux Controller.',
                    '',
                    'Controllers provide central network management and enable wireless charging for players and selected equipment.',
                    '',
                    '&7Tip:&r Review chunk loading, transfer bypass, and member permissions rather than enabling everything blindly.',
                ],
                deps=[5],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Flux Networks · Network control',
            ),
            Quest(
                n=7,
                x=17.5,
                y=18.0,
                task='fluxnetworks:basic_flux_storage',
                title='Basic Flux Storage',
                desc=[
                    '&6Goal:&r Craft Basic Flux Storage.',
                    '',
                    'Network storage absorbs surplus generation and covers demand spikes without extra cables.',
                    '',
                    '&7Tip:&r Keep a physical Powah or RFTools buffer too, so critical machines have layered resilience.',
                ],
                deps=[4],
                rewards=[xp_levels(2)],
                subtitle='Flux Networks · Energy storage',
            ),
            Quest(
                n=8,
                x=20.0,
                y=18.0,
                task='fluxnetworks:herculean_flux_storage',
                title='Herculean Storage',
                desc=[
                    '&6Goal:&r Upgrade to Herculean Flux Storage.',
                    '',
                    'Herculean storage supports factory-scale reserves for autocrafting, teleportation, and dimension upkeep.',
                    '',
                    '&7Tip:&r Watch actual input and output rates; capacity alone does not solve a generation shortage.',
                ],
                deps=[7],
                rewards=[xp_levels(2)],
                subtitle='Flux Networks · Energy storage',
            ),
            Quest(
                n=9,
                x=22.5,
                y=18.0,
                task='fluxnetworks:gargantuan_flux_storage',
                title='Gargantuan Storage',
                desc=[
                    '&6Goal:&r Craft Gargantuan Flux Storage.',
                    '',
                    'The largest survival Flux storage tier is an endgame reservoir for a fully wireless power grid.',
                    '',
                    '&7Tip:&r Feed it with automated high-tier Powah generation and monitor it from your RFTools control room.',
                ],
                deps=[8],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Flux Networks · Energy storage',
            ),
        ],
    )

