"""8. Flux Networks quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import RFTOOLS_DIMENSIONAL_CELL
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='flux_networks',
        base=470,
        chapter_id='0200000000000009',
        icon='fluxnetworks:flux_controller',
        title='8. Flux Networks',
        subtitle='Cross-dimensional wireless FE transfer, control, and storage',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=18.0,
                task='fluxnetworks:flux_dust',
                title='Flux from Bedrock',
                desc=tutorial(
                    'Produce &616 Flux Dust&r.',
                    why='Foundation material for a wireless FE network — made via the special bedrock interaction recipe.',
                    steps=[
                        'Open JEI on Flux Dust and note the exact in-world bedrock process.',
                        'Bring redstone (and any other listed ingredients) to bedrock level.',
                        'Run the interaction until you have a batch of 16+ dust.',
                    ],
                    tip='Batch dust early — every Flux device eats cores made from it.',
                    nxt='Craft Flux Cores.',
                ),
                task_count=16,
                links=require(RFTOOLS_DIMENSIONAL_CELL),
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=18.0,
                task='fluxnetworks:flux_core',
                title='Flux Cores',
                desc=tutorial(
                    'Craft &68 Flux Cores&r.',
                    why='Cores turn Flux Dust into network devices and storage components.',
                    steps=[
                        'Craft eight Flux Cores from dust and JEI ingredients.',
                        'Store extras in Refined Storage for Plug/Point/Controller crafts.',
                        'Keep producing dust so cores never gate expansion.',
                    ],
                    tip='Stock cores before you place half a wireless grid.',
                    nxt='Compress into Flux Blocks.',
                ),
                task_count=8,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Components',
            ),
            Quest(
                n=2,
                x=5.0,
                y=18.0,
                task='fluxnetworks:flux_block',
                title='Flux Block',
                desc=tutorial(
                    'Craft &64 Flux Blocks&r.',
                    why='Compressed network material used by the more capable Flux devices.',
                    steps=[
                        'Craft four Flux Blocks from cores/dust per JEI.',
                        'Hold them for Plugs, Points, Controllers, and storage tiers.',
                        'Automate dust → core → block before building at scale.',
                    ],
                    tip='Automate the material chain once wireless FE becomes factory-critical.',
                    nxt='Craft a Flux Plug to inject FE.',
                ),
                task_count=4,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Components',
            ),
            Quest(
                n=3,
                x=7.5,
                y=18.0,
                task='fluxnetworks:flux_plug',
                title='Flux Plug',
                desc=tutorial(
                    'Craft a Flux Plug.',
                    why='Takes FE from an attached generator, cell, or machine and inserts it into your wireless network.',
                    steps=[
                        'Place the Flux Plug on the output face of a Powah or RFTools energy cell.',
                        'Open the Plug GUI, create or select a named network, and join it.',
                        'Set a transfer limit so one Plug does not dump the entire buffer instantly.',
                    ],
                    tip='Name the network (“Main Factory”) before placing the first Point.',
                    nxt='Craft a Flux Point to pull FE out.',
                ),
                deps=[2],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Flux Networks · Wireless input',
            ),
            Quest(
                n=4,
                x=10.0,
                y=18.0,
                task='fluxnetworks:flux_point',
                title='Flux Point',
                desc=tutorial(
                    'Craft a Flux Point.',
                    why='Extracts FE from the wireless network into RS, RFTools, Create electrical machines, and more.',
                    steps=[
                        'Place the Flux Point on a machine or cell that should receive FE.',
                        'Join the same network name as your Plug.',
                        'Set priority and transfer limits so one hungry machine cannot starve the base.',
                    ],
                    tip='High priority for RS Controllers and teleporters; low for optional gadgets.',
                    nxt='Craft a Configurator, then a Controller.',
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Flux Networks · Wireless output',
            ),
            Quest(
                n=5,
                x=12.5,
                y=18.0,
                task='fluxnetworks:flux_configurator',
                title='Flux Configurator',
                desc=tutorial(
                    'Craft a Flux Configurator.',
                    why='Speeds up network-device management while building and troubleshooting.',
                    steps=[
                        'Craft the Configurator and keep it on your hotbar.',
                        'Use it to edit network membership, names, and device settings without digging GUIs.',
                        'On multiplayer, set security so strangers cannot join your FE grid.',
                    ],
                    tip='Name networks by purpose and lock them on servers.',
                    nxt='Add a Flux Controller for central management.',
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Flux Networks · Network tools',
            ),
            Quest(
                n=6,
                x=15.0,
                y=18.0,
                task='fluxnetworks:flux_controller',
                title='Flux Controller',
                desc=tutorial(
                    'Craft a Flux Controller.',
                    why='Central network management — enables wireless charging options and advanced network features.',
                    steps=[
                        'Place the Flux Controller and join it to your main network.',
                        'Open network settings: review chunk loading, transfer bypass, and member permissions.',
                        'Enable only the features you need — do not turn everything on blindly.',
                    ],
                    tip='Wireless player charging still needs surplus generation wired in via Plugs.',
                    nxt='Add Flux Storage for wireless buffers.',
                ),
                deps=[5],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Flux Networks · Network control',
            ),
            Quest(
                n=7,
                x=17.5,
                y=18.0,
                task='fluxnetworks:basic_flux_storage',
                title='Basic Flux Storage',
                desc=tutorial(
                    'Craft Basic Flux Storage.',
                    why='Network storage absorbs surplus generation and covers demand spikes without extra cables.',
                    steps=[
                        'Place Basic Flux Storage and join it to the same network as Plugs/Points.',
                        'Confirm it charges from Plug surplus and discharges when Points demand FE.',
                        'Keep a physical Powah/RFTools buffer too for layered resilience.',
                    ],
                    tip='Wireless + physical buffers beat either alone when teleporters spike.',
                    nxt='Upgrade to Herculean storage.',
                ),
                deps=[4],
                rewards=[xp_levels(2)],
                subtitle='Flux Networks · Energy storage',
            ),
            Quest(
                n=8,
                x=20.0,
                y=18.0,
                task='fluxnetworks:herculean_flux_storage',
                title='Herculean Storage',
                desc=tutorial(
                    'Upgrade to Herculean Flux Storage.',
                    why='Factory-scale reserves for autocrafting, teleportation, and dimension upkeep.',
                    steps=[
                        'Craft Herculean Flux Storage and join the main network.',
                        'Watch actual input/output rates in the GUI under load.',
                        'If capacity is full but Points still starve, add generation — not only storage.',
                    ],
                    tip='Capacity alone does not solve a generation shortage.',
                    nxt='Cap the grid with Gargantuan storage.',
                ),
                deps=[7],
                rewards=[xp_levels(2)],
                subtitle='Flux Networks · Energy storage',
            ),
            Quest(
                n=9,
                x=22.5,
                y=18.0,
                task='fluxnetworks:gargantuan_flux_storage',
                title='Gargantuan Storage',
                desc=tutorial(
                    'Craft Gargantuan Flux Storage.',
                    why='Largest survival Flux storage tier — endgame reservoir for a fully wireless power grid.',
                    steps=[
                        'Craft Gargantuan Flux Storage and attach it to the main network.',
                        'Feed it from automated high-tier Powah (reactors/Nitro) via Plugs.',
                        'Monitor fill from your RFTools control room or Flux GUI during peak autocrafting.',
                    ],
                    tip='Pair Gargantuan storage with Nitro-tier generation for real endgame wireless FE.',
                    nxt='Flux chapter complete — wireless power your factories and dimensions.',
                ),
                deps=[8],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Flux Networks · Energy storage',
            ),
        ],
    )
