"""1. Getting Started quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, connected, item, xp_levels
from ftb_quests.ids import CREATE_START, STORAGE_START, AUTOMATION_START


def chapter() -> Chapter:
    return Chapter(
        key='foundations',
        base=100,
        chapter_id='A200000000000001',
        icon='minecraft:iron_pickaxe',
        title='1. Getting Started',
        subtitle='Wood, iron, food, Waystones — leave the caves ready',
        quest_links=[
            connected(CREATE_START, 22.5, 0.0),
            connected(STORAGE_START, 22.5, 2.5),
            connected(AUTOMATION_START, 22.5, -2.5),
        ],
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='minecraft:book',
                title='Welcome to Fabulously Create',
                desc=[
                    '&6Goal:&r Open this book and claim your starter kit.',
                    '',
                    'This pack is about &6Create factories&r, smarter storage, Silent Gear tools, Integrated Dynamics logistics, and late-game flight.',
                    '',
                    'Quests complete when items are in your inventory — they are &anot consumed&r. Optional quests are dashed outlines; skip them anytime.',
                    '',
                    'Follow the &6dependency lines&r — chapters chain together (iron → Create → brass → automation → netherite). Side paths unlock as you progress.',
                    '',
                    "&7Tip:&r Claim rewards from completed quests. Use JEI (R) on any item you don't recognize.",
                    '&7Next:&r Gather wood, stone, and iron — then plant a Waystone before you dig deep.',
                ],
                rewards=[item('minecraft:bread', 16), item('minecraft:torch', 32), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Start here',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='minecraft:oak_log',
                title='Timber!',
                desc=[
                    '&6Goal:&r Collect &616 oak logs&r.',
                    '',
                    'Wood is your first building block: crafting tables, charcoal, Create casings, and early chests all burn through logs.',
                    '',
                    '&7Tip:&r Any wood works for most recipes — explore once you have iron.',
                    '&7Next:&r Craft a workbench, then start a stone stockpile.',
                ],
                task_count=16,
                deps=[0],
                rewards=[item('minecraft:apple', 8), item('minecraft:stick', 32)],
                subtitle='Gathering',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='minecraft:crafting_table',
                title='Workbench',
                desc=[
                    '&6Goal:&r Craft a crafting table.',
                    '',
                    'Early recipes still start here. Create automates later — until then, a bench (or Crafting on a Stick) is your workshop.',
                    '',
                    '&7Next:&r Mine cobble for furnaces and generators.',
                ],
                deps=[1],
                rewards=[item('minecraft:chest', 2), xp_levels(1)],
                subtitle='Gathering',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='minecraft:cobblestone',
                title='Stone Stockpile',
                desc=[
                    '&6Goal:&r Mine &664 cobblestone&r.',
                    '',
                    'Stone feeds furnaces, cobble gens, Create casings, and endless scaffolding. Grab more than feels polite.',
                    '',
                    "&7Tip:&r A stone pickaxe unlocks iron ore. Don't dig straight down.",
                    '&7Next:&r Smelt a furnace, then hunt iron.',
                ],
                task_count=64,
                deps=[2],
                rewards=[item('minecraft:torch', 32), item('minecraft:coal', 16)],
                subtitle='Gathering',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='minecraft:furnace',
                title='First Fire',
                desc=[
                    '&6Goal:&r Craft a furnace.',
                    '',
                    'Smelting unlocks metals. Coal is ideal; charcoal from logs works if caves are stingy.',
                    '',
                    '&7Next:&r Smelt a stack of iron — Create starts there.',
                ],
                deps=[3],
                rewards=[item('minecraft:coal', 32), xp_levels(1)],
                subtitle='Smelting',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0,
                task='minecraft:coal',
                title='Fuel Reserve',
                desc=[
                    '&6Goal:&r Stockpile &632 coal&r.',
                    '',
                    'Furnaces, Iron Furnaces, blaze burners (later), and long mining trips all want fuel on hand.',
                    '',
                    '&7Tip:&r Coal blocks compress storage. Charcoal works in furnaces too, but this quest wants coal ore/smelted coal.',
                ],
                task_count=32,
                deps=[4],
                rewards=[item('minecraft:coal_block', 2)],
                optional=True,
                subtitle='Fuel',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=12.5,
                y=-2,
                task='minecraft:iron_ingot',
                title='Iron Stockpile',
                desc=[
                    '&6Goal:&r Smelt &632 iron ingots&r.',
                    '',
                    "Iron is the pack's first real gate: Create andesite alloy, Pipez, Iron Chests/Furnaces, Construction Sticks, and more.",
                    '',
                    '&7Tip:&r FTB Ultimine (hold Grave / ` by default) clears connected ore fast when you hit a Large Ore Vein.',
                    '&7Next:&r Make an iron pickaxe, then set a Waystone before deep caves.',
                ],
                task_count=32,
                deps=[4],
                rewards=[item('minecraft:iron_pickaxe'), item('minecraft:shield'), xp_levels(2)],
                size=1.5,
                subtitle='Iron',
            ),
            Quest(
                n=7,
                x=15,
                y=-2,
                task='minecraft:iron_pickaxe',
                title='Iron Tools',
                desc=[
                    '&6Goal:&r Craft an iron pickaxe.',
                    '',
                    "Diamonds and Create's deeper ores wait below. Bring food, torches, and a way home.",
                    '',
                    '&7Next:&r Find diamonds, then plant a Waystone at base.',
                ],
                deps=[6],
                rewards=[item('minecraft:cooked_beef', 16), item('minecraft:lantern', 8)],
                subtitle='Iron',
            ),
            Quest(
                n=8,
                x=15,
                y=0,
                task='minecraft:copper_ingot',
                title='Copper Cache',
                desc=[
                    '&6Goal:&r Smelt &632 copper ingots&r.',
                    '',
                    'Copper becomes Create fluid pipes, backtanks, and brass (with zinc). Large copper veins are common — fill a chest.',
                    '',
                    "&7Tip:&r JEI: look ahead at brass and fluid tanks so you know why you're hoarding.",
                ],
                task_count=32,
                deps=[6],
                rewards=[item('minecraft:copper_block', 4), xp_levels(1)],
                subtitle='Metals',
            ),
            Quest(
                n=9,
                x=17.5,
                y=-2,
                task='minecraft:diamond',
                title='Sparkly Rocks',
                desc=[
                    '&6Goal:&r Find &65 diamonds&r.',
                    '',
                    "Save some for a pickaxe and enchanting. Create's midgame wants &6brass and precision mechanisms&r more than full diamond armor.",
                    '',
                    '&7Tip:&r Silent Gear can stretch materials further once you unlock blueprints.',
                ],
                task_count=5,
                deps=[7],
                rewards=[item('minecraft:experience_bottle', 8), xp_levels(2)],
                size=1.5,
                subtitle='Diamonds',
            ),
            Quest(
                n=10,
                x=20,
                y=-2,
                task='waystones:waystone',
                title='Set a Waystone',
                desc=[
                    '&6Goal:&r Craft and place a Waystone near your base.',
                    '',
                    'Warp home after every mining trip. Deaths hurt less with a recall point — especially once you hit the Nether for blaze burners.',
                    '',
                    '&7Tip:&r Warp Stones make temporary links while exploring. Sharestones help multiplayer bases.',
                    "&7Next:&r You're ready for Turning Gears — or finish the food/QoL side path first.",
                ],
                deps=[9],
                rewards=[item('waystones:warp_stone'), item('minecraft:ender_pearl', 4)],
                size=1.5,
                shape='hexagon',
                subtitle='Travel',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='minecraft:bread',
                title='Carb Loading',
                desc=[
                    '&6Goal:&r Bake &616 bread&r.',
                    '',
                    'Hunger kills more early bases than creepers. Keep a stack for every cave run.',
                ],
                task_count=16,
                deps=[3],
                rewards=[item('minecraft:wheat_seeds', 32), item('minecraft:bone_meal', 16)],
                optional=True,
                subtitle='Food',
                hide_until_deps=True,
            ),
            Quest(
                n=12,
                x=10,
                y=2.5,
                task='farmersdelight:cooking_pot',
                title='Cooking Pot',
                desc=[
                    "&6Goal:&r Craft a Farmer's Delight cooking pot.",
                    '',
                    'Meals beat plain steaks for saturation. Pair with a cutting board and stove for a proper kitchen.',
                    '',
                    '&7Tip:&r Later, Slice & Dice lets Create automate cutting boards — see Wires & Wits.',
                    "&7Next:&r Add a stove and knife when you're settled.",
                ],
                deps=[4],
                rewards=[item('farmersdelight:cabbage_seeds', 4), item('farmersdelight:tomato_seeds', 4), item('farmersdelight:onion', 4)],
                subtitle='Food',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='farmersdelight:stove',
                title="Farmer's Kitchen",
                desc=[
                    "&6Goal:&r Craft a Farmer's Delight stove.",
                    '',
                    'The stove is the heart of meal cooking — fire it up next to your cooking pot.',
                ],
                deps=[12],
                rewards=[item('farmersdelight:skillet'), xp_levels(1)],
                subtitle='Food',
            ),
            Quest(
                n=14,
                x=15,
                y=2.5,
                task='farmersdelight:iron_knife',
                title='Kitchen Knife',
                desc=[
                    '&6Goal:&r Craft an iron knife.',
                    '',
                    'Knives process meats and plants on a cutting board — required for many Delight recipes.',
                ],
                deps=[13],
                rewards=[item('farmersdelight:cutting_board')],
                optional=True,
                subtitle='Food',
                hide_until_deps=True,
            ),
            Quest(
                n=15,
                x=10,
                y=4.5,
                task='comforts:sleeping_bag_red',
                title='Portable Bed',
                desc=[
                    '&6Goal:&r Craft a sleeping bag.',
                    '',
                    "Unlike beds, it &adoesn't set your respawn&r — perfect for Nether trips and caves without wrecking your Waystone home.",
                ],
                deps=[7],
                rewards=[item('minecraft:white_wool', 16), xp_levels(1)],
                optional=True,
                subtitle='QoL',
                hide_until_deps=True,
            ),
            Quest(
                n=16,
                x=12.5,
                y=4.5,
                task='crafting_on_a_stick:crafting_table',
                title='Crafting on a Stick',
                desc=[
                    '&6Goal:&r Craft a crafting table on a stick.',
                    '',
                    'Portable crafting from your hotbar — huge quality-of-life while strip-mining or wiring factories.',
                    '',
                    '&7Tip:&r There are sticks for smithing, stonecutter, grindstone, and more.',
                ],
                deps=[7],
                rewards=[item('minecraft:stick', 16), xp_levels(1)],
                subtitle='QoL',
            ),
            Quest(
                n=17,
                x=15,
                y=4.5,
                task='ironchest:iron_chest',
                title='Iron Chest',
                desc=[
                    '&6Goal:&r Upgrade to an Iron Chest.',
                    '',
                    'More slots than wood. Keep upgrading toward gold / diamond / obsidian as junk piles grow.',
                    '',
                    '&7Next:&r Iron Furnaces speed smelting while you prep Create.',
                ],
                deps=[6],
                rewards=[item('minecraft:chest', 4), item('minecraft:iron_ingot', 8)],
                subtitle='Storage',
            ),
            Quest(
                n=18,
                x=17.5,
                y=4.5,
                task='ironfurnaces:iron_furnace',
                title='Iron Furnace',
                desc=[
                    '&6Goal:&r Craft an Iron Furnace.',
                    '',
                    'Faster smelting now; gold and diamond tiers wait until throughput really matters.',
                ],
                deps=[17],
                rewards=[item('minecraft:coal_block', 2), xp_levels(1)],
                subtitle='Smelting',
            ),
            Quest(
                n=19,
                x=10,
                y=-4,
                task='naturescompass:naturescompass',
                title="Nature's Compass",
                desc=[
                    "&6Goal:&r Craft a Nature's Compass.",
                    '',
                    'Hunt biomes for crops, building vibes, or menril-friendly areas before Integrated Dynamics.',
                ],
                deps=[10],
                rewards=[item('minecraft:map'), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=12.5,
                y=-4,
                task='explorerscompass:explorerscompass',
                title="Explorer's Compass",
                desc=[
                    "&6Goal:&r Craft an Explorer's Compass.",
                    '',
                    'Locate structures for loot. Reminder: &6Lootr&r makes structure chests per-player — no racing friends.',
                ],
                deps=[10],
                rewards=[item('minecraft:ender_pearl', 2), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=15,
                y=-4,
                task='supplementaries:wrench',
                title='Supplementaries Wrench',
                desc=[
                    '&6Goal:&r Craft a Supplementaries wrench.',
                    '',
                    "Rotate and tweak functional décor — faucets, turn tables, and more. Great alongside Create's own wrench.",
                ],
                deps=[16],
                rewards=[item('supplementaries:jar', 4)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=-4,
                task='another_furniture:oak_chair',
                title='Furnish the Base',
                desc=[
                    '&6Goal:&r Craft an oak chair (Another Furniture).',
                    '',
                    'Optional décor goal — make the base feel lived-in before the factory takes over every block.',
                ],
                deps=[17],
                rewards=[item('another_furniture:oak_table'), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=20,
                y=0,
                task='minecraft:leather',
                title='Leather Bundle',
                desc=[
                    '&6Goal:&r Collect &616 leather&r.',
                    '',
                    'Backpacks, books, and early armor all want leather. Breed cows or hunt while exploring.',
                    '',
                    '&7Next:&r Bags & Blades opens with a Sophisticated Backpack.',
                ],
                task_count=16,
                deps=[6],
                rewards=[item('minecraft:string', 16), xp_levels(1)],
                optional=True,
                subtitle='Gathering',
                hide_until_deps=True,
            ),
        ],
    )

