"""1. Getting Started quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, connected, item, xp_levels
from ftb_quests.ids import CREATE_START, STORAGE_START, AUTOMATION_START
from ftb_quests.text import overview, tutorial


def chapter() -> Chapter:
    return Chapter(
        key='foundations',
        base=100,
        chapter_id='0200000000000001',
        icon='minecraft:iron_pickaxe',
        title='1. Getting Started',
        subtitle='Wood, iron, food, Waystones — leave the caves ready',
        quest_links=[
            connected(CREATE_START, 22.5, 0.0),
            connected(STORAGE_START, 22.5, 2.5),
            connected(AUTOMATION_START, 22.5, -2.5),
        ],
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='minecraft:book',
                title='Welcome to Fabulously Create',
                desc=overview(
                    'This pack is about &6Create factories&r, smarter storage, Silent Gear tools, Integrated Dynamics logistics, and late-game flight. Quests complete when items are in your inventory — they are &anot consumed&r. Optional quests are dashed outlines; skip them anytime.',
                    you_will=[
                        'Follow dependency lines — chapters chain (iron → Create → brass → automation → netherite)',
                        'Claim rewards from completed quests',
                        'Use JEI (R) on any unfamiliar item',
                    ],
                    tip='Side paths unlock as you progress. Start with wood, stone, and iron, then plant a Waystone before you dig deep.',
                ),
                rewards=[item('minecraft:bread', 16), item('minecraft:torch', 32), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Start here',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='minecraft:oak_log',
                title='Timber!',
                desc=tutorial(
                    'Collect &616 oak logs&r.',
                    why='Wood is your first building block: crafting tables, charcoal, Create casings, and early chests all burn through logs.',
                    steps=[
                        'Punch or axe nearby trees until you have 16 oak logs in inventory.',
                        'Keep a few extras for a crafting table and sticks.',
                        'Plant saplings near your spawn so the next harvest is closer.',
                    ],
                    tip='Any wood works for most recipes — explore once you have iron.',
                    nxt='Craft a workbench, then start a stone stockpile.',
                ),
                task_count=16,
                deps=[0],
                rewards=[item('minecraft:apple', 8), item('minecraft:stick', 32)],
                subtitle='Gathering',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='minecraft:crafting_table',
                title='Workbench',
                desc=tutorial(
                    'Craft a crafting table.',
                    why='Early recipes still start here. Create automates later — until then, a bench (or Crafting on a Stick) is your workshop.',
                    steps=[
                        'Craft planks from 1 log (4 planks).',
                        'Arrange 4 planks in a 2×2 to make a crafting table.',
                        'Place it somewhere easy to reach and open it to unlock the 3×3 grid.',
                    ],
                    nxt='Mine cobble for furnaces and generators.',
                ),
                deps=[1],
                rewards=[item('minecraft:chest', 2), xp_levels(1)],
                subtitle='Gathering',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0,
                task='minecraft:cobblestone',
                title='Stone Stockpile',
                desc=tutorial(
                    'Mine &664 cobblestone&r.',
                    why='Stone feeds furnaces, cobble gens, Create casings, and endless scaffolding. Grab more than feels polite.',
                    steps=[
                        'Craft a wooden pickaxe, then mine 3 cobble for a stone pickaxe.',
                        'Dig a starter mine or quarry a hillside until you hold 64 cobble.',
                        'Stash extras in a chest — you will spend stacks on furnaces and Create.',
                    ],
                    tip="A stone pickaxe unlocks iron ore. Don't dig straight down.",
                    nxt='Smelt a furnace, then hunt iron.',
                ),
                task_count=64,
                deps=[2],
                rewards=[item('minecraft:torch', 32), item('minecraft:coal', 16)],
                subtitle='Gathering',
            ),
            Quest(
                n=4,
                x=10,
                y=0,
                task='minecraft:furnace',
                title='First Fire',
                desc=tutorial(
                    'Craft a furnace.',
                    why='Smelting unlocks metals. Coal is ideal; charcoal from logs works if caves are stingy.',
                    steps=[
                        'Surround the crafting grid edges with 8 cobblestone (leave the center empty).',
                        'Place the furnace and put fuel in the bottom slot (coal or charcoal).',
                        'Smelt a few logs into charcoal if you still need fuel for iron.',
                    ],
                    nxt='Smelt a stack of iron — Create starts there.',
                ),
                deps=[3],
                rewards=[item('minecraft:coal', 32), xp_levels(1)],
                subtitle='Smelting',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0,
                task='minecraft:coal',
                title='Fuel Reserve',
                desc=tutorial(
                    'Stockpile &632 coal&r.',
                    why='Furnaces, Iron Furnaces, blaze burners (later), and long mining trips all want fuel on hand.',
                    steps=[
                        'Mine coal ore in caves (Y levels vary — check exposed cliffs too).',
                        'Collect until you have 32 coal (or smelt coal ore if needed).',
                        'Optional: craft coal blocks to compress storage for later trips.',
                    ],
                    tip='Charcoal works in furnaces too, but this quest wants coal ore/smelted coal.',
                ),
                task_count=32,
                deps=[4],
                rewards=[item('minecraft:coal_block', 2)],
                optional=True,
                subtitle='Fuel',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=12.5,
                y=-2,
                task='minecraft:iron_ingot',
                title='Iron Stockpile',
                desc=tutorial(
                    'Smelt &632 iron ingots&r.',
                    why="Iron is the pack's first real gate: Create andesite alloy, Pipez, Iron Chests/Furnaces, Construction Sticks, and more.",
                    steps=[
                        'Mine iron ore with a stone (or better) pickaxe — bring torches and food.',
                        'Smelt raw iron / ore in your furnace until you have 32 ingots.',
                        'Stash a chest of extras; Turning Gears and Bags & Blades both spend iron fast.',
                    ],
                    tip='FTB Ultimine (hold Grave / ` by default) clears connected ore fast when you hit a Large Ore Vein.',
                    nxt='Make an iron pickaxe, then set a Waystone before deep caves.',
                ),
                task_count=32,
                deps=[4],
                rewards=[item('minecraft:iron_pickaxe'), item('minecraft:shield'), xp_levels(2)],
                size=1.5,
                subtitle='Iron',
            ),
            Quest(
                n=7,
                x=15,
                y=-2,
                task='minecraft:iron_pickaxe',
                title='Iron Tools',
                desc=tutorial(
                    'Craft an iron pickaxe.',
                    why="Diamonds and Create's deeper ores wait below. Bring food, torches, and a way home.",
                    steps=[
                        'Craft sticks if needed (2 planks → 4 sticks).',
                        'Craft an iron pickaxe: 3 iron ingots across the top, 2 sticks down the middle.',
                        'Optional: craft a shield and sword before your first deep trip.',
                    ],
                    nxt='Find diamonds, then plant a Waystone at base.',
                ),
                deps=[6],
                rewards=[item('minecraft:cooked_beef', 16), item('minecraft:lantern', 8)],
                subtitle='Iron',
            ),
            Quest(
                n=8,
                x=15,
                y=0,
                task='minecraft:copper_ingot',
                title='Copper Cache',
                desc=tutorial(
                    'Smelt &632 copper ingots&r.',
                    why='Copper becomes Create fluid pipes, backtanks, and brass (with zinc). Large copper veins are common — fill a chest.',
                    steps=[
                        'Mine copper ore (often in large blobs near stone / deepslate).',
                        'Smelt until you hold 32 copper ingots.',
                        'Keep a dedicated chest — fluid tanks and brass will empty it later.',
                    ],
                    tip="JEI: look ahead at brass and fluid tanks so you know why you're hoarding.",
                ),
                task_count=32,
                deps=[6],
                rewards=[item('minecraft:copper_block', 4), xp_levels(1)],
                subtitle='Metals',
            ),
            Quest(
                n=9,
                x=17.5,
                y=-2,
                task='minecraft:diamond',
                title='Sparkly Rocks',
                desc=tutorial(
                    'Find &65 diamonds&r.',
                    why="Save some for a pickaxe and enchanting. Create's midgame wants &6brass and precision mechanisms&r more than full diamond armor.",
                    steps=[
                        'Mine around deepslate levels with your iron pickaxe and plenty of torches.',
                        'Collect 5 diamonds (ores or loot — Lootr chests are per-player).',
                        'Craft a diamond pickaxe when ready; bank extras for enchanting later.',
                    ],
                    tip='Silent Gear can stretch materials further once you unlock blueprints.',
                ),
                task_count=5,
                deps=[7],
                rewards=[item('minecraft:experience_bottle', 8), xp_levels(2)],
                size=1.5,
                subtitle='Diamonds',
            ),
            Quest(
                n=10,
                x=20,
                y=-2,
                task='waystones:waystone',
                title='Set a Waystone',
                desc=tutorial(
                    'Craft and place a Waystone near your base.',
                    why='Warp home after every mining trip. Deaths hurt less with a recall point — especially once you hit the Nether for blaze burners.',
                    steps=[
                        'Craft a Waystone (check JEI for the recipe — usually stone + obsidian + pearls / nebula).',
                        'Place it at your base entrance and activate / name it.',
                        'Carry a Warp Stone for temporary links while exploring.',
                    ],
                    tip='Warp Stones make temporary links while exploring. Sharestones help multiplayer bases.',
                    nxt="You're ready for Turning Gears — or finish the food/QoL side path first.",
                ),
                deps=[9],
                rewards=[item('waystones:warp_stone'), item('minecraft:ender_pearl', 4)],
                size=1.5,
                shape='hexagon',
                subtitle='Travel',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='minecraft:bread',
                title='Carb Loading',
                desc=tutorial(
                    'Bake &616 bread&r.',
                    why='Hunger kills more early bases than creepers. Keep a stack for every cave run.',
                    steps=[
                        'Plant wheat seeds on tilled hydrated farmland near water.',
                        'Harvest wheat and craft bread (3 wheat in a row → 1 bread).',
                        'Bake until you hold 16 bread; keep a stack in your hotbar.',
                    ],
                ),
                task_count=16,
                deps=[3],
                rewards=[item('minecraft:wheat_seeds', 32), item('minecraft:bone_meal', 16)],
                optional=True,
                subtitle='Food',
                hide_until_deps=True,
            ),
            Quest(
                n=12,
                x=10,
                y=2.5,
                task='farmersdelight:cooking_pot',
                title='Cooking Pot',
                desc=tutorial(
                    "Craft a Farmer's Delight cooking pot.",
                    why='Meals beat plain steaks for saturation. Pair with a cutting board and stove for a proper kitchen.',
                    steps=[
                        'Gather brick / iron / wood as shown in JEI for the cooking pot.',
                        'Craft the pot and place it above a heat source (campfire or stove).',
                        'Add a bowl + ingredients to cook your first meal.',
                    ],
                    tip="Later, Slice & Dice lets Create automate cutting boards — see Wires & Wits.",
                    nxt="Add a stove and knife when you're settled.",
                ),
                deps=[4],
                rewards=[item('farmersdelight:cabbage_seeds', 4), item('farmersdelight:tomato_seeds', 4), item('farmersdelight:onion', 4)],
                subtitle='Food',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='farmersdelight:stove',
                title="Farmer's Kitchen",
                desc=tutorial(
                    "Craft a Farmer's Delight stove.",
                    why='The stove is the heart of meal cooking — fire it up next to your cooking pot.',
                    steps=[
                        'Craft the stove (JEI) and place it as a solid heat block.',
                        'Put your cooking pot on top (or beside, per recipe needs).',
                        'Keep fuel / fire going while you cook multi-ingredient meals.',
                    ],
                ),
                deps=[12],
                rewards=[item('farmersdelight:skillet'), xp_levels(1)],
                subtitle='Food',
            ),
            Quest(
                n=14,
                x=15,
                y=2.5,
                task='farmersdelight:iron_knife',
                title='Kitchen Knife',
                desc=tutorial(
                    'Craft an iron knife.',
                    why='Knives process meats and plants on a cutting board — required for many Delight recipes.',
                    steps=[
                        'Craft an iron knife (iron + stick pattern in JEI).',
                        'Place a cutting board on a counter.',
                        'Hold the knife and right-click ingredients on the board to process them.',
                    ],
                ),
                deps=[13],
                rewards=[item('farmersdelight:cutting_board')],
                optional=True,
                subtitle='Food',
                hide_until_deps=True,
            ),
            Quest(
                n=15,
                x=10,
                y=4.5,
                task='comforts:sleeping_bag_red',
                title='Portable Bed',
                desc=tutorial(
                    'Craft a sleeping bag.',
                    why="Unlike beds, it &adoesn't set your respawn&r — perfect for Nether trips and caves without wrecking your Waystone home.",
                    steps=[
                        'Gather wool (dye optional — red is the checklist color).',
                        'Craft a sleeping bag from JEI.',
                        'Use it to skip night or rest in dangerous dimensions without moving your spawn.',
                    ],
                ),
                deps=[7],
                rewards=[item('minecraft:white_wool', 16), xp_levels(1)],
                optional=True,
                subtitle='QoL',
                hide_until_deps=True,
            ),
            Quest(
                n=16,
                x=12.5,
                y=4.5,
                task='crafting_on_a_stick:crafting_table',
                title='Crafting on a Stick',
                desc=tutorial(
                    'Craft a crafting table on a stick.',
                    why='Portable crafting from your hotbar — huge quality-of-life while strip-mining or wiring factories.',
                    steps=[
                        'Craft the crafting-table-on-a-stick (crafting table + stick per JEI).',
                        'Put it on your hotbar and right-click to open a 3×3 anywhere.',
                        'Optional: craft sticks for smithing, stonecutter, and grindstone too.',
                    ],
                    tip='There are sticks for smithing, stonecutter, grindstone, and more.',
                ),
                deps=[7],
                rewards=[item('minecraft:stick', 16), xp_levels(1)],
                subtitle='QoL',
            ),
            Quest(
                n=17,
                x=15,
                y=4.5,
                task='ironchest:iron_chest',
                title='Iron Chest',
                desc=tutorial(
                    'Upgrade to an Iron Chest.',
                    why='More slots than wood. Keep upgrading toward gold / diamond / obsidian as junk piles grow.',
                    steps=[
                        'Place a wooden chest (or craft a new iron chest from JEI).',
                        'Craft the iron chest upgrade materials and apply / craft the Iron Chest.',
                        'Move your starter junk into it — leave room for Create alloys later.',
                    ],
                    nxt='Iron Furnaces speed smelting while you prep Create.',
                ),
                deps=[6],
                rewards=[item('minecraft:chest', 4), item('minecraft:iron_ingot', 8)],
                subtitle='Storage',
            ),
            Quest(
                n=18,
                x=17.5,
                y=4.5,
                task='ironfurnaces:iron_furnace',
                title='Iron Furnace',
                desc=tutorial(
                    'Craft an Iron Furnace.',
                    why='Faster smelting now; gold and diamond tiers wait until throughput really matters.',
                    steps=[
                        'Craft an Iron Furnace (upgrade path from a stone furnace — check JEI).',
                        'Place it and move your fuel + ore line over.',
                        'Feed it continuously while you mine copper and prep Andesite Alloy.',
                    ],
                ),
                deps=[17],
                rewards=[item('minecraft:coal_block', 2), xp_levels(1)],
                subtitle='Smelting',
            ),
            Quest(
                n=19,
                x=10,
                y=-4,
                task='naturescompass:naturescompass',
                title="Nature's Compass",
                desc=tutorial(
                    "Craft a Nature's Compass.",
                    why='Hunt biomes for crops, building vibes, or menril-friendly areas before Integrated Dynamics.',
                    steps=[
                        "Craft Nature's Compass from JEI.",
                        'Right-click, pick a biome, and follow the pointer.',
                        'Mark good farm / menril spots with a Waystone or map.',
                    ],
                ),
                deps=[10],
                rewards=[item('minecraft:map'), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=12.5,
                y=-4,
                task='explorerscompass:explorerscompass',
                title="Explorer's Compass",
                desc=tutorial(
                    "Craft an Explorer's Compass.",
                    why='Locate structures for loot. Reminder: &6Lootr&r makes structure chests per-player — no racing friends.',
                    steps=[
                        "Craft Explorer's Compass from JEI.",
                        'Select a structure type and travel toward the marker.',
                        'Loot freely — each player gets their own chest contents.',
                    ],
                ),
                deps=[10],
                rewards=[item('minecraft:ender_pearl', 2), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=15,
                y=-4,
                task='supplementaries:wrench',
                title='Supplementaries Wrench',
                desc=tutorial(
                    'Craft a Supplementaries wrench.',
                    why="Rotate and tweak functional décor — faucets, turn tables, and more. Great alongside Create's own wrench.",
                    steps=[
                        'Craft the Supplementaries wrench (JEI).',
                        'Right-click functional blocks to rotate / configure them.',
                        'Keep Create\'s wrench too — each mod touches different blocks.',
                    ],
                ),
                deps=[16],
                rewards=[item('supplementaries:jar', 4)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=-4,
                task='another_furniture:oak_chair',
                title='Furnish the Base',
                desc=tutorial(
                    'Craft an oak chair (Another Furniture).',
                    why='Optional décor goal — make the base feel lived-in before the factory takes over every block.',
                    steps=[
                        'Craft an oak chair from JEI.',
                        'Place seating near your crafting / kitchen area.',
                        'Add a table if you want the base to feel finished.',
                    ],
                ),
                deps=[17],
                rewards=[item('another_furniture:oak_table'), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=20,
                y=0,
                task='minecraft:leather',
                title='Leather Bundle',
                desc=tutorial(
                    'Collect &616 leather&r.',
                    why='Backpacks, books, and early armor all want leather. Breed cows or hunt while exploring.',
                    steps=[
                        'Hunt cows / horses, or start a small cow pen with wheat.',
                        'Collect 16 leather (or craft from rabbit hide if needed).',
                        'Save it for a Sophisticated Backpack in Bags & Blades.',
                    ],
                    nxt='Bags & Blades opens with a Sophisticated Backpack.',
                ),
                task_count=16,
                deps=[6],
                rewards=[item('minecraft:string', 16), xp_levels(1)],
                optional=True,
                subtitle='Gathering',
                hide_until_deps=True,
            ),
        ],
    )
