"""14. Immersive Engineering quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON


def chapter() -> Chapter:
    return Chapter(
        key='immersive_engineering',
        base=850,
        chapter_id='A20000000000000F',
        icon='immersiveengineering:hammer',
        title='14. Immersive Engineering',
        subtitle='Coke ovens, blast furnaces, wires, diesel, and arc furnaces',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='immersiveengineering:hammer',
                title="Engineer's Hammer",
                desc=[
                    "&6Goal:&r Craft an Engineer's Hammer.",
                    '',
                    'Multiblock formation, plate crafting, and many IE interactions start with this hammer.',
                    '',
                    '&7Tip:&r Keep it in your hotbar whenever you place coke oven or blast furnace bricks.',
                ],
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Immersive Engineering · Tools',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='immersiveengineering:manual',
                title="Engineer's Manual",
                desc=[
                    "&6Goal:&r Craft the Engineer's Manual.",
                    '',
                    'In-game documentation for every multiblock and wire — worth a permanent Curios/offhand slot.',
                    '',
                    '&7Tip:&r Form structures as the book shows; the hammer confirms when they click into place.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Tools',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='immersiveengineering:treated_wood_horizontal',
                title='Treated Wood',
                desc=[
                    '&6Goal:&r Craft &632 Treated Wood Planks&r.',
                    '',
                    'Creosote-treated wood is IE scaffolding for waterwheels, windmills, and crafting tables.',
                    '',
                    '&7Tip:&r Coke ovens produce creosote — bootstrap with Immersive or MI coke byproducts.',
                ],
                task_count=32,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Materials',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='immersiveengineering:hemp_fiber',
                title='Industrial Hemp',
                desc=[
                    '&6Goal:&r Collect &624 Industrial Hemp Fibers&r.',
                    '',
                    'Hemp makes tough fabric for windmill sails, wiring insulation, and engineering crafts.',
                    '',
                    '&7Tip:&r Farm hemp like a crop; rope and fabric recipes burn stacks.',
                ],
                task_count=24,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Materials',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='immersiveengineering:cokebrick',
                title='Coke Bricks',
                desc=[
                    '&6Goal:&r Craft &627 Coke Bricks&r.',
                    '',
                    "Build a 3×3×3 Coke Oven hollow and form it with the Engineer's Hammer.",
                    '',
                    "&7Tip:&r Coal in, coal coke + creosote out — steel's best friend.",
                ],
                task_count=27,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='immersiveengineering:coal_coke',
                title='Coal Coke',
                desc=[
                    '&6Goal:&r Produce &616 Coal Coke&r from a Coke Oven.',
                    '',
                    'Coke fuels the Blast Furnace. Creosote byproduct treats wood for more IE structures.',
                    '',
                    "&7Tip:&r Pipe creosote to a wooden barrel or tank so it doesn't void.",
                ],
                task_count=16,
                deps=[4],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='immersiveengineering:blastbrick',
                title='Blast Bricks',
                desc=[
                    '&6Goal:&r Craft &627 Blast Bricks&r.',
                    '',
                    'Assemble a Crude Blast Furnace and hammer-form it to smelt iron + coke into steel.',
                    '',
                    '&7Tip:&r Reinforced blast bricks upgrade throughput later.',
                ],
                task_count=27,
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='immersiveengineering:ingot_steel',
                title='IE Steel',
                desc=[
                    '&6Goal:&r Produce &616 Steel Ingots&r via Immersive Engineering.',
                    '',
                    'Steel feeds Heavy Engineering blocks, steel scaffolding, and HV components.',
                    '',
                    '&7Tip:&r Slag is a byproduct — stash or process it instead of clogging hoppers.',
                ],
                task_count=16,
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Steel',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='immersiveengineering:light_engineering',
                title='Light Engineering',
                desc=[
                    '&6Goal:&r Craft &68 Light Engineering Blocks&r.',
                    '',
                    'Component blocks for many mid-tier IE machines and multiblocks.',
                    '',
                    '&7Tip:&r Iron, copper, and components — batch craft with a Create press line if you like.',
                ],
                task_count=8,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Components',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='immersiveengineering:heavy_engineering',
                title='Heavy Engineering',
                desc=[
                    '&6Goal:&r Craft &64 Heavy Engineering Blocks&r.',
                    '',
                    'Steel-tier component blocks for crushers, diesel generators, and arc furnaces.',
                    '',
                    '&7Tip:&r Keep steel sheetmetal and scaffolding in the same chest.',
                ],
                task_count=4,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Components',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='immersiveengineering:workbench',
                title="Engineer's Workbench",
                desc=[
                    "&6Goal:&r Craft an Engineer's Workbench.",
                    '',
                    'Craft blueprints, schematics, and specialized IE recipes here.',
                    '',
                    '&7Tip:&r The Automated Workbench later runs blueprint recipes hands-free.',
                ],
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Crafting',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='immersiveengineering:wirecoil_copper',
                title='LV Copper Coils',
                desc=[
                    '&6Goal:&r Craft &616 LV Wire Coils&r.',
                    '',
                    'Connect LV connectors with copper coils to move IFE across your workshop.',
                    '',
                    '&7Tip:&r Wirecutters remove wires; relays extend long runs.',
                ],
                task_count=16,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='immersiveengineering:connector_lv',
                title='LV Connectors',
                desc=[
                    '&6Goal:&r Craft &68 LV Wire Connectors&r.',
                    '',
                    'Attach connectors to machines and capacitors, then spool wire between them.',
                    '',
                    '&7Tip:&r Mind voltage tiers — LV/MV/HV are not freely interchangeable.',
                ],
                task_count=8,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='immersiveengineering:capacitor_lv',
                title='LV Accumulator',
                desc=[
                    '&6Goal:&r Craft an LV Accumulator.',
                    '',
                    "Buffer IFE so waterwheels and diesel generators don't brown out machines.",
                    '',
                    '&7Tip:&r Upgrade to MV/HV capacitors as you climb wire tiers.',
                ],
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='immersiveengineering:windmill',
                title='Windmill',
                desc=[
                    '&6Goal:&r Craft a Windmill.',
                    '',
                    "Kinetic power from wind — attach sails and connect through IE's kinetic dynamo chain.",
                    '',
                    '&7Tip:&r Place high with clear air; hemp fabric sails improve capture.',
                ],
                deps=[3],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Kinetic',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='immersiveengineering:radiator',
                title='Radiator Block',
                desc=[
                    '&6Goal:&r Craft &64 Radiator Blocks&r.',
                    '',
                    'Radiators appear in Diesel Generator multiblocks and other heat-heavy IE structures.',
                    '',
                    "&7Tip:&r Follow the Engineer's Manual to form a Diesel Generator once you have biodiesel.",
                ],
                task_count=4,
                deps=[9],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='immersiveengineering:conveyor_basic',
                title='IE Conveyors',
                desc=[
                    '&6Goal:&r Craft &616 Basic Conveyors&r.',
                    '',
                    'Move items into crushers, furnaces, and assemblers without Create belts if you prefer IE logistics.',
                    '',
                    '&7Tip:&r Covered and vertical variants help keep factories tidy.',
                ],
                task_count=16,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Processing',
            ),
            Quest(
                n=17,
                x=20.0,
                y=2.5,
                task='immersiveengineering:graphite_electrode',
                title='Graphite Electrode',
                desc=[
                    '&6Goal:&r Craft a Graphite Electrode.',
                    '',
                    "Electrodes fuel the Arc Furnace multiblock — IE's high-throughput alloying endgame.",
                    '',
                    "&7Tip:&r Blueprint the electrode at the Engineer's Workbench, then build the Arc Furnace from the manual.",
                ],
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Immersive Engineering · Endgame',
            ),
        ],
    )

