"""14. Immersive Engineering quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='immersive_engineering',
        base=850,
        chapter_id='A20000000000000F',
        icon='immersiveengineering:hammer',
        title='14. Immersive Engineering',
        subtitle='Coke ovens, blast furnaces, wires, diesel, and arc furnaces',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='immersiveengineering:hammer',
                title="Engineer's Hammer",
                desc=tutorial(
                    "Craft an Engineer's Hammer.",
                    why="Multiblock formation, plate crafting, and most IE interactions start with this hammer — keep it hotbarred.",
                    steps=[
                        "Craft the &6Engineer's Hammer&r (iron + stick pattern — JEI).",
                        "Right-click metal ingots in-world or in crafting contexts to form plates when recipes call for hammering.",
                        "After building a brick multiblock, right-click the center face block to form it.",
                    ],
                    tip="Without the hammer, Coke Ovens and Blast Furnaces stay as pretty brick piles.",
                    nxt="Craft the Engineer's Manual for in-game diagrams.",
                ),
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Immersive Engineering · Tools',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='immersiveengineering:manual',
                title="Engineer's Manual",
                desc=tutorial(
                    "Craft the Engineer's Manual.",
                    why="In-game documentation for every multiblock, wire tier, and blueprint — worth a permanent offhand/Curios slot.",
                    steps=[
                        "Craft the &6Engineer's Manual&r and open it.",
                        "Find the Coke Oven / Blast Furnace pages and note the 3×3×3 brick layouts before you place blocks.",
                    ],
                    tip="Form structures exactly as the book shows; the hammer click confirms when they assemble.",
                    nxt="Make Treated Wood once you have creosote (or bootstrap from another coke source).",
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Tools',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='immersiveengineering:treated_wood_horizontal',
                title='Treated Wood',
                desc=tutorial(
                    "Craft &632 Treated Wood Planks&r.",
                    why="Creosote-treated wood is IE scaffolding for waterwheels, windmills, crafting stations, and many recipes.",
                    steps=[
                        "Obtain &6Creosote Oil&r from a Coke Oven (or another mod's coke byproduct).",
                        "Craft planks with creosote in the crafting grid / JEI recipe to make &6Treated Wood&r.",
                        "Stock a chest — sails, scaffolds, and engineering crafts burn through it.",
                    ],
                    tip="Pipe creosote into a wooden barrel or tank so the Coke Oven never voids fluid.",
                    nxt="Grow Industrial Hemp for fabric and insulation.",
                ),
                task_count=32,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Materials',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='immersiveengineering:hemp_fiber',
                title='Industrial Hemp',
                desc=tutorial(
                    "Collect &624 Industrial Hemp Fibers&r.",
                    why="Hemp makes tough fabric for windmill sails, wiring insulation, and engineering crafts.",
                    steps=[
                        "Find or craft &6Industrial Hemp Seeds&r and plant them on farmland.",
                        "Harvest mature hemp for fibers; craft fabric/rope as recipes need.",
                    ],
                    tip="Farm hemp like a crop — rope and fabric recipes burn stacks.",
                    nxt="Craft Coke Bricks for the Coke Oven multiblock.",
                ),
                task_count=24,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Materials',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='immersiveengineering:cokebrick',
                title='Coke Bricks',
                desc=tutorial(
                    "Craft &627 Coke Bricks&r.",
                    why="Exactly 27 Coke Bricks build the 3×3×3 Coke Oven — coal in, coal coke + creosote out.",
                    steps=[
                        "Craft &627 Coke Bricks&r (clay + sand + brick pattern — JEI).",
                        "Build a solid &63×3×3&r cube of Coke Bricks on flat ground.",
                        "Right-click the &6center block of any face&r with the &6Engineer's Hammer&r to form the Coke Oven.",
                        "Open the formed oven GUI — if it did not form, recheck the cube is complete and flush.",
                    ],
                    tip="Leave space beside one face for hoppers/pipes; the GUI face is where you hammered.",
                    nxt="Run coal through for Coal Coke and creosote.",
                ),
                task_count=27,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='immersiveengineering:coal_coke',
                title='Coal Coke',
                desc=tutorial(
                    "Produce &616 Coal Coke&r from a Coke Oven.",
                    why="Coke fuels the Blast Furnace. Creosote byproduct treats wood for more IE structures.",
                    steps=[
                        "Put &6Coal&r (or cokeable blocks) into the Coke Oven input.",
                        "Wait for the process; pull &6Coal Coke&r from the item output.",
                        "Pipe or bucket &6Creosote&r from the fluid output into a tank/barrel — do not let it void.",
                    ],
                    tip="Hopper coal in and coke out for a hands-free coke stack.",
                    nxt="Craft Blast Bricks for the Crude Blast Furnace.",
                ),
                task_count=16,
                deps=[4],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='immersiveengineering:blastbrick',
                title='Blast Bricks',
                desc=tutorial(
                    "Craft &627 Blast Bricks&r.",
                    why="Assemble a Crude Blast Furnace and hammer-form it to smelt iron + coke into steel.",
                    steps=[
                        "Craft &627 Blast Bricks&r.",
                        "Build a solid &63×3×3&r cube of Blast Bricks (same shape as the Coke Oven).",
                        "Engineer's Hammer the &6center of a face&r to form the Crude Blast Furnace.",
                        "Later: upgrade bricks to &6Reinforced Blast Bricks&r for the Improved Blast Furnace (faster, keeps fuel).",
                    ],
                    tip="Keep coke and iron chests next to the GUI face before you start steel runs.",
                    nxt="Smelt your first IE Steel batch.",
                ),
                task_count=27,
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Multiblocks',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='immersiveengineering:ingot_steel',
                title='IE Steel',
                desc=tutorial(
                    "Produce &616 Steel Ingots&r via Immersive Engineering.",
                    why="Steel feeds Heavy Engineering blocks, steel scaffolding, HV components, and many multiblocks.",
                    steps=[
                        "In the Blast Furnace GUI, add &6Iron Ingots&r and &6Coal Coke&r as fuel/input (JEI shows ratios).",
                        "Collect &6Steel Ingots&r and &6Slag&r from the outputs.",
                        "Hopper slag aside so it does not clog the item output.",
                    ],
                    tip="Improved Blast Furnace recycles coke better — upgrade when steel demand spikes.",
                    nxt="Craft Light Engineering Blocks from components.",
                ),
                task_count=16,
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Steel',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='immersiveengineering:light_engineering',
                title='Light Engineering',
                desc=tutorial(
                    "Craft &68 Light Engineering Blocks&r.",
                    why="Component blocks for mid-tier IE machines, workbenches, and many multiblock recipes.",
                    steps=[
                        "Craft &6Iron Components&r / related parts (plates, copper) as JEI shows.",
                        "Assemble &6Light Engineering Blocks&r in batches of 8+.",
                    ],
                    tip="Create presses help plate spam if you already have a brass factory.",
                    nxt="Heavy Engineering for crushers, diesel, and arc furnaces.",
                ),
                task_count=8,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Components',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='immersiveengineering:heavy_engineering',
                title='Heavy Engineering',
                desc=tutorial(
                    "Craft &64 Heavy Engineering Blocks&r.",
                    why="Steel-tier component blocks for crushers, diesel generators, excavators, and arc furnaces.",
                    steps=[
                        "Craft steel components / sheetmetal as required (JEI).",
                        "Assemble &6Heavy Engineering Blocks&r; store beside steel scaffolding.",
                    ],
                    tip="Keep steel sheetmetal and scaffolding in the same chest as these blocks.",
                    nxt="Engineer's Workbench for blueprints, then wiring.",
                ),
                task_count=4,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Components',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='immersiveengineering:workbench',
                title="Engineer's Workbench",
                desc=tutorial(
                    "Craft an Engineer's Workbench.",
                    why="Craft blueprints, schematics, and specialized IE recipes — electrodes and many tools start here.",
                    steps=[
                        "Craft and place the &6Engineer's Workbench&r.",
                        "Insert a &6Blueprint&r (engineer's craft) and the listed materials to make blueprint items.",
                        "Use it for Graphite Electrodes and other schematic crafts before Arc Furnace work.",
                    ],
                    tip="The Automated Workbench later runs blueprint recipes hands-free.",
                    nxt="LV Copper Coils to start the power grid.",
                ),
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Crafting',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='immersiveengineering:wirecoil_copper',
                title='LV Copper Coils',
                desc=tutorial(
                    "Craft &616 LV Wire Coils&r.",
                    why="Spool copper coils between LV connectors to move Immersive Flux (IFE) across your workshop.",
                    steps=[
                        "Craft &6Copper Wire&r then wind &6LV Wire Coils&r.",
                        "Hold a coil and right-click from one connector to another to string the wire.",
                        "Use &6Wire Cutters&r to remove bad links; add &6LV Relays&r to extend long runs.",
                    ],
                    tip="Do not mix LV coils onto MV/HV connectors — voltage tiers are separate.",
                    nxt="Craft LV Wire Connectors to attach to machines.",
                ),
                task_count=16,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='immersiveengineering:connector_lv',
                title='LV Connectors',
                desc=tutorial(
                    "Craft &68 LV Wire Connectors&r.",
                    why="Connectors attach to machines and capacitors — then you spool wire between them.",
                    steps=[
                        "Place &6LV Wire Connectors&r on machine faces or capacitor sides that should receive/send power.",
                        "String &6LV Wire Coils&r connector-to-connector.",
                        "Add an &6LV Transformer&r (or MV/HV equivalents) when stepping between voltage tiers.",
                    ],
                    caution="Wrong-tier wire on a connector fails or wastes the coil — match LV/MV/HV.",
                    tip="Capacitors in the middle of a run buffer brownouts from kinetic dynamos.",
                    nxt="Craft an LV Accumulator for storage.",
                ),
                task_count=8,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='immersiveengineering:capacitor_lv',
                title='LV Accumulator',
                desc=tutorial(
                    "Craft an LV Accumulator.",
                    why="Buffers IFE so waterwheels, windmills, and diesel generators do not brown out machines mid-craft.",
                    steps=[
                        "Place the &6LV Accumulator&r near your machine cluster.",
                        "Put connectors on the capacitor and on machines; spool LV wire between them.",
                        "Feed power from a Kinetic Dynamo / Diesel Generator into the capacitor first, then out to loads.",
                    ],
                    tip="Upgrade to MV/HV capacitors as you climb wire tiers and Arc Furnace power draw.",
                    nxt="Optional kinetic: Windmill — or Radiators toward diesel.",
                ),
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='immersiveengineering:windmill',
                title='Windmill',
                desc=tutorial(
                    "Craft a Windmill.",
                    why="Kinetic power from wind — attach sails and convert through a Kinetic Dynamo into IFE.",
                    steps=[
                        "Place the &6Windmill&r high with clear air around the blades.",
                        "Craft &6Windmill Sails&r (hemp fabric) and right-click them onto the windmill hub.",
                        "Connect a &6Wooden Axle&r from the windmill into a &6Kinetic Dynamo&r.",
                        "Wire the dynamo with LV connectors/coils into your accumulator.",
                    ],
                    tip="More sails and higher placement improve capture; waterwheels are steadier if you have flowing water.",
                    nxt="Radiator Blocks for Diesel Generator multiblocks.",
                ),
                deps=[3],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Kinetic',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='immersiveengineering:radiator',
                title='Radiator Block',
                desc=tutorial(
                    "Craft &64 Radiator Blocks&r.",
                    why="Radiators appear in the Diesel Generator multiblock and other heat-heavy IE structures.",
                    steps=[
                        "Craft &6Radiator Blocks&r from plate/copper recipes (JEI).",
                        "Open the Engineer's Manual Diesel Generator page and place Heavy Engineering, Radiators, and generators per the diagram.",
                        "Hammer-form the multiblock on the indicated block face.",
                        "Pipe &6Biodiesel&r (or diesel) into the fuel hatch; wire IFE out with MV-capable connectors.",
                    ],
                    tip="Refine biodiesel from ethanol + plant oil in IE fermenters/refineries before relying on diesel power.",
                    nxt="Conveyors for machine I/O, then Graphite Electrodes for the Arc Furnace.",
                ),
                task_count=4,
                deps=[9],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Immersive Engineering · Power',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='immersiveengineering:conveyor_basic',
                title='IE Conveyors',
                desc=tutorial(
                    "Craft &616 Basic Conveyors&r.",
                    why="Move items into crushers, furnaces, and assemblers without Create belts if you prefer IE logistics.",
                    steps=[
                        "Place conveyors in a line into machine input faces; sneak-place to change direction.",
                        "Use covered/vertical variants to climb into crusher or Arc Furnace inputs.",
                        "Drop items from hoppers onto belts, or pull from chests with conveyor variants that extract.",
                    ],
                    tip="Covered conveyors keep players and stray items from kicking stacks off the line.",
                    nxt="Blueprint a Graphite Electrode for the Arc Furnace.",
                ),
                task_count=16,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Immersive Engineering · Processing',
            ),
            Quest(
                n=17,
                x=20.0,
                y=2.5,
                task='immersiveengineering:graphite_electrode',
                title='Graphite Electrode',
                desc=tutorial(
                    "Craft a Graphite Electrode.",
                    why="Electrodes fuel the Arc Furnace multiblock — IE's high-throughput alloying and smelting endgame.",
                    steps=[
                        "At the Engineer's Workbench, use the electrode &6Blueprint&r with the listed materials to craft &6Graphite Electrodes&r.",
                        "Build the &6Arc Furnace&r from the Manual (refractory bricks, Heavy Engineering, electrodes on top).",
                        "Hammer-form the structure; insert electrodes into the electrode slots.",
                        "Feed IFE (HV recommended), ores/ingots on conveyors, and pull slag/metals from the outputs.",
                    ],
                    caution="Electrodes wear out — keep spares crafted or the furnace stops mid-run.",
                    tip="Pair with a Crusher multiblock upstream for dust → Arc Furnace alloy lines.",
                    nxt="Chapter complete — excavator and metal press await in the Manual when you need bulk ore.",
                ),
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Immersive Engineering · Endgame',
            ),
        ],
    )
