"""13. Industrial Foregoing quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON


def chapter() -> Chapter:
    return Chapter(
        key='industrial_foregoing',
        base=800,
        chapter_id='A20000000000000E',
        icon='industrialforegoing:machine_frame_pity',
        title='13. Industrial Foregoing',
        subtitle='Latex, plastic, farms, mob slaughter, lasers, and infinity tools',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='industrialforegoing:machine_frame_pity',
                title='Pity Machine Frame',
                desc=[
                    '&6Goal:&r Craft &64 Pity Machine Frames&r.',
                    '',
                    'Industrial Foregoing starts with Pity frames — wooden-tier chassis for extractors and early machines.',
                    '',
                    "&7Tip:&r You'll rebuild these into Simple/Advanced/Supreme frames as you climb.",
                ],
                task_count=4,
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='industrialforegoing:fluid_extractor',
                title='Fluid Extractor',
                desc=[
                    '&6Goal:&r Craft &62 Fluid Extractors&r.',
                    '',
                    'Extract latex from logs. Place against wood and pipe latex into a processing unit.',
                    '',
                    '&7Tip:&r Oak and other logs work; keep a tree farm glued to the extractors.',
                ],
                task_count=2,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='industrialforegoing:latex_processing_unit',
                title='Latex Processing',
                desc=[
                    '&6Goal:&r Craft a Latex Processing Unit.',
                    '',
                    "Turn latex into tiny dry rubber, then dry rubber, then plastic — IF's core material chain.",
                    '',
                    '&7Tip:&r Water and power keep the unit running; buffer latex in a tank.',
                ],
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='industrialforegoing:plastic',
                title='Plastic',
                desc=[
                    '&6Goal:&r Craft &616 Plastic&r.',
                    '',
                    'Plastic appears in nearly every IF machine upgrade. Overproduce early.',
                    '',
                    '&7Tip:&r Pink slime later supplements high-tier crafts — plastic never stops being useful.',
                ],
                task_count=16,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='industrialforegoing:machine_frame_simple',
                title='Simple Machine Frame',
                desc=[
                    '&6Goal:&r Craft &62 Simple Machine Frames&r.',
                    '',
                    'Simple frames unlock the main farming and mob machines.',
                    '',
                    '&7Tip:&r Iron, plastic, and pity frames typically combine here — check JEI.',
                ],
                task_count=2,
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='industrialforegoing:pitiful_generator',
                title='Pitiful Generator',
                desc=[
                    '&6Goal:&r Craft a Pitiful Generator.',
                    '',
                    'A humble solid-fuel FE generator to bootstrap IF machines before biofuel.',
                    '',
                    '&7Tip:&r Replace it with Biofuel or Protein generators once farms run.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Power',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='industrialforegoing:plant_sower',
                title='Plant Sower',
                desc=[
                    '&6Goal:&r Craft a Plant Sower.',
                    '',
                    'Auto-plants seeds in a working area — the start of IF crop automation.',
                    '',
                    '&7Tip:&r Pair with a Plant Gatherer and Fertilizer for a full farm loop.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='industrialforegoing:plant_gatherer',
                title='Plant Gatherer',
                desc=[
                    '&6Goal:&r Craft a Plant Gatherer.',
                    '',
                    'Harvests grown crops into its inventory or pipes. Essential beside the sower.',
                    '',
                    '&7Tip:&r Range addons expand coverage; speed addons keep up with bone-meal spam.',
                ],
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='industrialforegoing:hydroponic_bed',
                title='Hydroponic Bed',
                desc=[
                    '&6Goal:&r Craft &62 Hydroponic Beds&r.',
                    '',
                    'Compact soil substitutes for dense indoor farms.',
                    '',
                    "&7Tip:&r Great under sowers when you don't want to manage vanilla farmland water.",
                ],
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='industrialforegoing:mob_slaughter_factory',
                title='Mob Slaughter',
                desc=[
                    '&6Goal:&r Craft a Mob Slaughter Factory.',
                    '',
                    'Grinds mobs into meat and pink slime fluid — brutal but efficient.',
                    '',
                    '&7Tip:&r Feed it a contained spawner area; collect pink slime for frames and infinity tools.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Mobs',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='industrialforegoing:dissolution_chamber',
                title='Dissolution Chamber',
                desc=[
                    '&6Goal:&r Craft a Dissolution Chamber.',
                    '',
                    'Mix items and fluids into advanced IF components, including pink slime processing.',
                    '',
                    '&7Tip:&r Many mid/late crafts are dissolution recipes — keep one piped and powered.',
                ],
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Processing',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='industrialforegoing:pink_slime',
                title='Pink Slime',
                desc=[
                    '&6Goal:&r Collect &68 Pink Slimeballs&r.',
                    '',
                    'Pink slime is the prestige goo for Advanced/Supreme frames and infinity tools.',
                    '',
                    "&7Tip:&r Mob slaughter is the usual farm; don't discard slime fluid.",
                ],
                task_count=8,
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Mobs',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='industrialforegoing:machine_frame_advanced',
                title='Advanced Frame',
                desc=[
                    '&6Goal:&r Craft an Advanced Machine Frame.',
                    '',
                    'Advanced frames unlock stronger generators, lasers, and late machines.',
                    '',
                    '&7Tip:&r Plastic + pink slime + gold-tier materials are common ingredients.',
                ],
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='industrialforegoing:ore_laser_base',
                title='Ore Laser Base',
                desc=[
                    '&6Goal:&r Craft an Ore Laser Base.',
                    '',
                    'Laser drills mine specific ores from a vertical beam when paired with a lens and drill.',
                    '',
                    '&7Tip:&r Power hungry but excellent for rare resources once tuned.',
                ],
                deps=[12],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Industrial Foregoing · Lasers',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='industrialforegoing:laser_drill',
                title='Laser Drill',
                desc=[
                    '&6Goal:&r Craft a Laser Drill.',
                    '',
                    'Mount above/below the ore laser base with the correct lens for your target ore.',
                    '',
                    '&7Tip:&r Biome and dimension affect tables — check JEI for lens weights.',
                ],
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Lasers',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='industrialforegoing:machine_frame_supreme',
                title='Supreme Frame',
                desc=[
                    '&6Goal:&r Craft a Supreme Machine Frame.',
                    '',
                    'Top chassis tier for the strongest IF machines and infinity tool crafting.',
                    '',
                    '&7Tip:&r By now latex, plastic, and pink slime lines should be fully automatic.',
                ],
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Endgame',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='industrialforegoing:infinity_drill',
                title='Infinity Drill',
                desc=[
                    '&6Goal:&r Craft an Infinity Drill.',
                    '',
                    "A chargeable, upgradeable drill that grows with additives — IF's signature mining tool.",
                    '',
                    '&7Tip:&r Feed it power and materials; tank size and speed upgrades change everything.',
                ],
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Industrial Foregoing · Endgame',
            ),
        ],
    )

