"""13. Industrial Foregoing quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='industrial_foregoing',
        base=800,
        chapter_id='020000000000000E',
        icon='industrialforegoing:machine_frame_pity',
        title='13. Industrial Foregoing',
        subtitle='Latex, plastic, farms, mob slaughter, lasers, and infinity tools',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='industrialforegoing:machine_frame_pity',
                title='Pity Machine Frame',
                desc=tutorial(
                    "Craft &64 Pity Machine Frames&r.",
                    why="Industrial Foregoing starts with Pity frames — wooden-tier chassis for extractors and early machines.",
                    steps=[
                        "Craft &6Pity Machine Frames&r from wood, iron, and redstone parts (JEI).",
                        "Keep extras — Fluid Extractors and the Latex Processing Unit each want frames.",
                    ],
                    tip="You will rebuild these into Simple/Advanced/Supreme frames as you climb.",
                    nxt="Fluid Extractors against a tree line.",
                ),
                task_count=4,
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='industrialforegoing:fluid_extractor',
                title='Fluid Extractor',
                desc=tutorial(
                    "Craft &62 Fluid Extractors&r.",
                    why="Extractors pull &6Latex&r from logs — the start of dry rubber and plastic.",
                    steps=[
                        "Place each &6Fluid Extractor&r facing into a log (oak and most logs work).",
                        "Power the extractors (Pitiful Generator later, or any FE cable).",
                        "Pipe latex out of the fluid side into a tank or straight into the Latex Processing Unit.",
                        "Keep a tree farm or Plant Gatherer replacing logs as they get stripped/consumed.",
                    ],
                    tip="Multiple extractors on one trunk speed latex if the wood type allows.",
                    nxt="Latex Processing Unit to make dry rubber.",
                ),
                task_count=2,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='industrialforegoing:latex_processing_unit',
                title='Latex Processing',
                desc=tutorial(
                    "Craft a Latex Processing Unit.",
                    why="Turns latex into tiny dry rubber → dry rubber → plastic — IF's core material chain.",
                    steps=[
                        "Place the unit; connect FE and pipe in &6Latex&r + &6Water&r.",
                        "Pull &6Tiny Dry Rubber&r / &6Dry Rubber&r from the item output into a chest.",
                        "Buffer latex in a fluid tank so extractors never back up into a full machine.",
                    ],
                    tip="Water and power keep the unit running — a sink or Create hose is enough water.",
                    nxt="Craft Plastic from dry rubber.",
                ),
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='industrialforegoing:plastic',
                title='Plastic',
                desc=tutorial(
                    "Craft &616 Plastic&r.",
                    why="Plastic appears in nearly every IF machine and upgrade. Overproduce early.",
                    steps=[
                        "Compress or craft &6Dry Rubber&r from tiny dry rubber (JEI).",
                        "Smelt/craft dry rubber into &6Plastic&r.",
                        "Stockpile at least a stack before building Simple-tier machines.",
                    ],
                    tip="Pink slime later supplements high-tier crafts — plastic never stops being useful.",
                    nxt="Upgrade to Simple Machine Frames.",
                ),
                task_count=16,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Latex',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='industrialforegoing:machine_frame_simple',
                title='Simple Machine Frame',
                desc=tutorial(
                    "Craft &62 Simple Machine Frames&r.",
                    why="Simple frames unlock the main farming, generator, and mob machines.",
                    steps=[
                        "Craft Simple frames from &6Pity Frames&r + &6Plastic&r + iron-tier materials (JEI).",
                        "Save them for Plant Sower/Gatherer, Pitiful Generator, and Mob Slaughter.",
                    ],
                    tip="Iron, plastic, and pity frames typically combine here — check JEI.",
                    nxt="Pitiful Generator to bootstrap FE.",
                ),
                task_count=2,
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='industrialforegoing:pitiful_generator',
                title='Pitiful Generator',
                desc=tutorial(
                    "Craft a Pitiful Generator.",
                    why="A humble solid-fuel FE generator to bootstrap IF machines before biofuel or pink-slime power.",
                    steps=[
                        "Place the generator near your latex/farm machines.",
                        "Insert solid fuel; pull FE out with energy cables/conduits into machine sides.",
                        "Replace later with Biofuel or Protein generators once farms and mob lines run.",
                    ],
                    tip="One generator can feed several early machines if you buffer with an energy cell.",
                    nxt="Plant Sower for crop automation.",
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Power',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='industrialforegoing:plant_sower',
                title='Plant Sower',
                desc=tutorial(
                    "Craft a Plant Sower.",
                    why="Auto-plants seeds in a working area — the start of IF crop automation.",
                    steps=[
                        "Place the &6Plant Sower&r facing a farmland / Hydroponic Bed grid.",
                        "Power it; put seeds in the input slots.",
                        "Open the GUI and set the work area (or insert &6Range Addons&r).",
                        "Pair with a Plant Gatherer covering the same plots.",
                    ],
                    tip="Fertilizer addon / fertilizer fluid speeds growth when you are ready.",
                    nxt="Plant Gatherer to harvest the field.",
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='industrialforegoing:plant_gatherer',
                title='Plant Gatherer',
                desc=tutorial(
                    "Craft a Plant Gatherer.",
                    why="Harvests grown crops into its inventory or pipes — essential beside the sower.",
                    steps=[
                        "Place the Gatherer so its area overlaps the sower's crops.",
                        "Power it; insert &6Range&r and &6Speed Addons&r as needed.",
                        "Pipe crops out to storage; return seeds to the Sower.",
                    ],
                    tip="Speed addons keep up with bone-meal or fertilizer spam.",
                    nxt="Hydroponic Beds for compact indoor farms.",
                ),
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='industrialforegoing:hydroponic_bed',
                title='Hydroponic Bed',
                desc=tutorial(
                    "Craft &62 Hydroponic Beds&r.",
                    why="Compact soil substitutes for dense indoor farms without vanilla farmland water tricks.",
                    steps=[
                        "Craft and place &6Hydroponic Beds&r in a grid under your sower/gatherer.",
                        "Plant via the Plant Sower as if they were farmland.",
                        "Pipe water/fertilizer into beds if the recipe/GUI requires fluid for max speed.",
                    ],
                    tip="Great under sowers when you do not want to manage vanilla farmland water.",
                    nxt="Mob Slaughter Factory on a separate branch.",
                ),
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Farming',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='industrialforegoing:mob_slaughter_factory',
                title='Mob Slaughter',
                desc=tutorial(
                    "Craft a Mob Slaughter Factory.",
                    why="Grinds mobs into meat and &6Pink Slime&r fluid — brutal but efficient for frames and infinity tools.",
                    steps=[
                        "Build a contained mob spawn area (dark room, spawner, or cursed earth style).",
                        "Place the &6Mob Slaughter Factory&r so mobs walk into its working range; power it.",
                        "Pipe &6Meat&r and &6Pink Slime&r fluids into tanks; pull item drops if enabled.",
                        "Insert range/speed addons so the kill box covers the whole pad.",
                    ],
                    caution="Open kill boxes near your base are messy — wall them in and vacuum items.",
                    tip="Pink slime fluid is the prize — do not void it.",
                    nxt="Dissolution Chamber for pink slime crafting.",
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Mobs',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='industrialforegoing:dissolution_chamber',
                title='Dissolution Chamber',
                desc=tutorial(
                    "Craft a Dissolution Chamber.",
                    why="Mixes items and fluids into advanced IF components, including pink slimeballs and many mid/late crafts.",
                    steps=[
                        "Place and power the chamber; pipe in required fluids (pink slime, latex, etc. per JEI).",
                        "Insert catalog items into the item slots for the recipe.",
                        "Pull crafted outputs automatically — keep one chamber piped as a permanent station.",
                    ],
                    tip="Many mid/late crafts are dissolution recipes — treat it like a second crafting table with tanks.",
                    nxt="Collect Pink Slimeballs.",
                ),
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Processing',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='industrialforegoing:pink_slime',
                title='Pink Slime',
                desc=tutorial(
                    "Collect &68 Pink Slimeballs&r.",
                    why="Pink slime is the prestige goo for Advanced/Supreme frames and infinity tools.",
                    steps=[
                        "Pipe pink slime fluid from the Mob Slaughter Factory into the Dissolution Chamber.",
                        "Run the slimeball recipes; stockpile at least 8.",
                    ],
                    tip="Mob slaughter is the usual farm — never discard slime fluid.",
                    nxt="Advanced Machine Frame.",
                ),
                task_count=8,
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Industrial Foregoing · Mobs',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='industrialforegoing:machine_frame_advanced',
                title='Advanced Frame',
                desc=tutorial(
                    "Craft an Advanced Machine Frame.",
                    why="Advanced frames unlock stronger generators, ore lasers, and late machines.",
                    steps=[
                        "Craft from &6Simple Frames&r + &6Plastic&r + &6Pink Slime&r + gold-tier materials (JEI).",
                        "Reserve the first frame for the Ore Laser Base.",
                    ],
                    tip="Automate plastic and pink slime before you need a second Advanced frame.",
                    nxt="Ore Laser Base.",
                ),
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Frames',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='industrialforegoing:ore_laser_base',
                title='Ore Laser Base',
                desc=tutorial(
                    "Craft an Ore Laser Base.",
                    why="Laser drills mine specific ores from a vertical beam when paired with a lens and drill — excellent for rare resources.",
                    steps=[
                        "Place the &6Ore Laser Base&r with clear vertical space for the beam.",
                        "Power it heavily; insert the correct &6Laser Lens&r for your target ore (JEI weights).",
                        "Mount a &6Laser Drill&r above/below as the structure requires.",
                        "Pipe ores out; biome and dimension affect drop tables — check JEI.",
                    ],
                    tip="Power hungry but steady once tuned — buffer FE beside the base.",
                    nxt="Craft the Laser Drill itself.",
                ),
                deps=[12],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Industrial Foregoing · Lasers',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='industrialforegoing:laser_drill',
                title='Laser Drill',
                desc=tutorial(
                    "Craft a Laser Drill.",
                    why="Works with the Ore Laser Base and lens to actually mine the ore table.",
                    steps=[
                        "Craft the &6Laser Drill&r and place it on the laser base stack per JEI/guidebook.",
                        "Confirm the lens in the base matches the ore you want.",
                        "Pull outputs into storage; swap lenses when changing targets.",
                    ],
                    tip="Biome and dimension affect tables — check JEI for lens weights before building a second drill.",
                    nxt="Supreme Machine Frame for endgame tools.",
                ),
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Lasers',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='industrialforegoing:machine_frame_supreme',
                title='Supreme Frame',
                desc=tutorial(
                    "Craft a Supreme Machine Frame.",
                    why="Top chassis tier for the strongest IF machines and infinity tool crafting.",
                    steps=[
                        "Craft from Advanced frames + pink slime + late materials (JEI).",
                        "By now latex, plastic, and pink slime lines should be fully automatic.",
                    ],
                    tip="Make two if you plan multiple infinity tools.",
                    nxt="Infinity Drill.",
                ),
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Industrial Foregoing · Endgame',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='industrialforegoing:infinity_drill',
                title='Infinity Drill',
                desc=tutorial(
                    "Craft an Infinity Drill.",
                    why="A chargeable, upgradeable drill that grows with additives — IF's signature mining tool.",
                    steps=[
                        "Craft the &6Infinity Drill&r at the Dissolution Chamber / crafting path JEI shows (Supreme frame tier).",
                        "Charge it with FE; open the GUI to add tank size, speed, and special additives.",
                        "Mine in area modes once upgraded — keep a power station nearby for top-ups.",
                    ],
                    tip="Feed it power and materials; tank size and speed upgrades change everything.",
                    nxt="Chapter complete — ether gas and more infinity tools await in JEI when you are ready.",
                ),
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Industrial Foregoing · Endgame',
            ),
        ],
    )
