"""15. Beyond Brass quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import C_PRECISION, C_TRACK
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='late_game',
        base=500,
        chapter_id='A200000000000005',
        icon='minecraft:netherite_ingot',
        title='15. Beyond Brass',
        subtitle='Netherite, flight, railways, bosses, and the sky',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='minecraft:netherite_ingot',
                title='Netherite',
                desc=tutorial(
                    'Smith a netherite ingot.',
                    why='Ancient debris + gold — the late-game material gate for this book.',
                    steps=[
                        'Mine ancient debris in the Nether (bed mining or strip mining Y~8–22).',
                        'Smelt debris into netherite scrap, then smith scrap + gold into an ingot.',
                        'Bring fire resistance and a Waystone before long Nether runs.',
                    ],
                    tip='One ingot unlocks the endgame checklist — furnaces, flight, flex crafts.',
                    nxt='Flight, trains, cannons, and finale bosses branch from here.',
                ),
                links=require(C_PRECISION),
                rewards=[item('minecraft:ancient_debris', 4), xp_levels(3)],
                size=2.0,
                shape='gear',
                subtitle='Endgame gate',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='ironfurnaces:netherite_furnace',
                title='Netherite Furnace',
                desc=tutorial(
                    'Craft a Netherite Furnace.',
                    why='Top-tier smelting speed for when your ore drill finally wakes up.',
                    steps=[
                        'Upgrade through Iron Furnaces tiers or craft the Netherite Furnace per JEI.',
                        'Place it on your smelting line and feed ore + fuel (or FE if upgraded that way).',
                        'Pipe outputs into RS or drawers so the furnace never backs up.',
                    ],
                    tip='Pair with hopper/pipe automation — speed is wasted if outputs clog.',
                    nxt='Optional chests, or push flight thrusters.',
                ),
                deps=[0],
                rewards=[item('minecraft:netherite_ingot'), xp_levels(2)],
                subtitle='Smelting',
            ),
            Quest(
                n=2,
                x=2.5,
                y=2.5,
                task='ironchest:obsidian_chest',
                title='Obsidian Chest',
                desc=tutorial(
                    'Craft an Obsidian Chest.',
                    why='Blast-resistant storage for bases that experiment with Big Cannons.',
                    steps=[
                        'Craft the Obsidian Chest (upgrade path via Iron Chests).',
                        'Place it for valuables near risky test ranges.',
                        'Keep a Waystone nearby — “experiment” is doing a lot of work here.',
                    ],
                    tip='Optional flex storage — skip if RS already holds everything.',
                    nxt='Diamond Chest is the other optional chest branch.',
                ),
                deps=[1],
                rewards=[item('minecraft:obsidian', 32)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=3,
                x=2.5,
                y=-2.5,
                task='ironchest:diamond_chest',
                title='Diamond Chest',
                desc=tutorial(
                    'Craft a Diamond Chest.',
                    why='Huge mixed storage before full digital networks take over.',
                    steps=[
                        'Upgrade an Iron/Gold chest path to Diamond per JEI.',
                        'Use it as a local dump chest beside a Create line.',
                        'Importer into RS when you are ready to digitize the pile.',
                    ],
                    tip='Optional — drawers + RS usually outscale mixed chests.',
                    nxt='Back to flight or trains from Netherite.',
                ),
                deps=[1],
                rewards=[item('minecraft:diamond', 8)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=4,
                x=5,
                y=0,
                task='ironjetpacks:thruster',
                title='Jetpack Thrusters',
                desc=tutorial(
                    'Craft &62 Iron Jetpacks thrusters&r.',
                    why='Thrusters combine with coils, capacitors, cells, and a strap into modular jetpacks.',
                    steps=[
                        'Craft two thrusters for your chosen jetpack tier.',
                        'Gather matching coils/capacitors while you craft.',
                        'Plan FE charging: Powah Player Transmitter, alternator, or diesel.',
                    ],
                    tip='Charge with FE from your alternator / diesel / Powah setup.',
                    nxt='Craft the jetpack energy cell.',
                ),
                task_count=2,
                deps=[0],
                rewards=[item('ironjetpacks:basic_coil', 2), xp_levels(1)],
                subtitle='Flight',
            ),
            Quest(
                n=5,
                x=7.5,
                y=0,
                task='ironjetpacks:cell',
                title='Jetpack Cell',
                desc=tutorial(
                    'Craft an Iron Jetpacks energy cell.',
                    why="Energy storage for your jetpack assembly — don't skip the battery.",
                    steps=[
                        'Craft the energy cell for your jetpack tier.',
                        'Keep the matching capacitor ready for final assembly.',
                        'Higher cells = longer flights before you need a charger.',
                    ],
                    tip='Upgrade the cell when you upgrade thrusters — mismatched tiers feel weak.',
                    nxt='Assemble the Iron Jetpack.',
                ),
                deps=[4],
                rewards=[item('ironjetpacks:capacitor')],
                subtitle='Flight',
            ),
            Quest(
                n=6,
                x=10,
                y=0,
                task='ironjetpacks:jetpack',
                title='Iron Jetpack',
                desc=tutorial(
                    'Assemble an Iron Jetpacks jetpack.',
                    why='Charge it and take to the skies — independent from Create backtanks.',
                    steps=[
                        'Combine thrusters, cell, capacitor, coils, and strap per JEI.',
                        'Equip the jetpack and charge it fully before a long flight.',
                        'Bind hover/engine keys and test over water, not lava.',
                    ],
                    tip='Powah Player Transmitters keep jetpacks topped up while you build.',
                    nxt='Create Jetpack if you prefer pressure over FE.',
                ),
                deps=[5],
                rewards=[xp_levels(3)],
                size=1.5,
                shape='hexagon',
                subtitle='Flight',
            ),
            Quest(
                n=7,
                x=5,
                y=-2.5,
                task='create_jetpack:jetpack',
                title='Create Jetpack',
                desc=tutorial(
                    'Craft the Create Jetpack.',
                    why='Runs off copper backtank pressure — perfect if your factory already fills tanks.',
                    steps=[
                        'Craft the Create Jetpack and a Copper Backtank.',
                        'Fill the backtank at an Encased Fan + water/lava setup or tank filler.',
                        'Equip both and verify thrust before long climbs.',
                    ],
                    tip='Factory air compressors beat hand-pumping before every trip.',
                    nxt='Optional Brass Jetpack, or stockpile mechanisms.',
                ),
                deps=[6],
                rewards=[item('create:copper_backtank'), xp_levels(2)],
                size=1.5,
                subtitle='Flight',
            ),
            Quest(
                n=8,
                x=7.5,
                y=-2.5,
                task='create_sa:brass_jetpack_chestplate',
                title='Brass Jetpack',
                desc=tutorial(
                    "Craft Stuff 'N Additions brass jetpack chestplate.",
                    why='Another flight option for brass-rich factories — pick your favorite sky kit.',
                    steps=[
                        'Craft the brass jetpack chestplate per JEI.',
                        'Charge/fuel it according to its tooltip requirements.',
                        'Keep one flight system as daily driver; stash the rest.',
                    ],
                    tip='Optional — you only need one reliable way to fly.',
                    nxt='Mechanism stockpile or trains.',
                ),
                deps=[7],
                rewards=[item('create:brass_ingot', 16), xp_levels(2)],
                optional=True,
                subtitle='Flight',
                hide_until_deps=True,
            ),
            Quest(
                n=9,
                x=5,
                y=2.5,
                task='createbigcannons:cannon_mount',
                title='Cannon Mount',
                desc=tutorial(
                    'Craft a Create Big Cannons mount.',
                    why='Base of a buildable cannon — build responsibly (or don’t).',
                    steps=[
                        'Craft the Cannon Mount and place it on a solid test pad far from the factory.',
                        'Use foundries and cast moulds for proper barrels — JEI lists the chain.',
                        'Add controls/seats before loading live shot.',
                    ],
                    tip='Test ranges strongly recommended. Bases are rebuildable; friends are not.',
                    nxt='Craft solid shot ammunition.',
                ),
                deps=[14],
                rewards=[item('minecraft:iron_block', 4), xp_levels(1)],
                optional=True,
                subtitle='Chaos',
                hide_until_deps=True,
            ),
            Quest(
                n=10,
                x=7.5,
                y=2.5,
                task='createbigcannons:solid_shot',
                title='Solid Shot',
                desc=tutorial(
                    'Craft solid shot ammunition.',
                    why='Optional gunnery goal — proves the barrel works.',
                    steps=[
                        'Craft solid shot per JEI.',
                        'Load the cannon on a clear test range with a backstop.',
                        'Fire once, then decide if the factory roof needed that hole.',
                    ],
                    tip='Optional chaos quest — skip without shame.',
                    nxt='Back to serious endgame: bosses and elytra.',
                ),
                deps=[9],
                rewards=[item('minecraft:gunpowder', 16)],
                optional=True,
                subtitle='Chaos',
                hide_until_deps=True,
            ),
            Quest(
                n=11,
                x=10,
                y=2.5,
                task='create:track',
                title='Rail Empire',
                desc=tutorial(
                    'Craft &664 Create tracks&r.',
                    why='Link factories across the map — trains move bulk ore, fuel, and players.',
                    steps=[
                        'Automate track crafting (mechanical crafters love this).',
                        'Place a line between two stations with proper slopes and signals.',
                        'Schedule a train for ore/fuel before decorating.',
                    ],
                    tip='Trains beat shulker relays for bulk Create logistics.',
                    nxt='Steam ’n’ Rails conductor whistle for railway QoL.',
                ),
                task_count=64,
                deps=[0],
                links=require(C_TRACK),
                rewards=[item('create:precision_mechanism', 2), xp_levels(2)],
                subtitle='Trains',
            ),
            Quest(
                n=12,
                x=12.5,
                y=2.5,
                task='railways:conductor_whistle',
                title='Conductor Whistle',
                desc=tutorial(
                    "Craft a Steam 'n' Rails conductor whistle.",
                    why='Conductors, fancy tracks, and train QoL — run the railway like you mean it.',
                    steps=[
                        'Craft the conductor whistle.',
                        'Recruit/place conductors and bind them to your routes as the mod requires.',
                        'Add fuel tanks and proper schedules so trains return home.',
                    ],
                    tip='A fueled, scheduled train beats a decorative locomotive.',
                    nxt='Optional Bells & Whistles headlight flair.',
                ),
                deps=[11],
                rewards=[item('railways:fuel_tank'), xp_levels(2)],
                subtitle='Trains',
            ),
            Quest(
                n=13,
                x=15,
                y=2.5,
                task='bellsandwhistles:headlight',
                title='Train Headlight',
                desc=tutorial(
                    'Craft a Bells & Whistles headlight.',
                    why='Dress up locomotives — pilots, grab rails, metro casing, and station flair.',
                    steps=[
                        'Craft the headlight and mount it on a locomotive.',
                        'Add metro casing and other cosmetics if you want a full livery.',
                        'Night runs look better with lights — function first, paint second.',
                    ],
                    tip='Optional cosmetics — skip if you are mid-Wither prep.',
                    nxt='Mechanism stockpile toward bosses.',
                ),
                deps=[12],
                rewards=[item('bellsandwhistles:metro_casing', 8)],
                optional=True,
                subtitle='Trains',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=12.5,
                y=0,
                task='create:precision_mechanism',
                title='Mechanism Stockpile',
                desc=tutorial(
                    'Stockpile &632 precision mechanisms&r.',
                    why="If this hurts, your assembly line isn't automated enough yet.",
                    steps=[
                        'Set mechanical crafters + deployers + arms to feed a chest nonstop.',
                        'Pull mechanisms into RS or a drawer wall.',
                        'Do not hand-craft thirty-two — fix the line instead.',
                    ],
                    tip='This quest is a factory exam disguised as a number.',
                    nxt='Fight the Wither for a nether star.',
                ),
                task_count=32,
                deps=[6],
                links=require(C_PRECISION),
                rewards=[item('create:brass_sheet', 32), xp_levels(3)],
                size=1.5,
                subtitle='Logistics flex',
            ),
            Quest(
                n=15,
                x=15,
                y=0,
                task='minecraft:nether_star',
                title='Wither Down',
                desc=tutorial(
                    'Defeat the Wither and hold a nether star.',
                    why='Beacon bases make Create factories feel unfair — haste + speed while building is cracked.',
                    steps=[
                        'Prep a Wither arena (bedrock box, underground, or open desert — your call).',
                        'Bring netherite gear, potions, and a Waystone escape.',
                        'Kill the Wither, collect the nether star, and keep it for a beacon.',
                    ],
                    tip='Cheese is allowed. Pride is optional.',
                    nxt='Dragon egg / elytra / beacon — endgame checklist.',
                ),
                deps=[14],
                rewards=[item('minecraft:diamond_block', 2), xp_levels(5)],
                size=1.75,
                shape='pentagon',
                subtitle='Boss',
            ),
            Quest(
                n=16,
                x=17.5,
                y=0,
                task='minecraft:dragon_egg',
                title='Dragon Egg',
                desc=tutorial(
                    'Claim the dragon egg after beating the Ender Dragon.',
                    why='Trophy of the End — keep it safe or display it above the factory.',
                    steps=[
                        'Reach the End, destroy crystals, defeat the dragon.',
                        'Click the egg carefully (piston/torch trick if it teleports).',
                        'Store or display the egg somewhere you will not explode later.',
                    ],
                    tip='Optional trophy — elytra is the practical End reward.',
                    nxt='Grab elytra from End ships.',
                ),
                deps=[15],
                rewards=[item('minecraft:end_crystal', 4), xp_levels(3)],
                optional=True,
                size=1.5,
                subtitle='Boss',
                hide_until_deps=True,
            ),
            Quest(
                n=17,
                x=20,
                y=0,
                task='minecraft:elytra',
                title='Elytra',
                desc=tutorial(
                    'Claim elytra from the End.',
                    why="Combine with a jetpack or fireworks — you're done with walking.",
                    steps=[
                        'Find an End ship (outer islands) and take the elytra from the item frame.',
                        'Craft firework rockets for boosting; mend elytra with XP/mending.',
                        'Optional: shulker shells for portable storage on the same trip.',
                    ],
                    tip="You've reached the end of the guided quest book — keep building absurd factories.",
                    nxt='Optional beacon base, then free play.',
                ),
                deps=[15],
                rewards=[item('minecraft:firework_rocket', 64), item('minecraft:shulker_shell', 4), xp_levels(5)],
                size=2.0,
                shape='gear',
                subtitle='Finale',
            ),
            Quest(
                n=18,
                x=12.5,
                y=-2.5,
                task='constructionstick:netherite_stick',
                title='Netherite Construction Stick',
                desc=tutorial(
                    'Craft the netherite construction stick.',
                    why='Maximum reach building for megabases and rail yards.',
                    steps=[
                        'Upgrade Construction Stick tiers to netherite per JEI.',
                        'Configure placement mode (wall/floor/fill) before big builds.',
                        'Bring shulker boxes of building blocks to the site.',
                    ],
                    tip='Optional QoL — worth it before paving a rail empire.',
                    nxt='Keep building.',
                ),
                deps=[1],
                rewards=[xp_levels(2)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=19,
                x=15,
                y=-2.5,
                task='tombstone:grave_dust',
                title='Tombstone Dust',
                desc=tutorial(
                    'Collect &68 grave dust&r from Corail Tombstone.',
                    why='Graves protect items on death — dust feeds magic crafts.',
                    steps=[
                        'Die less; when you do, recover from your grave.',
                        'Collect grave dust from Tombstone mechanics/crafts per JEI.',
                        'Stock eight dust for magic recipes you care about.',
                    ],
                    tip='Optional death QoL path — the best strategy is still not dying.',
                    nxt='Optional tools, or back to bosses.',
                ),
                task_count=8,
                deps=[0],
                rewards=[item('minecraft:bone', 32), xp_levels(1)],
                optional=True,
                subtitle='Death QoL',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=17.5,
                y=-2.5,
                task='create_sa:brass_drill_head',
                title='Brass Drill Head',
                desc=tutorial(
                    "Craft a brass drill head (Stuff 'N Additions).",
                    why='Extra Create tools for excavation-style play — optional flex craft.',
                    steps=[
                        'Craft the brass drill head once mechanisms and brass are plentiful.',
                        'Attach/use it per the mod’s tool recipes.',
                        'Treat it as a flex goal after the mechanism stockpile.',
                    ],
                    tip='Optional — skip if your Create drills already clear veins.',
                    nxt='Bosses and elytra remain the main endgame.',
                ),
                deps=[14],
                rewards=[item('create:brass_ingot', 8)],
                optional=True,
                subtitle='Tools',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=10,
                y=-4.5,
                task='minecraft:beacon',
                title='Beacon Base',
                desc=tutorial(
                    'Craft a beacon.',
                    why='Power it with your nether star — Haste II while placing Create shafts is a lifestyle.',
                    steps=[
                        'Craft the beacon and build a mineral pyramid (iron/gold/diamond/netherite/emerald).',
                        'Insert the nether star and select Haste (and Speed if the pyramid allows).',
                        'Build the factory inside the beacon range — thank yourself later.',
                    ],
                    tip='Optional but transformative for Create construction.',
                    nxt='Book complete — absurd factories await.',
                ),
                deps=[15],
                rewards=[item('minecraft:iron_block', 36), xp_levels(2)],
                optional=True,
                subtitle='Boss',
                hide_until_deps=True,
            ),
        ],
    )
