"""15. Beyond Brass quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import C_PRECISION, C_TRACK


def chapter() -> Chapter:
    return Chapter(
        key='late_game',
        base=500,
        chapter_id='A200000000000005',
        icon='minecraft:netherite_ingot',
        title='15. Beyond Brass',
        subtitle='Netherite, flight, railways, bosses, and the sky',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='minecraft:netherite_ingot',
                title='Netherite',
                desc=[
                    '&6Goal:&r Smith a netherite ingot.',
                    '',
                    'Ancient debris + gold. The late-game material gate for this book — furnaces, sticks, and flex.',
                    '',
                    '&7Tip:&r Bring fire resistance, a Waystone, and dignity.',
                    '&7Next:&r Flight, trains, cannons, and the finale bosses await.',
                ],
                links=require(C_PRECISION),
                rewards=[item('minecraft:ancient_debris', 4), xp_levels(3)],
                size=2.0,
                shape='gear',
                subtitle='Endgame gate',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='ironfurnaces:netherite_furnace',
                title='Netherite Furnace',
                desc=[
                    '&6Goal:&r Craft a Netherite Furnace.',
                    '',
                    'Top-tier smelting speed for when your ore drill finally wakes up.',
                ],
                deps=[0],
                rewards=[item('minecraft:netherite_ingot'), xp_levels(2)],
                subtitle='Smelting',
            ),
            Quest(
                n=2,
                x=2.5,
                y=2.5,
                task='ironchest:obsidian_chest',
                title='Obsidian Chest',
                desc=[
                    '&6Goal:&r Craft an Obsidian Chest.',
                    '',
                    'Blast-resistant storage for bases that… experiment with Big Cannons.',
                ],
                deps=[1],
                rewards=[item('minecraft:obsidian', 32)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=3,
                x=2.5,
                y=-2.5,
                task='ironchest:diamond_chest',
                title='Diamond Chest',
                desc=[
                    '&6Goal:&r Craft a Diamond Chest.',
                    '',
                    'Huge mixed storage before full digital networks take over.',
                ],
                deps=[1],
                rewards=[item('minecraft:diamond', 8)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=4,
                x=5,
                y=0,
                task='ironjetpacks:thruster',
                title='Jetpack Thrusters',
                desc=[
                    '&6Goal:&r Craft &62 Iron Jetpacks thrusters&r.',
                    '',
                    'Combine with coils, capacitors, cells, and a strap to assemble modular jetpacks.',
                    '',
                    '&7Tip:&r Charge with FE from your alternator / diesel / New Age setup.',
                ],
                task_count=2,
                deps=[0],
                rewards=[item('ironjetpacks:basic_coil', 2), xp_levels(1)],
                subtitle='Flight',
            ),
            Quest(
                n=5,
                x=7.5,
                y=0,
                task='ironjetpacks:cell',
                title='Jetpack Cell',
                desc=[
                    '&6Goal:&r Craft an Iron Jetpacks energy cell.',
                    '',
                    "Energy storage for your jetpack assembly — don't skip the battery.",
                ],
                deps=[4],
                rewards=[item('ironjetpacks:capacitor')],
                subtitle='Flight',
            ),
            Quest(
                n=6,
                x=10,
                y=0,
                task='ironjetpacks:jetpack',
                title='Iron Jetpack',
                desc=[
                    '&6Goal:&r Assemble an Iron Jetpacks jetpack.',
                    '',
                    'Charge it and take to the skies — independent from Create backtanks.',
                ],
                deps=[5],
                rewards=[xp_levels(3)],
                size=1.5,
                shape='hexagon',
                subtitle='Flight',
            ),
            Quest(
                n=7,
                x=5,
                y=-2.5,
                task='create_jetpack:jetpack',
                title='Create Jetpack',
                desc=[
                    '&6Goal:&r Craft the Create Jetpack.',
                    '',
                    'Runs off copper backtank pressure — perfect if your factory already fills tanks.',
                ],
                deps=[6],
                rewards=[item('create:copper_backtank'), xp_levels(2)],
                size=1.5,
                subtitle='Flight',
            ),
            Quest(
                n=8,
                x=7.5,
                y=-2.5,
                task='create_sa:brass_jetpack_chestplate',
                title='Brass Jetpack',
                desc=[
                    "&6Goal:&r Craft Stuff 'N Additions brass jetpack chestplate.",
                    '',
                    'Another flight option for brass-rich factories — pick your favorite sky kit.',
                ],
                deps=[7],
                rewards=[item('create:brass_ingot', 16), xp_levels(2)],
                optional=True,
                subtitle='Flight',
                hide_until_deps=True,
            ),
            Quest(
                n=9,
                x=5,
                y=2.5,
                task='createbigcannons:cannon_mount',
                title='Cannon Mount',
                desc=[
                    '&6Goal:&r Craft a Create Big Cannons mount.',
                    '',
                    "The base of a buildable cannon. Build responsibly. Or don't. We put it in the pack either way.",
                    '',
                    '&7Tip:&r Foundries and cast moulds make proper barrels — JEI is your friend.',
                ],
                deps=[14],
                rewards=[item('minecraft:iron_block', 4), xp_levels(1)],
                optional=True,
                subtitle='Chaos',
                hide_until_deps=True,
            ),
            Quest(
                n=10,
                x=7.5,
                y=2.5,
                task='createbigcannons:solid_shot',
                title='Solid Shot',
                desc=[
                    '&6Goal:&r Craft solid shot ammunition.',
                    '',
                    'Optional gunnery goal — test ranges strongly recommended.',
                ],
                deps=[9],
                rewards=[item('minecraft:gunpowder', 16)],
                optional=True,
                subtitle='Chaos',
                hide_until_deps=True,
            ),
            Quest(
                n=11,
                x=10,
                y=2.5,
                task='create:track',
                title='Rail Empire',
                desc=[
                    '&6Goal:&r Craft &664 Create tracks&r.',
                    '',
                    'Link factories across the map. Trains move bulk ore, fuel, and players.',
                ],
                task_count=64,
                deps=[0],
                links=require(C_TRACK),
                rewards=[item('create:precision_mechanism', 2), xp_levels(2)],
                subtitle='Trains',
            ),
            Quest(
                n=12,
                x=12.5,
                y=2.5,
                task='railways:conductor_whistle',
                title='Conductor Whistle',
                desc=[
                    "&6Goal:&r Craft a Steam 'n' Rails conductor whistle.",
                    '',
                    'Conductors, fancy tracks, and train QoL — run the railway like you mean it.',
                ],
                deps=[11],
                rewards=[item('railways:fuel_tank'), xp_levels(2)],
                subtitle='Trains',
            ),
            Quest(
                n=13,
                x=15,
                y=2.5,
                task='bellsandwhistles:headlight',
                title='Train Headlight',
                desc=[
                    '&6Goal:&r Craft a Bells & Whistles headlight.',
                    '',
                    'Dress up locomotives — pilots, grab rails, metro casing, and station flair.',
                ],
                deps=[12],
                rewards=[item('bellsandwhistles:metro_casing', 8)],
                optional=True,
                subtitle='Trains',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=12.5,
                y=0,
                task='create:precision_mechanism',
                title='Mechanism Stockpile',
                desc=[
                    '&6Goal:&r Stockpile &632 precision mechanisms&r.',
                    '',
                    "If this hurts, your assembly line isn't automated enough yet — go fix that.",
                    '',
                    '&7Tip:&r Mechanical crafters + deployers + arms should be feeding a chest nonstop.',
                ],
                task_count=32,
                deps=[6],
                links=require(C_PRECISION),
                rewards=[item('create:brass_sheet', 32), xp_levels(3)],
                size=1.5,
                subtitle='Logistics flex',
            ),
            Quest(
                n=15,
                x=15,
                y=0,
                task='minecraft:nether_star',
                title='Wither Down',
                desc=[
                    '&6Goal:&r Defeat the Wither and hold a nether star.',
                    '',
                    'Beacon bases make Create factories feel unfair in the best way — haste + speed while building is cracked.',
                ],
                deps=[14],
                rewards=[item('minecraft:diamond_block', 2), xp_levels(5)],
                size=1.75,
                shape='pentagon',
                subtitle='Boss',
            ),
            Quest(
                n=16,
                x=17.5,
                y=0,
                task='minecraft:dragon_egg',
                title='Dragon Egg',
                desc=[
                    '&6Goal:&r Claim the dragon egg after beating the Ender Dragon.',
                    '',
                    'Trophy of the End. Keep it safe — or display it above the factory.',
                ],
                deps=[15],
                rewards=[item('minecraft:end_crystal', 4), xp_levels(3)],
                optional=True,
                size=1.5,
                subtitle='Boss',
                hide_until_deps=True,
            ),
            Quest(
                n=17,
                x=20,
                y=0,
                task='minecraft:elytra',
                title='Elytra',
                desc=[
                    '&6Goal:&r Claim elytra from the End.',
                    '',
                    "Combine with a jetpack or fireworks — you're done with walking.",
                    '',
                    "You've reached the end of the guided quest book. Keep building absurd factories, railways, and questionable cannons.",
                    '',
                    '&7Tip:&r Shulker shells turn storage portable. Firework rockets are still valid tech.',
                ],
                deps=[15],
                rewards=[item('minecraft:firework_rocket', 64), item('minecraft:shulker_shell', 4), xp_levels(5)],
                size=2.0,
                shape='gear',
                subtitle='Finale',
            ),
            Quest(
                n=18,
                x=12.5,
                y=-2.5,
                task='constructionstick:netherite_stick',
                title='Netherite Construction Stick',
                desc=[
                    '&6Goal:&r Craft the netherite construction stick.',
                    '',
                    'Maximum reach building for megabases and rail yards.',
                ],
                deps=[1],
                rewards=[xp_levels(2)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=19,
                x=15,
                y=-2.5,
                task='tombstone:grave_dust',
                title='Tombstone Dust',
                desc=[
                    '&6Goal:&r Collect &68 grave dust&r from Corail Tombstone.',
                    '',
                    'Graves protect your items on death — dust feeds magic crafts. Die less; collect more.',
                ],
                task_count=8,
                deps=[0],
                rewards=[item('minecraft:bone', 32), xp_levels(1)],
                optional=True,
                subtitle='Death QoL',
                hide_until_deps=True,
            ),
            Quest(
                n=20,
                x=17.5,
                y=-2.5,
                task='create_sa:brass_drill_head',
                title='Brass Drill Head',
                desc=[
                    "&6Goal:&r Craft a brass drill head (Stuff 'N Additions).",
                    '',
                    'Extra Create tools for excavation-style play — optional flex craft.',
                ],
                deps=[14],
                rewards=[item('create:brass_ingot', 8)],
                optional=True,
                subtitle='Tools',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=10,
                y=-4.5,
                task='minecraft:beacon',
                title='Beacon Base',
                desc=[
                    '&6Goal:&r Craft a beacon.',
                    '',
                    'Power it with your nether star. Haste II while placing Create shafts is a lifestyle.',
                ],
                deps=[15],
                rewards=[item('minecraft:iron_block', 36), xp_levels(2)],
                optional=True,
                subtitle='Boss',
                hide_until_deps=True,
            ),
        ],
    )

