"""9. Mekanism quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_BRASS
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='mekanism',
        base=600,
        chapter_id='020000000000000A',
        icon='mekanism:steel_casing',
        title='9. Mekanism',
        subtitle='Steel casings, ore processing, gases, factories, and QIO',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='mekanism:ingot_osmium',
                title='Osmium Supply',
                desc=tutorial(
                    "Smelt &616 Osmium Ingots&r.",
                    why="Osmium is Mekanism's core metal — circuits, machines, compressors, and alloys all burn through it.",
                    steps=[
                        "Mine &6Osmium Ore&r (or raw osmium) from the world.",
                        "Smelt ore/raw into &6Osmium Ingots&r in any furnace, or enrich first for double dust yield.",
                    ],
                    tip="Create crushers work for early ore lines if your Mekanism hall is not up yet.",
                    nxt="Stock iron and carbon — steel infusion is next.",
                ),
                task_count=16,
                links=require(C_BRASS),
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='mekanism:ingot_steel',
                title='Steel Infusion',
                desc=tutorial(
                    "Craft &616 Steel Ingots&r.",
                    why="Steel unlocks &6Steel Casings&r — the chassis under nearly every Mekanism machine.",
                    steps=[
                        "Place a &6Metallurgic Infuser&r and power it (Energy Cube, cable, or charged Energy Tablet).",
                        "Put &6Coal&r, &6Charcoal&r, or &6Enriched Carbon&r in the infusion extra slot.",
                        "Insert &6Iron Ingots&r; collect &6Steel Ingots&r from the output (or pull steel from IE/MI if you already make it elsewhere).",
                    ],
                    tip="Enrich coal in an Enrichment Chamber later — enriched carbon lasts far longer than raw fuel.",
                    nxt="Batch steel into Steel Casings.",
                ),
                task_count=16,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Materials',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='mekanism:steel_casing',
                title='Steel Casing',
                desc=tutorial(
                    "Craft &68 Steel Casings&r.",
                    why="Almost every Mekanism machine sits on a Steel Casing. Batch them before the machine rush.",
                    steps=[
                        "Craft casings from &6Steel&r, &6Osmium&r, and &6Glass&r (check JEI for the exact pattern).",
                        "Keep a stack ready — Enrichment Chamber, Crusher, Factories, and Energy Cubes all consume them.",
                    ],
                    tip="Pair casings with Basic Control Circuits for the first machine wave.",
                    nxt="Make Basic Control Circuits next.",
                ),
                task_count=8,
                deps=[1],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Mekanism · Foundation',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='mekanism:basic_control_circuit',
                title='Basic Circuits',
                desc=tutorial(
                    "Craft &68 Basic Control Circuits&r.",
                    why="Circuits gate every machine tier. Basic is the first stop; Advanced/Elite/Ultimate climb the alloy ladder.",
                    steps=[
                        "Enrich &6Redstone&r in an Enrichment Chamber (or craft circuits once you have the recipe unlocked).",
                        "In a &6Metallurgic Infuser&r, infuse &6Osmium Ingots&r with &6Enriched Redstone&r to form Basic Control Circuits.",
                        "Stockpile — cables, transporters, and early machines each want several.",
                    ],
                    tip="Automate redstone enrichment before you mass-produce Advanced circuits.",
                    nxt="Build a dedicated Metallurgic Infuser for the alloy line.",
                ),
                task_count=8,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Foundation',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='mekanism:metallurgic_infuser',
                title='Metallurgic Infuser',
                desc=tutorial(
                    "Craft a Metallurgic Infuser.",
                    why="The Infuser is the heart of Mekanism — steel, circuits, infused/reinforced/atomic alloys, and enriched materials all start here.",
                    steps=[
                        "Craft and place the Infuser; connect FE via &6Universal Cable&r or an &6Energy Cube&r.",
                        "Open the GUI: main slot for the metal, left/extra slot for the infusion material (carbon, redstone, diamond, refined obsidian, tin, etc.).",
                        "Use a &6Configurator&r (Shift+right-click) to set auto-eject and side modes so pipes can pull outputs.",
                        "Optional: enrich materials first (coal→enriched carbon, redstone→enriched redstone) so each bar lasts longer.",
                    ],
                    tip="Energy Tablets charge early machines before your cable network is ready.",
                    nxt="Add an Enrichment Chamber for 2× ore dust and enriched infusion stock.",
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='mekanism:enrichment_chamber',
                title='Enrichment Chamber',
                desc=tutorial(
                    "Craft an Enrichment Chamber.",
                    why="Tier-1 ore processing: enrich ore → dust → smelt for double ingots. Also makes enriched redstone/diamond/carbon for the Infuser.",
                    steps=[
                        "Place and power the chamber; pipe ores into the input with Logistical Transporters or hoppers.",
                        "Enrich raw ores/ores into dusts, then smelt dusts for ~2× yield versus raw smelting.",
                        "Enrich redstone, diamond, coal, and refined-obsidian inputs for Metallurgic Infuser bars.",
                        "Configurator: enable auto-eject and lock sides so dusts leave cleanly into a furnace line.",
                    ],
                    tip="Speed and energy upgrades pay for themselves once ore lines are feeding it.",
                    nxt="Add a Crusher for dirt/dust intermediates and factory upgrades later.",
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='mekanism:crusher',
                title='Mekanism Crusher',
                desc=tutorial(
                    "Craft a Mekanism Crusher.",
                    why="Crushers turn clumps, shards, and crystals into dirty dusts/dusts along the higher ore-processing tiers — and crush solids for FE-powered dust lines.",
                    steps=[
                        "Place next to your Enrichment Chamber and power both.",
                        "Basic line: Enrich ore → smelt. Better line: Purification/Injection products → Crusher → Enrichment → Furnace.",
                        "Set side config so crushed outputs feed the Enrichment Chamber automatically.",
                    ],
                    tip="A Basic Tier Installer turns this into a multi-slot factory later.",
                    nxt="Infuse iron with redstone for Infused Alloy.",
                ),
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='mekanism:alloy_infused',
                title='Infused Alloy',
                desc=tutorial(
                    "Craft &68 Infused Alloys&r.",
                    why="Redstone-infused iron is the first alloy tier — Advanced circuits, mid machines, and transporters need it.",
                    steps=[
                        "In the Metallurgic Infuser, load &6Enriched Redstone&r (or redstone) as the infusion type.",
                        "Insert &6Iron Ingots&r; collect &6Infused Alloy&r from the output.",
                    ],
                    tip="Keep a dedicated Infuser on redstone so you are not constantly swapping carbon/redstone/diamond bars.",
                    nxt="Craft Advanced Control Circuits.",
                ),
                task_count=8,
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Alloys',
            ),
            Quest(
                n=8,
                x=0.0,
                y=2.5,
                task='mekanism:advanced_control_circuit',
                title='Advanced Circuits',
                desc=tutorial(
                    "Craft &64 Advanced Control Circuits&r.",
                    why="Advanced circuits unlock Purification, Injection, Osmium Compressor, Digital Miner, and factory installers.",
                    steps=[
                        "Craft Advanced Control Circuits from &6Basic Control Circuits&r + &6Infused Alloy&r (JEI).",
                        "Stockpile extras — every upgrade path burns through these.",
                    ],
                    tip="Automate infused alloy before chasing Elite circuits (reinforced alloy + advanced circuit).",
                    nxt="Build the Purification Chamber for the next ore-yield jump.",
                ),
                task_count=4,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Alloys',
            ),
            Quest(
                n=9,
                x=2.5,
                y=2.5,
                task='mekanism:purification_chamber',
                title='Purification Chamber',
                desc=tutorial(
                    "Craft a Purification Chamber.",
                    why="Oxygen-assisted purification is the next yield tier after enrichment — ores become clumps that crush into more dust.",
                    steps=[
                        "Place and power the Purification Chamber.",
                        "Pipe &6Oxygen&r in via &6Pressurized Tubes&r from an Electrolytic Separator (or Chemical Tank).",
                        "Feed ores; clumps leave the item output — crush → enrich → smelt for the upgraded chain.",
                        "Configurator: chemical input on one side, items on others; enable auto-eject.",
                    ],
                    tip="One separator can feed multiple purification machines if oxygen is buffered in a chemical tank.",
                    nxt="Build the Electrolytic Separator for O₂/H₂.",
                ),
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Ore processing',
            ),
            Quest(
                n=10,
                x=5.0,
                y=2.5,
                task='mekanism:electrolytic_separator',
                title='Electrolytic Separator',
                desc=tutorial(
                    "Craft an Electrolytic Separator.",
                    why="Splits water into &6Hydrogen&r and &6Oxygen&r — purification, HCl, gas-burning power, and many chemical recipes depend on it.",
                    steps=[
                        "Place and power the Separator; pipe &6Water&r into the fluid input (sink, pump, or Create hose).",
                        "Connect &6Pressurized Tubes&r from the O₂ and H₂ sides to tanks or machines.",
                        "Configurator: set dump modes if one gas backs up and stalls the machine (common when only oxygen is used).",
                        "Store surplus hydrogen in a Chemical Tank or burn it in a Gas-Burning Generator.",
                    ],
                    caution="If either gas output is full and dump is off, electrolysis stops — always give both gases somewhere to go.",
                    tip="Salt → brine electrolysis later yields chlorine for Hydrogen Chloride.",
                    nxt="Chemical Injection Chamber for elite ore yields.",
                ),
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Gases',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='mekanism:chemical_injection_chamber',
                title='Chemical Injection',
                desc=tutorial(
                    "Craft a Chemical Injection Chamber.",
                    why="Hydrogen Chloride injection pushes ore processing into elite shard yields — the step before full slurry/crystal lines.",
                    steps=[
                        "Make &6Hydrogen Chloride&r: Chemical Infuser combining &6Hydrogen&r + &6Chlorine&r (chlorine from brine in an Electrolytic Separator).",
                        "Pipe HCl into the Injection Chamber via Pressurized Tubes; power the machine.",
                        "Feed ores → shards; crush shards → dirty dust → enrich → smelt.",
                        "Later (optional): Chemical Dissolution + Sulfuric Acid → slurry → Chemical Washer → Crystalizer for max yield.",
                    ],
                    tip="Buffer HCl in a Basic Chemical Tank so the chamber never starves mid-batch.",
                    nxt="Osmium Compressor for refined glowstone/obsidian products.",
                ),
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Ore processing',
            ),
            Quest(
                n=12,
                x=10.0,
                y=2.5,
                task='mekanism:osmium_compressor',
                title='Osmium Compressor',
                desc=tutorial(
                    "Craft an Osmium Compressor.",
                    why="Compresses liquid osmium onto dusts for refined glowstone, refined obsidian, and other late intermediates on the Atomic Alloy path.",
                    steps=[
                        "Place and power the compressor; feed it &6Osmium&r (ingots/blocks as the recipe requires — check JEI).",
                        "Insert the dust/material to compress; collect refined products from the output.",
                        "Pipe inputs with Logistical Transporters; keep a chest of osmium beside it.",
                    ],
                    tip="Pair with a Combiner when recipes want compressed blocks or blended dusts.",
                    nxt="Climb to Atomic Alloy once reinforced alloy and refined obsidian are flowing.",
                ),
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='mekanism:basic_universal_cable',
                title='Universal Cables',
                desc=tutorial(
                    "Craft &632 Basic Universal Cables&r.",
                    why="Universal Cables move FE between cubes, machines, chargepads, and generators — Mekanism's power bus.",
                    steps=[
                        "Craft a stack of &6Basic Universal Cables&r and place them like redstone dust between machines.",
                        "Connect an &6Energy Cube&r or generator on one end and your machine cluster on the other.",
                        "Sneak-Configurator on a cable connection to set pull/push if energy is not flowing the way you expect.",
                    ],
                    tip="Upgrade cable tiers when transfer rate stalls under factory load.",
                    nxt="Add Logistical Transporters for items.",
                ),
                task_count=32,
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=14,
                x=15.0,
                y=2.5,
                task='mekanism:basic_logistical_transporter',
                title='Logistical Transporters',
                desc=tutorial(
                    "Craft &632 Basic Logistical Transporters&r.",
                    why="Mekanism item pipes with filters, color coding, and round-robin — excellent beside Create belts.",
                    steps=[
                        "Place transporters between inventories/machines like pipes.",
                        "Use a Configurator to set pull on the source chest and push toward machines.",
                        "Shift-Configurator cycles color; matching colors keep ore lines from mixing.",
                        "Add Logistical Sorters later for filtered routing into multiple machines.",
                    ],
                    tip="Round-robin helps feed multi-slot factories evenly.",
                    nxt="Pressurized Tubes for chemicals and gases.",
                ),
                task_count=32,
                deps=[13],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=15,
                x=17.5,
                y=2.5,
                task='mekanism:basic_pressurized_tube',
                title='Pressurized Tubes',
                desc=tutorial(
                    "Craft &616 Basic Pressurized Tubes&r.",
                    why="Move chemicals and gases between separators, chambers, tanks, and injectors without buckets.",
                    steps=[
                        "Place tubes from Electrolytic Separator outputs to Purification / Injection / Chemical Tanks.",
                        "Configurator on tube ends sets pull/push; mismatched modes are the usual 'no gas flowing' bug.",
                        "Buffer expensive gases in Chemical Tanks so machines do not stall mid-craft.",
                    ],
                    tip="Keep radioactive or expensive gases on dedicated color-coded networks.",
                    nxt="Park an Energy Cube at the center of the machine hall.",
                ),
                task_count=16,
                deps=[14],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=16,
                x=0.0,
                y=5.0,
                task='mekanism:basic_energy_cube',
                title='Energy Cube',
                desc=tutorial(
                    "Craft a Basic Energy Cube.",
                    why="Cubes buffer FE for machine halls so generators can keep working through demand spikes.",
                    steps=[
                        "Place the cube centrally among machines; cable generators into input sides.",
                        "Configurator each face: input from power, output toward machines (or use Universal Cables freely).",
                        "Upgrade Advanced → Elite → Ultimate as Digital Miner and factories demand more buffer.",
                    ],
                    tip="Short cable runs from a central cube cut transfer bottlenecks.",
                    nxt="QIO storage once power is stable — or Tier Installers for factories.",
                ),
                deps=[13],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Power',
            ),
            Quest(
                n=17,
                x=2.5,
                y=5.0,
                task='mekanism:basic_tier_installer',
                title='Factory Installer',
                desc=tutorial(
                    "Craft a Basic Tier Installer.",
                    why="Right-click a machine to turn it into a Factory with more parallel processing slots — huge ore-line throughput.",
                    steps=[
                        "Craft a &6Basic Tier Installer&r (Advanced circuits + alloys — check JEI).",
                        "Right-click a placed Enrichment Chamber, Crusher, Infuser, etc. to convert it into a Basic Factory.",
                        "Higher installers (Advanced/Elite/Ultimate) upgrade the same machine further in place.",
                        "Re-pipe items after upgrading — slot counts and side configs can need a refresh.",
                    ],
                    tip="Plan floor space; factories are wider in the GUI and hungry for power.",
                    nxt="Digital Miner when you want filter-based area mining.",
                ),
                deps=[8],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Factories',
            ),
            Quest(
                n=18,
                x=5.0,
                y=5.0,
                task='mekanism:digital_miner',
                title='Digital Miner',
                desc=tutorial(
                    "Craft a Digital Miner.",
                    why="Filter-based area mining that pulls ores (and more) without you swinging a pick — the ultimate ore vacuum.",
                    steps=[
                        "Place the miner with clear space; connect serious FE (Energy Cube + upgraded cables).",
                        "Open the GUI: set radius, Y min/max, silk touch / fortune modes as desired.",
                        "Add item filters for the ores you want (or inverse-filter junk).",
                        "Start the miner; pull items out with Logistical Transporters into storage.",
                    ],
                    caution="A wide unfiltered miner will shred the landscape and lag the area — set filters before starting.",
                    tip="Anchor it near a QIO or RS system so ores never sit in the internal buffer.",
                    nxt="Atomic Disassembler for a configurable all-tool.",
                ),
                deps=[8],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism · Late tools',
            ),
            Quest(
                n=19,
                x=7.5,
                y=5.0,
                task='mekanism:atomic_disassembler',
                title='Atomic Disassembler',
                desc=tutorial(
                    "Craft an Atomic Disassembler.",
                    why="A configurable all-tool that scales with energy — mining, combat, vein, and slow modes in one charged package.",
                    steps=[
                        "Craft the Disassembler (Atomic Alloy and late components — JEI).",
                        "Charge it on a &6Chargepad&r wired to your energy network, or in an Energy Cube GUI.",
                        "Sneak-scroll or use the mode key to switch digging/vein/slow modes as needed.",
                    ],
                    tip="Energy upgrades and a full cube make vein mode feel instant.",
                    nxt="QIO Dashboard for wireless bulk storage.",
                ),
                deps=[18],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Late tools',
            ),
            Quest(
                n=20,
                x=10.0,
                y=5.0,
                task='mekanism:qio_dashboard',
                title='QIO Dashboard',
                desc=tutorial(
                    "Craft a QIO Dashboard.",
                    why="Quantum Item Orchestration stores huge item volumes wirelessly once drives and frequencies are linked.",
                    steps=[
                        "Craft a &6QIO Drive Array&r, insert &6QIO Drives&r, and set a frequency name.",
                        "Craft the &6QIO Dashboard&r and set it to the same frequency.",
                        "Place QIO Exporters/Importers on chests or machine I/O to move items on that frequency.",
                        "Expand with larger drives as ore lines fill the first drive.",
                    ],
                    tip="One frequency per base keeps things simple until you need isolation.",
                    nxt="Atomic Alloy for teleporters and elite crafts.",
                ),
                deps=[16],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Mekanism · Storage',
            ),
            Quest(
                n=21,
                x=12.5,
                y=5.0,
                task='mekanism:alloy_atomic',
                title='Atomic Alloy',
                desc=tutorial(
                    "Craft &64 Atomic Alloys&r.",
                    why="Diamond-then-obsidian infused alloy is Mekanism's top crafting tier for teleporters, elite machines, and MekaSuit modules.",
                    steps=[
                        "Infuse &6Infused Alloy&r with diamond → &6Reinforced Alloy&r.",
                        "Make &6Refined Obsidian Dust&r (Enrich obsidian → compress with osmium as recipes require).",
                        "Infuse Reinforced Alloy with refined obsidian → &6Atomic Alloy&r.",
                    ],
                    tip="Automate the full alloy ladder before chasing MekaSuit modules.",
                    nxt="Frame a Mekanism Teleporter.",
                ),
                task_count=4,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Endgame',
            ),
            Quest(
                n=22,
                x=15.0,
                y=5.0,
                task='mekanism:teleporter',
                title='Mekanism Teleporter',
                desc=tutorial(
                    "Craft a Mekanism Teleporter.",
                    why="Linked portals give instant base-to-base travel once frames and frequencies are set.",
                    steps=[
                        "Build a portal frame from &6Teleporter Frame&r blocks (usually a hollow rectangle like a nether portal).",
                        "Place the &6Teleporter&r block in the frame; power it heavily.",
                        "Set matching frequencies on two teleporters; walk in to travel.",
                        "Buffer FE in an Energy Cube beside each pad — jumps are energy-hungry.",
                    ],
                    tip="Frames are cheap; energy cost and correct frequency linking are the real setup.",
                    nxt="Chapter complete — push factories, ore tiers, and QIO as your base grows.",
                ),
                deps=[21],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism · Endgame',
            ),
        ],
    )
