"""9. Mekanism quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_BRASS


def chapter() -> Chapter:
    return Chapter(
        key='mekanism',
        base=600,
        chapter_id='A20000000000000A',
        icon='mekanism:steel_casing',
        title='9. Mekanism',
        subtitle='Steel casings, ore processing, gases, factories, and QIO',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='mekanism:ingot_osmium',
                title='Osmium Supply',
                desc=[
                    '&6Goal:&r Smelt &616 Osmium Ingots&r.',
                    '',
                    "Osmium is Mekanism's signature metal — circuits, machines, and compressed alloys all start here.",
                    '',
                    '&7Tip:&r Mine osmium ore or process it through Create crushers if you prefer factory ore lines.',
                ],
                task_count=16,
                links=require(C_BRASS),
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='mekanism:ingot_steel',
                title='Steel Infusion',
                desc=[
                    '&6Goal:&r Craft &616 Steel Ingots&r.',
                    '',
                    'Infuse iron with carbon in a Metallurgic Infuser (or pull steel from another mod) to unlock Steel Casings.',
                    '',
                    '&7Tip:&r Keep charcoal or coal dust stocked; early steel batches disappear fast.',
                ],
                task_count=16,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Materials',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='mekanism:steel_casing',
                title='Steel Casing',
                desc=[
                    '&6Goal:&r Craft &68 Steel Casings&r.',
                    '',
                    'Almost every Mekanism machine sits on a Steel Casing. Batch them before the machine rush.',
                    '',
                    '&7Tip:&r Pair casings with Basic Control Circuits for the first machine wave.',
                ],
                task_count=8,
                deps=[1],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Mekanism · Foundation',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='mekanism:basic_control_circuit',
                title='Basic Circuits',
                desc=[
                    '&6Goal:&r Craft &68 Basic Control Circuits&r.',
                    '',
                    'Circuits gate machine tiers. Basic is your first stop; Advanced/Elite/Ultimate follow the alloy ladder.',
                    '',
                    '&7Tip:&r Enrich redstone and compress circuits with osmium once the Enrichment Chamber is up.',
                ],
                task_count=8,
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Foundation',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='mekanism:metallurgic_infuser',
                title='Metallurgic Infuser',
                desc=[
                    '&6Goal:&r Craft a Metallurgic Infuser.',
                    '',
                    'Infuse metals with carbon, redstone, diamond, refined obsidian, and more — the heart of Mekanism alloys.',
                    '',
                    '&7Tip:&r Side-config input/output with the Configurator; energy tablets charge early machines.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='mekanism:enrichment_chamber',
                title='Enrichment Chamber',
                desc=[
                    '&6Goal:&r Craft an Enrichment Chamber.',
                    '',
                    'Enrich ores, redstone, diamonds, and other materials for better yields and circuit ingredients.',
                    '',
                    '&7Tip:&r Speed and energy upgrades pay for themselves once ore lines are feeding it.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='mekanism:crusher',
                title='Mekanism Crusher',
                desc=[
                    '&6Goal:&r Craft a Mekanism Crusher.',
                    '',
                    'Crush ores and intermediates alongside Create mills — useful when you want FE-powered dust production.',
                    '',
                    '&7Tip:&r Factory upgrades turn this into a multi-slot crushing line later.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='mekanism:alloy_infused',
                title='Infused Alloy',
                desc=[
                    '&6Goal:&r Craft &68 Infused Alloys&r.',
                    '',
                    'Redstone-infused iron is the first alloy tier — Advanced circuits and many mid machines need it.',
                    '',
                    '&7Tip:&r Automate redstone enrichment before you mass-produce Advanced Control Circuits.',
                ],
                task_count=8,
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Alloys',
            ),
            Quest(
                n=8,
                x=0.0,
                y=2.5,
                task='mekanism:advanced_control_circuit',
                title='Advanced Circuits',
                desc=[
                    '&6Goal:&r Craft &64 Advanced Control Circuits&r.',
                    '',
                    'Advanced circuits unlock stronger machines, better transporters, and the next alloy step.',
                    '',
                    '&7Tip:&r Stockpile infused alloy; every upgrade path burns through these.',
                ],
                task_count=4,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Alloys',
            ),
            Quest(
                n=9,
                x=2.5,
                y=2.5,
                task='mekanism:purification_chamber',
                title='Purification Chamber',
                desc=[
                    '&6Goal:&r Craft a Purification Chamber.',
                    '',
                    'Oxygen-assisted ore purification is the next yield jump after enrichment.',
                    '',
                    '&7Tip:&r Feed oxygen from an Electrolytic Separator once you start gas processing.',
                ],
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Ore processing',
            ),
            Quest(
                n=10,
                x=5.0,
                y=2.5,
                task='mekanism:electrolytic_separator',
                title='Electrolytic Separator',
                desc=[
                    '&6Goal:&r Craft an Electrolytic Separator.',
                    '',
                    'Split water into hydrogen and oxygen — coolant, purification, and gas-burning power all depend on it.',
                    '',
                    '&7Tip:&r Dump excess hydrogen into a Gas-Burning Generator or store it in chemical tanks.',
                ],
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Gases',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='mekanism:chemical_injection_chamber',
                title='Chemical Injection',
                desc=[
                    '&6Goal:&r Craft a Chemical Injection Chamber.',
                    '',
                    'Hydrogen chloride injection pushes ore processing into elite yields.',
                    '',
                    '&7Tip:&r Make HCl by infusing hydrogen with chlorine from salt brine electrolysis.',
                ],
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Ore processing',
            ),
            Quest(
                n=12,
                x=10.0,
                y=2.5,
                task='mekanism:osmium_compressor',
                title='Osmium Compressor',
                desc=[
                    '&6Goal:&r Craft an Osmium Compressor.',
                    '',
                    'Compress osmium onto dusts for refined glowstone, obsidian products, and other late intermediates.',
                    '',
                    '&7Tip:&r Pair with a Combiner when recipes want compressed blocks or blended dusts.',
                ],
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Machines',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='mekanism:basic_universal_cable',
                title='Universal Cables',
                desc=[
                    '&6Goal:&r Craft &632 Basic Universal Cables&r.',
                    '',
                    'Move FE between cubes, machines, and chargepads. Upgrade cable tiers when transfer rate stalls.',
                    '',
                    '&7Tip:&r Configurator sets pull/push modes on cable connections.',
                ],
                task_count=32,
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=14,
                x=15.0,
                y=2.5,
                task='mekanism:basic_logistical_transporter',
                title='Logistical Transporters',
                desc=[
                    '&6Goal:&r Craft &632 Basic Logistical Transporters&r.',
                    '',
                    "Mekanism's item pipes with filters, color coding, and round-robin — great beside Create belts.",
                    '',
                    '&7Tip:&r Use configurator color modes to keep ore lines from mixing.',
                ],
                task_count=32,
                deps=[13],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=15,
                x=17.5,
                y=2.5,
                task='mekanism:basic_pressurized_tube',
                title='Pressurized Tubes',
                desc=[
                    '&6Goal:&r Craft &616 Basic Pressurized Tubes&r.',
                    '',
                    'Move chemicals and gases between separators, chambers, and tanks.',
                    '',
                    '&7Tip:&r Leak-free routing matters once radioactive or expensive gases enter the network.',
                ],
                task_count=16,
                deps=[14],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Logistics',
            ),
            Quest(
                n=16,
                x=0.0,
                y=5.0,
                task='mekanism:basic_energy_cube',
                title='Energy Cube',
                desc=[
                    '&6Goal:&r Craft a Basic Energy Cube.',
                    '',
                    'Buffer FE for machine halls. Upgrade through Advanced/Elite/Ultimate as demand grows.',
                    '',
                    '&7Tip:&r Place cubes at the center of machine clusters to shorten cable runs.',
                ],
                deps=[13],
                rewards=[xp_levels(1)],
                subtitle='Mekanism · Power',
            ),
            Quest(
                n=17,
                x=2.5,
                y=5.0,
                task='mekanism:basic_tier_installer',
                title='Factory Installer',
                desc=[
                    '&6Goal:&r Craft a Basic Tier Installer.',
                    '',
                    'Right-click a machine to turn it into a factory with more processing slots.',
                    '',
                    '&7Tip:&r Higher-tier installers stack further — plan floor space before upgrading everything.',
                ],
                deps=[8],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Factories',
            ),
            Quest(
                n=18,
                x=5.0,
                y=5.0,
                task='mekanism:digital_miner',
                title='Digital Miner',
                desc=[
                    '&6Goal:&r Craft a Digital Miner.',
                    '',
                    'Filter-based area mining that respects configs and silk-touch options — the ultimate ore vacuum.',
                    '',
                    "&7Tip:&r Feed it serious power and set precise filters so you don't shred your base biome.",
                ],
                deps=[8],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism · Late tools',
            ),
            Quest(
                n=19,
                x=7.5,
                y=5.0,
                task='mekanism:atomic_disassembler',
                title='Atomic Disassembler',
                desc=[
                    '&6Goal:&r Craft an Atomic Disassembler.',
                    '',
                    'A configurable all-tool that scales with energy upgrades — mining, combat, and vein modes in one.',
                    '',
                    '&7Tip:&r Charge it on a Chargepad connected to your energy network.',
                ],
                deps=[18],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Late tools',
            ),
            Quest(
                n=20,
                x=10.0,
                y=5.0,
                task='mekanism:qio_dashboard',
                title='QIO Dashboard',
                desc=[
                    '&6Goal:&r Craft a QIO Dashboard.',
                    '',
                    'Quantum Item Orchestration stores huge item volumes wirelessly once drives and frequency links are set.',
                    '',
                    '&7Tip:&r Start with a base QIO Drive and expand frequencies carefully.',
                ],
                deps=[16],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Mekanism · Storage',
            ),
            Quest(
                n=21,
                x=12.5,
                y=5.0,
                task='mekanism:alloy_atomic',
                title='Atomic Alloy',
                desc=[
                    '&6Goal:&r Craft &64 Atomic Alloys&r.',
                    '',
                    "Diamond-infused reinforced alloy is Mekanism's top crafting tier for elite machines and teleporters.",
                    '',
                    '&7Tip:&r Automate the full alloy ladder before chasing MekaSuit modules.',
                ],
                task_count=4,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Mekanism · Endgame',
            ),
            Quest(
                n=22,
                x=15.0,
                y=5.0,
                task='mekanism:teleporter',
                title='Mekanism Teleporter',
                desc=[
                    '&6Goal:&r Craft a Mekanism Teleporter.',
                    '',
                    'Frame a portal and link frequencies for instant base-to-base travel.',
                    '',
                    '&7Tip:&r Teleporter Frames are cheap; energy cost and linking are the real setup.',
                ],
                deps=[21],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism · Endgame',
            ),
        ],
    )

