"""10. Mekanism Reactors quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import MEKANISM_START


def chapter() -> Chapter:
    return Chapter(
        key='mekanism_generators',
        base=650,
        chapter_id='A20000000000000B',
        icon='mekanismgenerators:fission_reactor_casing',
        title='10. Mekanism Reactors',
        subtitle='Heat, solar, wind, fission, turbines, and fusion power',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='mekanismgenerators:heat_generator',
                title='Heat Generator',
                desc=[
                    '&6Goal:&r Craft a Heat Generator.',
                    '',
                    'Burn solid fuel or sit beside lava/heat sources for your first Mekanism FE — perfect for bootstrapping machines.',
                    '',
                    '&7Tip:&r Lava-adjacent heat generation is quiet and steady for early steel casings.',
                ],
                links=require(MEKANISM_START),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Mekanism Generators · Early power',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='mekanismgenerators:solar_generator',
                title='Solar Generator',
                desc=[
                    '&6Goal:&r Craft &62 Solar Generators&r.',
                    '',
                    'Daytime FE with no fuel logistics. Pair with Energy Cubes so night shifts still run.',
                    '',
                    '&7Tip:&r Advanced Solar Generators cover a 3×3 footprint for much higher output.',
                ],
                task_count=2,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Early power',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='mekanismgenerators:wind_generator',
                title='Wind Generator',
                desc=[
                    '&6Goal:&r Craft a Wind Generator.',
                    '',
                    'Height-scaled wind power that runs day and night — tower them above your factory roof.',
                    '',
                    '&7Tip:&r Higher Y-levels produce more FE; check the GUI after placing.',
                ],
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Early power',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='mekanismgenerators:bio_generator',
                title='Bio-Generator',
                desc=[
                    '&6Goal:&r Craft a Bio-Generator.',
                    '',
                    'Burn bio fuel refined from organic matter when you want compact fuel-based FE.',
                    '',
                    '&7Tip:&r Farms and compost chains keep this fed without coal runs.',
                ],
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Early power',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='mekanismgenerators:gas_burning_generator',
                title='Gas-Burning Generator',
                desc=[
                    '&6Goal:&r Craft a Gas-Burning Generator.',
                    '',
                    'Burn hydrogen (and other fuels) from your Electrolytic Separator for dense FE.',
                    '',
                    '&7Tip:&r Pipe hydrogen with pressurized tubes; excess water electrolysis becomes free power.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Gas power',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='mekanismgenerators:advanced_solar_generator',
                title='Advanced Solar',
                desc=[
                    '&6Goal:&r Craft an Advanced Solar Generator.',
                    '',
                    'A larger solar array for mid-game machine halls before nuclear options.',
                    '',
                    '&7Tip:&r Still daylight-gated — buffer into Induction Matrices or Energy Cubes.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Early power',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='mekanismgenerators:fission_reactor_casing',
                title='Fission Casing',
                desc=[
                    '&6Goal:&r Craft &632 Fission Reactor Casings&r.',
                    '',
                    'Fission reactors are hollow cuboids of casing, ports, fuel assemblies, and control rods.',
                    '',
                    '&7Tip:&r Read the multiblock overlay carefully — leaks and missing corners fail formation.',
                ],
                task_count=32,
                deps=[4],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism Generators · Fission',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='mekanismgenerators:fission_fuel_assembly',
                title='Fuel Assemblies',
                desc=[
                    '&6Goal:&r Craft &64 Fission Fuel Assemblies&r.',
                    '',
                    'Fuel assemblies hold fissile fuel. More assemblies raise heat and output — and meltdown risk.',
                    '',
                    '&7Tip:&r Start small; add assemblies only after coolant and waste handling are proven.',
                ],
                task_count=4,
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Fission',
            ),
            Quest(
                n=8,
                x=0.0,
                y=2.5,
                task='mekanismgenerators:control_rod_assembly',
                title='Control Rods',
                desc=[
                    '&6Goal:&r Craft &62 Control Rod Assemblies&r.',
                    '',
                    'Control rods throttle the reaction. Keep enough rods to SCRAM if heat spikes.',
                    '',
                    '&7Tip:&r Logic adapters can automate rod insertion from redstone or ID.',
                ],
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Fission',
            ),
            Quest(
                n=9,
                x=2.5,
                y=2.5,
                task='mekanismgenerators:fission_reactor_port',
                title='Fission Ports',
                desc=[
                    '&6Goal:&r Craft &62 Fission Reactor Ports&r.',
                    '',
                    'Ports inject coolant, extract heated coolant/waste, and connect to boilers or turbines.',
                    '',
                    '&7Tip:&r Never run a reactor without a planned coolant loop and waste barrel strategy.',
                ],
                task_count=2,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Mekanism Generators · Fission',
            ),
            Quest(
                n=10,
                x=5.0,
                y=2.5,
                task='mekanismgenerators:turbine_casing',
                title='Industrial Turbine',
                desc=[
                    '&6Goal:&r Craft &624 Turbine Casings&r.',
                    '',
                    'Steam from fission (via boiler) or other sources spins an Industrial Turbine for huge FE.',
                    '',
                    '&7Tip:&r Rotors, blades, vents, and electromagnetic coils complete the multiblock.',
                ],
                task_count=24,
                deps=[9],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Mekanism Generators · Turbine',
            ),
            Quest(
                n=11,
                x=7.5,
                y=2.5,
                task='mekanismgenerators:turbine_blade',
                title='Turbine Blades',
                desc=[
                    '&6Goal:&r Craft &68 Turbine Blades&r.',
                    '',
                    'Blades on the rotor shaft determine flow capacity — match vents and condensers to blade count.',
                    '',
                    '&7Tip:&r Undersized vents choke output; oversized blades without steam waste materials.',
                ],
                task_count=8,
                deps=[10],
                rewards=[xp_levels(2)],
                subtitle='Mekanism Generators · Turbine',
            ),
            Quest(
                n=12,
                x=10.0,
                y=2.5,
                task='mekanismgenerators:electromagnetic_coil',
                title='Electromagnetic Coils',
                desc=[
                    '&6Goal:&r Craft &62 Electromagnetic Coils&r.',
                    '',
                    'Coils convert rotor motion into FE. More coils raise energy production for a given steam flow.',
                    '',
                    '&7Tip:&r Saturating condensers help close the water loop for continuous operation.',
                ],
                task_count=2,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Mekanism Generators · Turbine',
            ),
            Quest(
                n=13,
                x=12.5,
                y=2.5,
                task='mekanismgenerators:fusion_reactor_frame',
                title='Fusion Frame',
                desc=[
                    '&6Goal:&r Craft &616 Fusion Reactor Frames&r.',
                    '',
                    "Fusion is Mekanism's endgame power — frame a reactor, inject D-T fuel, and ignite with lasers.",
                    '',
                    '&7Tip:&r Prepare hohlraums, laser amplifiers, and serious power before the first ignition attempt.',
                ],
                task_count=16,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Mekanism Generators · Fusion',
            ),
            Quest(
                n=14,
                x=15.0,
                y=2.5,
                task='mekanismgenerators:fusion_reactor_controller',
                title='Fusion Controller',
                desc=[
                    '&6Goal:&r Craft a Fusion Reactor Controller.',
                    '',
                    'The brain of the fusion multiblock. Monitor heat, fuel, and injection rates from its GUI.',
                    '',
                    '&7Tip:&r Water cooling and steam extraction can feed the same turbine network as fission.',
                ],
                deps=[13],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Mekanism Generators · Fusion',
            ),
            Quest(
                n=15,
                x=17.5,
                y=2.5,
                task='mekanismgenerators:hohlraum',
                title='Hohlraum',
                desc=[
                    '&6Goal:&r Craft a Hohlraum.',
                    '',
                    'Load fusion fuel into a hohlraum and ignite the reactor with a charged laser focus matrix.',
                    '',
                    '&7Tip:&r Keep spare hohlraums; failed ignitions and restarts consume them.',
                ],
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Mekanism Generators · Fusion',
            ),
        ],
    )

