"""12. Modern Industrialization quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='modern_industrialization',
        base=750,
        chapter_id='A20000000000000D',
        icon='modern_industrialization:forge_hammer',
        title='12. Modern Industrialization',
        subtitle='Steam age, steel, circuits, electric machines, and quarries',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='modern_industrialization:forge_hammer',
                title='Forge Hammer',
                desc=tutorial(
                    "Craft a Forge Hammer.",
                    why="MI starts with manual forging — plates, rods, rings, and bolts from ingots before steam machines take over.",
                    steps=[
                        "Craft and place the &6Forge Hammer&r.",
                        "Right-click with &6Iron&r (and other) ingots to form plates/rods per JEI; repeat for a starter stockpile.",
                        "Keep the hammer until bronze compressors automate plate spam.",
                    ],
                    tip="Pound a stack of iron plates now; bronze recipes will thank you.",
                    nxt="Alloy copper and tin into Bronze.",
                ),
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Modern Industrialization · Age 1',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='modern_industrialization:bronze_ingot',
                title='Bronze Age',
                desc=tutorial(
                    "Craft &616 Bronze Ingots&r.",
                    why="Bronze unlocks the first steam machines and boilers — MI's true beginning.",
                    steps=[
                        "Combine &6Copper&r + &6Tin&r into bronze via MI recipes (forge hammer dusts, mixing, or JEI path for this pack).",
                        "Smelt dusts/blends into &6Bronze Ingots&r if needed.",
                        "Hammer bronze into plates/rods for boiler and machine crafts.",
                    ],
                    tip="Create mixing can help if you already run a brass factory nearby.",
                    nxt="Craft a Bronze Boiler and get steam flowing.",
                ),
                task_count=16,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Age 1',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='modern_industrialization:bronze_boiler',
                title='Bronze Boiler',
                desc=tutorial(
                    "Craft a Bronze Boiler.",
                    why="Burns fuel with water to make steam — the lifeblood of every bronze-age machine.",
                    steps=[
                        "Place the &6Bronze Boiler&r; put solid fuel in the fuel slot.",
                        "Pipe or bucket &6Water&r into the water hatch/tank — a dry boiler makes no steam.",
                        "Connect &6Fluid Pipes&r from the steam output to the steam input of nearby bronze machines.",
                        "Wrench pipe connections if steam is not arriving (MI pipes are directional).",
                    ],
                    tip="A Water Pump or continuous Create hose keeps boilers topped up.",
                    nxt="Bronze Furnace for steam smelting.",
                ),
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='modern_industrialization:bronze_furnace',
                title='Bronze Furnace',
                desc=tutorial(
                    "Craft a Bronze Furnace.",
                    why="Steam-powered smelting that outpaces a vanilla furnace once steam is stable.",
                    steps=[
                        "Place the furnace beside the boiler; pipe &6Steam&r into its fluid input.",
                        "Pipe ores/items into the item input; pull ingots from the output with item pipes.",
                        "Use a wrench to set pipe push/pull so steam and items flow the right way.",
                    ],
                    tip="One boiler can feed several steam machines if pipe throughput holds.",
                    nxt="Bronze Compressor to automate plates.",
                ),
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='modern_industrialization:bronze_compressor',
                title='Bronze Compressor',
                desc=tutorial(
                    "Craft a Bronze Compressor.",
                    why="Automates plates and compressed parts so you can retire the Forge Hammer for bulk work.",
                    steps=[
                        "Place and pipe in steam + ingots.",
                        "Pull plates into a chest feeding machine crafts.",
                        "Overproduce — steel-age recipes still want piles of plates.",
                    ],
                    tip="Keep a small forge hammer for odd parts the compressor does not cover yet.",
                    nxt="Bronze Macerator for early dusts.",
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='modern_industrialization:bronze_macerator',
                title='Bronze Macerator',
                desc=tutorial(
                    "Craft a Bronze Macerator.",
                    why="Crush ores and solids with steam power — MI's early dust line and better ore yields.",
                    steps=[
                        "Pipe steam in; feed ores to the item input.",
                        "Macerate → furnace (or further MI processing) for improved yield where recipes allow.",
                        "Buffer dusts before the furnace so steam blips do not idle the line.",
                    ],
                    tip="Double-process ores when JEI shows a dust path with bonus outputs.",
                    nxt="Build the Coke Oven multiblock for coal coke.",
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='modern_industrialization:coke_oven',
                title='Coke Oven',
                desc=tutorial(
                    "Build a Coke Oven multiblock.",
                    why="Coal coke and creosote start the steel path — required fuel/input for the Steam Blast Furnace.",
                    steps=[
                        "Craft &6Coke Oven Bricks&r (fire clay path — JEI) and check the in-game guidebook shape.",
                        "Build the hollow brick structure; place &6Item/Fluid Hatches&r where the diagram shows.",
                        "Use the &6Wrench&r to form/configure the controller once the shape is valid.",
                        "Feed coal; pull coke from the item hatch and creosote from the fluid hatch into a tank.",
                    ],
                    tip="Creosote is useful for treated wood elsewhere — store it instead of voiding.",
                    nxt="Steam Blast Furnace for steel.",
                ),
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='modern_industrialization:steam_blast_furnace',
                title='Steam Blast Furnace',
                desc=tutorial(
                    "Build a Steam Blast Furnace.",
                    why="Blasts iron with coke toward steel — the gate to steel machines and the electric age.",
                    steps=[
                        "Follow JEI/guidebook for the &6Steam Blast Furnace&r brick shape (fire-clay / coke oven bricks).",
                        "Replace edge/face blocks with &6Item Inputs&r, &6Item Outputs&r, and &6Fluid Inputs&r (steam) hatches as required.",
                        "Wrench the controller to form the multiblock when the shape turns valid.",
                        "Pipe steam from boilers, insert iron + coke per recipe, pull steel from the output hatch.",
                    ],
                    caution="Missing or wrong-tier hatches prevent formation — compare every layer to the guide.",
                    tip="Keep steam pressure high; starved SBFs crawl. Parallel bronze boilers help.",
                    nxt="Stockpile Steel Ingots.",
                ),
                deps=[6],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='modern_industrialization:steel_ingot',
                title='Steel Stockpile',
                desc=tutorial(
                    "Produce &616 Steel Ingots&r.",
                    why="Steel unlocks stronger machines, better boilers, hulls, and the jump toward electricity.",
                    steps=[
                        "Run iron + coke through the Steam Blast Furnace until you have 16+ &6Steel Ingots&r.",
                        "Immediately compress/hammer plates and rods — steel machine crafts eat them.",
                    ],
                    tip="Batch plates and rods right after the first steel pour.",
                    nxt="Steel Boiler and Analog Circuits in parallel.",
                ),
                task_count=16,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='modern_industrialization:steel_boiler',
                title='Steel Boiler',
                desc=tutorial(
                    "Craft a Steel Boiler.",
                    why="Higher steam output for steel-tier machines, larger steam multiblocks, and denser factories.",
                    steps=[
                        "Craft and place the &6Steel Boiler&r; feed fuel + water like the bronze version.",
                        "Upgrade fluid pipe networks when steam demand outruns bronze boilers.",
                        "Optional: progress toward a &6Large Steam Boiler&r multiblock when single-block boilers fall behind.",
                    ],
                    tip="Water input rate is as important as fuel — add pumps early.",
                    nxt="Analog Circuits for electric machines.",
                ),
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='modern_industrialization:analog_circuit',
                title='Analog Circuits',
                desc=tutorial(
                    "Craft &68 Analog Circuits&r.",
                    why="Circuits are MI's long progression spine — analog today, electronic/digital/quantum later.",
                    steps=[
                        "Craft circuit boards and analog components per JEI (wires, resistors, plates).",
                        "Assemble &6Analog Circuits&r in batches of 8+.",
                        "Start automating board ingredients before the craft spam hurts.",
                    ],
                    tip="A dedicated steam assembler line for circuits pays for itself quickly.",
                    nxt="Basic Machine Hulls for LV electric machines.",
                ),
                task_count=8,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='modern_industrialization:basic_machine_hull',
                title='Basic Machine Hull',
                desc=tutorial(
                    "Craft &64 Basic Machine Hulls&r.",
                    why="Electric machines are built on hulls. Basic hulls cover LV; advanced tiers follow.",
                    steps=[
                        "Craft hulls from steel/analog parts (JEI).",
                        "Stock motors, cables, and conveyors alongside — they share materials with hull crafts.",
                    ],
                    tip="Never craft just one hull; the next four machines will want them immediately.",
                    nxt="Motors, then Electric Macerator.",
                ),
                task_count=4,
                deps=[10],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='modern_industrialization:motor',
                title='Motors',
                desc=tutorial(
                    "Craft &64 Motors&r.",
                    why="Motors drive electric machines and appear in countless component recipes.",
                    steps=[
                        "Craft &6Tin Cables&r / rubber-insulated wire as JEI requires.",
                        "Assemble &6Motors&r from rods, cables, and magnetic parts.",
                        "Keep extras — conveyors, robot arms, and generators eat motors too.",
                    ],
                    tip="Rubber often gates early motor crafts — solve latex/rubber before mass production.",
                    nxt="Electric Macerator on LV power.",
                ),
                task_count=4,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='modern_industrialization:electric_macerator',
                title='Electric Macerator',
                desc=tutorial(
                    "Craft an Electric Macerator.",
                    why="EU/FE-powered crushing for serious ore throughput once LV power is online.",
                    steps=[
                        "Place the macerator; connect &6LV Cables&r from a generator or energy storage to the energy hatch/side.",
                        "Pipe items in/out; wrench cable and pipe ends if IO is wrong.",
                        "Feed dusts into electric furnaces or further MI processing lines.",
                    ],
                    tip="Pull dusts into RS or Create storage so the machine never jams full.",
                    nxt="LV Diesel Generator for steady power.",
                ),
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='modern_industrialization:lv_diesel_generator',
                title='LV Diesel Generator',
                desc=tutorial(
                    "Craft an LV Diesel Generator.",
                    why="Burns diesel/biodiesel for steady LV energy when steam turbines are not enough.",
                    steps=[
                        "Place the generator; pipe &6Diesel&r or &6Biodiesel&r into the fluid input.",
                        "Connect LV cables from the energy output to machines or a storage block.",
                        "Buffer fuel in a tank so the generator does not pulse empty.",
                    ],
                    tip="Oil drilling and distillation unlock proper fuel logistics later.",
                    nxt="Electronic Circuits for MV progression.",
                ),
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='modern_industrialization:electronic_circuit',
                title='Electronic Circuits',
                desc=tutorial(
                    "Craft &64 Electronic Circuits&r.",
                    why="MV progression and better machines demand electronic circuits — the next circuit factory tier.",
                    steps=[
                        "Unlock and craft electronic-tier boards/components (JEI).",
                        "Assemble &6Electronic Circuits&r; automate boards before you feel the spam.",
                    ],
                    tip="Treat circuit crafting as its own factory wing, not a crafting-table chore.",
                    nxt="Electric Quarry for bulk resources.",
                ),
                task_count=4,
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Mid game',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='modern_industrialization:electric_quarry',
                title='Electric Quarry',
                desc=tutorial(
                    "Craft an Electric Quarry.",
                    why="Automated area mining with drill heads and power — MI's answer to bulk resource gathering.",
                    steps=[
                        "Place the &6Electric Quarry&r with clear working volume below/around per guidebook.",
                        "Insert &6Drill Heads&r and connect serious LV/MV power.",
                        "Pipe or inventory-pull mined items into storage; restock drill heads as they wear.",
                        "Wrench/configure the work area before leaving it running overnight.",
                    ],
                    caution="Quarries erase terrain in their zone — do not aim one under your base.",
                    tip="Clear the work area and supply drill heads before activating.",
                    nxt="Digital Circuits for HV-tier brains.",
                ),
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Modern Industrialization · Mid game',
            ),
            Quest(
                n=17,
                x=20.0,
                y=2.5,
                task='modern_industrialization:digital_circuit',
                title='Digital Circuits',
                desc=tutorial(
                    "Craft &62 Digital Circuits&r.",
                    why="HV-tier brains for advanced machines and late multiblocks.",
                    steps=[
                        "Craft digital-tier components from electronic circuits and advanced parts (JEI).",
                        "Assemble &6Digital Circuits&r; keep the line automated.",
                    ],
                    tip="If circuit crafting is still manual, fix that before HV multiblocks.",
                    nxt="Chapter complete — push large boilers, blast furnaces, and HV machines next.",
                ),
                task_count=2,
                deps=[16],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Late',
            ),
        ],
    )
