"""12. Modern Industrialization quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import F_IRON


def chapter() -> Chapter:
    return Chapter(
        key='modern_industrialization',
        base=750,
        chapter_id='A20000000000000D',
        icon='modern_industrialization:forge_hammer',
        title='12. Modern Industrialization',
        subtitle='Steam age, steel, circuits, electric machines, and quarries',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=0.0,
                task='modern_industrialization:forge_hammer',
                title='Forge Hammer',
                desc=[
                    '&6Goal:&r Craft a Forge Hammer.',
                    '',
                    'MI starts with manual forging — plates, rods, and rings from ingots before machines take over.',
                    '',
                    '&7Tip:&r Pound a stack of iron plates now; bronze recipes will thank you.',
                ],
                links=require(F_IRON),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Modern Industrialization · Age 1',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0.0,
                task='modern_industrialization:bronze_ingot',
                title='Bronze Age',
                desc=[
                    '&6Goal:&r Craft &616 Bronze Ingots&r.',
                    '',
                    "Bronze unlocks the first steam machines and boilers — MI's true beginning.",
                    '',
                    '&7Tip:&r Tin + copper; Create mixing can help if you already have a brass factory.',
                ],
                task_count=16,
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Age 1',
            ),
            Quest(
                n=2,
                x=5.0,
                y=0.0,
                task='modern_industrialization:bronze_boiler',
                title='Bronze Boiler',
                desc=[
                    '&6Goal:&r Craft a Bronze Boiler.',
                    '',
                    'Burn fuel to make steam for bronze machines. Pipe steam with fluid pipes to machine hatches.',
                    '',
                    '&7Tip:&r Keep a water supply attached; dry boilers do nothing.',
                ],
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=3,
                x=7.5,
                y=0.0,
                task='modern_industrialization:bronze_furnace',
                title='Bronze Furnace',
                desc=[
                    '&6Goal:&r Craft a Bronze Furnace.',
                    '',
                    'Steam-powered smelting that outpaces a vanilla furnace once steam is stable.',
                    '',
                    '&7Tip:&r Item pipes move ores in and ingots out while you expand.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=4,
                x=10.0,
                y=0.0,
                task='modern_industrialization:bronze_compressor',
                title='Bronze Compressor',
                desc=[
                    '&6Goal:&r Craft a Bronze Compressor.',
                    '',
                    'Automate plates and other compressed parts so you can retire the Forge Hammer for bulk work.',
                    '',
                    '&7Tip:&r Steel age recipes still want lots of plates — overproduce.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=5,
                x=12.5,
                y=0.0,
                task='modern_industrialization:bronze_macerator',
                title='Bronze Macerator',
                desc=[
                    '&6Goal:&r Craft a Bronze Macerator.',
                    '',
                    "Crush ores and solids with steam power — MI's early dust line.",
                    '',
                    '&7Tip:&r Double-process ores when recipes allow for better yields.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steam',
            ),
            Quest(
                n=6,
                x=15.0,
                y=0.0,
                task='modern_industrialization:coke_oven',
                title='Coke Oven',
                desc=[
                    '&6Goal:&r Build a Coke Oven multiblock.',
                    '',
                    'Coal coke and creosote start the steel path. Bring fire-clay bricks and a valid hollow structure.',
                    '',
                    '&7Tip:&r Creosote is useful elsewhere — store it instead of voiding.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=7,
                x=17.5,
                y=0.0,
                task='modern_industrialization:steam_blast_furnace',
                title='Steam Blast Furnace',
                desc=[
                    '&6Goal:&r Build a Steam Blast Furnace.',
                    '',
                    'Blast iron with coke toward steel. This multiblock is the gate to Steel machines.',
                    '',
                    '&7Tip:&r Keep steam pressure high; starved SFBs crawl.',
                ],
                deps=[6],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=8,
                x=20.0,
                y=0.0,
                task='modern_industrialization:steel_ingot',
                title='Steel Stockpile',
                desc=[
                    '&6Goal:&r Produce &616 Steel Ingots&r.',
                    '',
                    'Steel unlocks stronger machines, better boilers, and the jump toward electricity.',
                    '',
                    '&7Tip:&r Batch plates and rods immediately after the first steel pour.',
                ],
                task_count=16,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=9,
                x=0.0,
                y=2.5,
                task='modern_industrialization:steel_boiler',
                title='Steel Boiler',
                desc=[
                    '&6Goal:&r Craft a Steel Boiler.',
                    '',
                    'Higher steam output for steel-tier machines and larger factories.',
                    '',
                    '&7Tip:&r Upgrade pipe networks when steam demand outruns bronze boilers.',
                ],
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Steel',
            ),
            Quest(
                n=10,
                x=2.5,
                y=2.5,
                task='modern_industrialization:analog_circuit',
                title='Analog Circuits',
                desc=[
                    '&6Goal:&r Craft &68 Analog Circuits&r.',
                    '',
                    "Circuits are MI's long progression spine — analog today, electronic/digital/quantum later.",
                    '',
                    '&7Tip:&r Automate circuit board ingredients before you feel the craft spam.',
                ],
                task_count=8,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=11,
                x=5.0,
                y=2.5,
                task='modern_industrialization:basic_machine_hull',
                title='Basic Machine Hull',
                desc=[
                    '&6Goal:&r Craft &64 Basic Machine Hulls&r.',
                    '',
                    'Electric machines are built on hulls. Basic hulls cover LV; advanced tiers follow.',
                    '',
                    '&7Tip:&r Motors, conveyors, and robot arms share parts with hull crafts — stock components.',
                ],
                task_count=4,
                deps=[10],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=12,
                x=7.5,
                y=2.5,
                task='modern_industrialization:motor',
                title='Motors',
                desc=[
                    '&6Goal:&r Craft &64 Motors&r.',
                    '',
                    'Motors drive electric machines and appear in countless component recipes.',
                    '',
                    '&7Tip:&r Tin cables and rubber often gate early motor crafts — check JEI.',
                ],
                task_count=4,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=13,
                x=10.0,
                y=2.5,
                task='modern_industrialization:electric_macerator',
                title='Electric Macerator',
                desc=[
                    '&6Goal:&r Craft an Electric Macerator.',
                    '',
                    'FE-powered crushing for serious ore throughput once LV power is online.',
                    '',
                    '&7Tip:&r Feed it with item pipes and pull dusts into an RS or Create line.',
                ],
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=14,
                x=12.5,
                y=2.5,
                task='modern_industrialization:lv_diesel_generator',
                title='LV Diesel Generator',
                desc=[
                    '&6Goal:&r Craft an LV Diesel Generator.',
                    '',
                    "Burn diesel/biodiesel for steady LV FE when steam turbines aren't enough.",
                    '',
                    '&7Tip:&r Oil drilling and distillation unlock proper fuel logistics later.',
                ],
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Electric',
            ),
            Quest(
                n=15,
                x=15.0,
                y=2.5,
                task='modern_industrialization:electronic_circuit',
                title='Electronic Circuits',
                desc=[
                    '&6Goal:&r Craft &64 Electronic Circuits&r.',
                    '',
                    'MV progression and better machines demand electronic circuits.',
                    '',
                    '&7Tip:&r Plan clean-room style crafting arrays — circuit crafting is a factory of its own.',
                ],
                task_count=4,
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Mid game',
            ),
            Quest(
                n=16,
                x=17.5,
                y=2.5,
                task='modern_industrialization:electric_quarry',
                title='Electric Quarry',
                desc=[
                    '&6Goal:&r Craft an Electric Quarry.',
                    '',
                    "Automated chunk mining with drill heads and power — MI's answer to bulk resource gathering.",
                    '',
                    '&7Tip:&r Clear the work area and supply drill heads before activating.',
                ],
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Modern Industrialization · Mid game',
            ),
            Quest(
                n=17,
                x=20.0,
                y=2.5,
                task='modern_industrialization:digital_circuit',
                title='Digital Circuits',
                desc=[
                    '&6Goal:&r Craft &62 Digital Circuits&r.',
                    '',
                    'HV-tier brains for advanced machines and late multiblocks.',
                    '',
                    '&7Tip:&r By now circuit automation should be hands-off; if not, fix that first.',
                ],
                task_count=2,
                deps=[16],
                rewards=[xp_levels(2)],
                subtitle='Modern Industrialization · Late',
            ),
        ],
    )

