"""6. Powah quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_BRASS
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='powah',
        base=424,
        chapter_id='0200000000000007',
        icon='powah:energizing_orb',
        title='6. Powah',
        subtitle='FE generation, energizing tiers, reactors, and wireless charging',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=7.0,
                task='powah:dielectric_paste',
                title='Dielectric Beginnings',
                desc=tutorial(
                    'Craft &616 Dielectric Paste&r.',
                    why='Powah uses dielectric paste, rods, and casings throughout every generator and storage tier.',
                    steps=[
                        'Check JEI for Dielectric Paste ingredients (clay, silicon/lava variants by pack recipe).',
                        'Craft a batch of 16+ paste.',
                        'Keep a drawer stocked — upgrading machines repeatedly consumes plenty.',
                    ],
                    tip='Cook or craft paste in batches before the generator rush.',
                    nxt='Build a Starter Furnator for first FE.',
                ),
                task_count=16,
                links=require(C_BRASS),
                rewards=[xp_levels(1)],
                subtitle='Powah · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=7.0,
                task='powah:furnator_starter',
                title='Starter Furnator',
                desc=tutorial(
                    'Craft a Starter Furnator.',
                    why='Burn solid fuel for your first independent FE supply — enough to bootstrap RS and the Energizing Orb.',
                    steps=[
                        'Place the Furnator near your early power room.',
                        'Open the GUI and insert coal/charcoal (or other solid fuel).',
                        'Set the energy output side, or connect a Powah energy cable to that face.',
                    ],
                    tip='A small Energy Cell next door absorbs spikes so the Furnator keeps burning.',
                    nxt='Run Starter Energy Cables.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Powah · Generation',
            ),
            Quest(
                n=2,
                x=5.0,
                y=7.0,
                task='powah:energy_cable_starter',
                title='Starter Energy Cables',
                desc=tutorial(
                    'Craft &616 Starter Energy Cables&r.',
                    why='Powah cables move FE between generators, cells, RS controllers, chargers, and Create electrical machines.',
                    steps=[
                        'Place cable from the Furnator toward machines that need FE.',
                        'Connect the RS Controller and any chargers on the same bus.',
                        'Upgrade cable tier later when transfer rate becomes the bottleneck.',
                    ],
                    tip='Color-code or separate buses if you mix low-tier and Nitro gear later.',
                    nxt='Add a Starter Energy Cell buffer.',
                ),
                task_count=16,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Powah · Transfer',
            ),
            Quest(
                n=3,
                x=7.5,
                y=7.0,
                task='powah:energy_cell_starter',
                title='Starter Energy Cell',
                desc=tutorial(
                    'Craft a Starter Energy Cell.',
                    why='Cells buffer generation so machines survive demand spikes and generators keep working between jobs.',
                    steps=[
                        'Place the Energy Cell between generation and the factory bus.',
                        'Cable generators into the cell, then cable the cell out to consumers.',
                        'Watch the fill bar under load — if it empties, add generation before more machines.',
                    ],
                    tip='Storage between generation and demand is the difference between brownouts and smooth FE.',
                    nxt='Add Thermo, Magmator, or Solar — then the Energizing Orb.',
                ),
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Powah · Storage',
            ),
            Quest(
                n=4,
                x=10.0,
                y=7.0,
                task='powah:thermo_generator_starter',
                title='Thermo Generator',
                desc=tutorial(
                    'Craft a Starter Thermo Generator.',
                    why='Passive, fuel-free FE from heat + water — great baseline under the factory.',
                    steps=[
                        'Place a hot block (magma, lava, blaze burner heat, etc.) under or against the generator per JEI rules.',
                        'Place the Thermo Generator above/on that heat source.',
                        'Supply water (sink, Create tank, or bucket loop) and cable FE out to your cell.',
                    ],
                    tip='Better heat sources improve output — upgrade the heat, not only the generator tier.',
                    nxt='Add Magmator and/or Solar for more generation.',
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=5,
                x=12.5,
                y=7.0,
                task='powah:magmator_starter',
                title='Magmator',
                desc=tutorial(
                    'Craft a Starter Magmator.',
                    why='Consumes lava for steady power — excellent with Create hose pulleys and train-delivered lava.',
                    steps=[
                        'Place the Magmator and cable it to your Energy Cell.',
                        'Buffer lava in a Create Fluid Tank or tank cart.',
                        'Pipe or hose-pulley lava into the Magmator fluid input, then confirm FE output.',
                    ],
                    tip='Never starve the Magmator of lava mid-spike — keep a tank buffer.',
                    nxt='Solar for daytime surplus, or jump to the Energizing Orb.',
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=6,
                x=15.0,
                y=7.0,
                task='powah:solar_panel_starter',
                title='Solar Panel',
                desc=tutorial(
                    'Craft a Starter Solar Panel.',
                    why='Free daytime power with clear sky access — combine sources rather than relying on one generator.',
                    steps=[
                        'Place Solar Panels on a roof or open sky platform (no opaque blocks above).',
                        'Cable them into your Energy Cell bus.',
                        'Let daytime surplus fill the cell for overnight use.',
                    ],
                    tip='Rain and night cut solar — keep Magmator/Thermo as baseline.',
                    nxt='Build the Energizing Orb when your buffer is healthy.',
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=7,
                x=17.5,
                y=7.0,
                task='powah:energizing_orb',
                title='Energizing Orb',
                desc=tutorial(
                    'Craft an Energizing Orb.',
                    why="The Orb turns ordinary materials into Powah's tier crystals when Energizing Rods supply enough FE.",
                    steps=[
                        'Place the Orb with clear air around it for rod line-of-sight.',
                        'Leave space on several sides for Energizing Rods to aim at the Orb.',
                        'Plan item I/O with Create funnels, arms, Pipez, or RS interfaces.',
                    ],
                    tip='The Orb itself does not pull FE — rods do. Build rods next.',
                    nxt='Craft Starter Energizing Rods and aim them at the Orb.',
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Energizing',
            ),
            Quest(
                n=8,
                x=20.0,
                y=7.0,
                task='powah:energizing_rod_starter',
                title='Energizing Rod',
                desc=tutorial(
                    'Craft &62 Starter Energizing Rods&r.',
                    why='Rods beam FE into the Orb — more and better rods finish recipes faster.',
                    steps=[
                        'Place rods with an unobstructed line of sight to the Energizing Orb.',
                        'Rotate/adjust each rod so it faces the Orb (check the beam in-world).',
                        'Cable every rod to the same buffered power network as your generators.',
                    ],
                    tip='If energizing stalls, add rods or upgrade generation — not just the Orb.',
                    nxt='Produce Energized Steel as your first tier material.',
                ),
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Powah · Energizing',
            ),
            Quest(
                n=9,
                x=22.5,
                y=7.0,
                task='powah:steel_energized',
                title='Energized Steel',
                desc=tutorial(
                    'Produce &68 Energized Steel&r.',
                    why='First energized material — unlocks Basic-tier generators, cables, cells, batteries, and wireless devices.',
                    steps=[
                        'Check JEI for the Energizing Orb recipe (iron/steel + FE cost).',
                        'Drop ingredients into the Orb (or funnel them in).',
                        'Wait for rods to finish the energize, then pull Energized Steel out.',
                    ],
                    tip='Encode the Orb recipe in Refined Storage once processing autocrafting is ready.',
                    nxt='Climb Blazing → Niotic → Spirited → Nitro crystals.',
                ),
                task_count=8,
                deps=[8],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Basic',
            ),
            Quest(
                n=10,
                x=25.0,
                y=7.0,
                task='powah:crystal_blazing',
                title='Blazing Crystal',
                desc=tutorial(
                    'Produce &68 Blazing Crystals&r.',
                    why='Blazing tier raises generation, capacity, and transfer with Nether materials.',
                    steps=[
                        'Gather blaze products (rods/powder) via farm or bulk processing.',
                        'Energize the JEI recipe in the Orb with enough rod power.',
                        'Upgrade key generators/cables/cells to Blazing when you need the rate.',
                    ],
                    tip='Keep blaze automated with a Create farm or bulk processing line.',
                    nxt='Niotic crystals for diamond-tier power.',
                ),
                task_count=8,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Blazing',
            ),
            Quest(
                n=11,
                x=0.0,
                y=9.5,
                task='powah:crystal_niotic',
                title='Niotic Crystal',
                desc=tutorial(
                    'Produce &68 Niotic Crystals&r.',
                    why='Niotic uses diamonds and marks the jump into serious factory-scale FE.',
                    steps=[
                        'Stock diamonds and check the Orb energizing cost in JEI.',
                        'Run the Orb only when your Energy Cell can afford the spike.',
                        'Upgrade generator, cell, and cable tiers together so one piece is not the bottleneck.',
                    ],
                    tip='Upgrade bottlenecks together: generator, cell, and cable throughput.',
                    nxt='Spirited crystals next.',
                ),
                task_count=8,
                deps=[10],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Niotic',
            ),
            Quest(
                n=12,
                x=2.5,
                y=9.5,
                task='powah:crystal_spirited',
                title='Spirited Crystal',
                desc=tutorial(
                    'Produce &68 Spirited Crystals&r.',
                    why='Emerald-heavy late-game step suited to large RS autocrafting networks.',
                    steps=[
                        'Gather emeralds (villager trades or mining) before starting the batch.',
                        'Energize in the Orb with upgraded rods and a fat FE buffer.',
                        'Only upgrade machines whose capacity or rate you actually need.',
                    ],
                    tip='Skip upgrading decorative chargers — spend Spirited on generation and transfer.',
                    nxt='Nitro crystals for top survival tier.',
                ),
                task_count=8,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Spirited',
            ),
            Quest(
                n=13,
                x=5.0,
                y=9.5,
                task='powah:crystal_nitro',
                title='Nitro Crystal',
                desc=tutorial(
                    'Produce &64 Nitro Crystals&r.',
                    why="Nitro is Powah's top survival tier — Nether Stars plus a major FE investment.",
                    steps=[
                        'Defeat the Wither (or stock Nether Stars) before committing.',
                        'Buffer a reactor-scale Energy Cell so energizing does not brown out the base.',
                        'Energize Nitro in the Orb, then craft Nitro generators/cables as needed.',
                    ],
                    tip='A buffered reactor network prevents energizing from starving RS autocrafting.',
                    nxt='Build toward a Nitro Reactor.',
                ),
                task_count=4,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Nitro',
            ),
            Quest(
                n=14,
                x=7.5,
                y=9.5,
                task='powah:uraninite',
                title='Uraninite Supply',
                desc=tutorial(
                    'Process &616 Uraninite&r.',
                    why='Uraninite fuels Powah reactors — stock it before assembling sustained reactor power.',
                    steps=[
                        'Mine uraninite ore (check JEI worldgen heights).',
                        'Smelt or energize it into usable Uraninite per JEI.',
                        'Also stock coal, redstone, water, and dry ice — reactors want supporting inputs.',
                    ],
                    tip='Automate ore → Uraninite before you rely on reactor uptime.',
                    nxt='Assemble a Starter Reactor.',
                ),
                task_count=16,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=15,
                x=10.0,
                y=9.5,
                task='powah:reactor_starter',
                title='Starter Reactor',
                desc=tutorial(
                    'Craft and assemble a Starter Reactor.',
                    why='Compact continuous FE from uraninite and supporting resources.',
                    steps=[
                        'Craft reactor blocks and place the multiblock/assembly per JEI or in-world guide.',
                        'Pipe in Uraninite plus required coolants/fuels before enabling full production.',
                        'Cable reactor output through an Energy Cell, not straight into hungry machines.',
                    ],
                    tip='Automate each consumable — a dry reactor is just expensive décor.',
                    nxt='Climb reactor tiers toward Nitro.',
                ),
                deps=[14],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=16,
                x=12.5,
                y=9.5,
                task='powah:reactor_nitro',
                title='Nitro Reactor',
                desc=tutorial(
                    'Upgrade all the way to a Nitro Reactor.',
                    why='Endgame Powah generator — enormous output for RS, jetpacks, and electric Create factories.',
                    steps=[
                        'Craft Nitro-tier reactor components with Nitro crystals and high-end materials.',
                        'Rebuild or upgrade the reactor assembly to Nitro.',
                        'Verify automated fuel/cooling and watch real FE/t into your buffer under full load.',
                    ],
                    tip='Huge theoretical output is useless without automated supply — monitor fuel first.',
                    nxt='Wireless FE via Ender Cells and Player Transmitters.',
                ),
                deps=[13],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=17,
                x=15.0,
                y=9.5,
                task='powah:ender_cell_starter',
                title='Ender Cell',
                desc=tutorial(
                    'Craft a Starter Ender Cell.',
                    why='Frequency-based wireless energy storage shared by linked Ender Gates.',
                    steps=[
                        'Place the Ender Cell and cable FE into it from your main generation.',
                        'Open the GUI and set a channel/frequency name for this network.',
                        'Use separate channels for public infrastructure vs critical machines.',
                    ],
                    tip='Name channels clearly — “Factory”, “Quarry”, “Dims” beats “1”.',
                    nxt='Attach Ender Gates at distant machines.',
                ),
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless network',
            ),
            Quest(
                n=18,
                x=17.5,
                y=9.5,
                task='powah:ender_gate_starter',
                title='Ender Gate',
                desc=tutorial(
                    'Craft &62 Starter Ender Gates&r.',
                    why='Cable-free FE access for distant machines through the selected Ender Cell channel.',
                    steps=[
                        'Place a gate on (or beside) a remote machine that needs power.',
                        'Set the gate to the same channel as your Ender Cell.',
                        'Confirm transfer; upgrade gate tier if the transfer limit caps your machine.',
                    ],
                    tip="A gate's transfer limit still depends on its tier — upgrade hungry endpoints.",
                    nxt='Add a Player Transmitter for on-person charging.',
                ),
                task_count=2,
                deps=[17],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless network',
            ),
            Quest(
                n=19,
                x=20.0,
                y=9.5,
                task='powah:player_transmitter_starter',
                title='Player Transmitter',
                desc=tutorial(
                    'Craft a Starter Player Transmitter.',
                    why='Wireless charging for carried equipment — especially Iron Jetpacks and Powah batteries.',
                    steps=[
                        'Place the Player Transmitter and cable it to a strong FE supply.',
                        'Bind yourself with the player binding card / GUI binding.',
                        'Carry a battery or jetpack and walk in range to confirm charge rate.',
                    ],
                    tip='No bind + no FE = a fancy lamp. Bind and power it before long trips.',
                    nxt='Craft a Portable Battery to test the link.',
                ),
                deps=[18],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Wireless charging',
            ),
            Quest(
                n=20,
                x=22.5,
                y=9.5,
                task='powah:battery_starter',
                title='Portable Battery',
                desc=tutorial(
                    'Craft a Starter Battery.',
                    why='Carries FE between jobs and is a simple test item for your Player Transmitter.',
                    steps=[
                        'Craft the battery and keep it in your inventory or Curios/hotbar as needed.',
                        'Stand near the Player Transmitter and watch charge climb.',
                        'Upgrade battery tier alongside wireless charging rate and equipment demand.',
                    ],
                    tip='Nitro batteries + Nitro transmitters keep jetpacks aloft all day.',
                    nxt='Powah chapter complete — feed Flux Networks or RS from this grid.',
                ),
                deps=[19],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless charging',
            ),
        ],
    )
