"""6. Powah quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_BRASS


def chapter() -> Chapter:
    return Chapter(
        key='powah',
        base=424,
        chapter_id='A200000000000007',
        icon='powah:energizing_orb',
        title='6. Powah',
        subtitle='FE generation, energizing tiers, reactors, and wireless charging',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=7.0,
                task='powah:dielectric_paste',
                title='Dielectric Beginnings',
                desc=[
                    '&6Goal:&r Craft &616 Dielectric Paste&r.',
                    '',
                    'Powah uses dielectric paste, rods, and casings throughout every generator and storage tier.',
                    '',
                    '&7Tip:&r Cook it in batches; upgrading machines repeatedly consumes plenty.',
                ],
                task_count=16,
                links=require(C_BRASS),
                rewards=[xp_levels(1)],
                subtitle='Powah · Materials',
            ),
            Quest(
                n=1,
                x=2.5,
                y=7.0,
                task='powah:furnator_starter',
                title='Starter Furnator',
                desc=[
                    '&6Goal:&r Craft a Starter Furnator.',
                    '',
                    'Burn solid fuel for your first independent FE supply—enough to bootstrap Refined Storage and the Energizing Orb.',
                    '',
                    '&7Tip:&r Set output sides in the GUI or connect an energy cable.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Powah · Generation',
            ),
            Quest(
                n=2,
                x=5.0,
                y=7.0,
                task='powah:energy_cable_starter',
                title='Starter Energy Cables',
                desc=[
                    '&6Goal:&r Craft &616 Starter Energy Cables&r.',
                    '',
                    'Powah cables move FE between generators, cells, RS controllers, chargers, and Create Crafts & Additions machines.',
                    '',
                    '&7Tip:&r Upgrade the cable tier when transfer rate becomes the bottleneck.',
                ],
                task_count=16,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Powah · Transfer',
            ),
            Quest(
                n=3,
                x=7.5,
                y=7.0,
                task='powah:energy_cell_starter',
                title='Starter Energy Cell',
                desc=[
                    '&6Goal:&r Craft a Starter Energy Cell.',
                    '',
                    'Cells buffer generation so machines survive demand spikes and generators can keep working between jobs.',
                    '',
                    '&7Tip:&r Place storage between generation and the factory bus.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Powah · Storage',
            ),
            Quest(
                n=4,
                x=10.0,
                y=7.0,
                task='powah:thermo_generator_starter',
                title='Thermo Generator',
                desc=[
                    '&6Goal:&r Craft a Starter Thermo Generator.',
                    '',
                    'Place it above a hot block and supply water for passive, fuel-free FE. Better heat sources improve output.',
                    '',
                    '&7Tip:&r Use a sink or pumped Create tank for reliable water supply.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=5,
                x=12.5,
                y=7.0,
                task='powah:magmator_starter',
                title='Magmator',
                desc=[
                    '&6Goal:&r Craft a Starter Magmator.',
                    '',
                    'A Magmator consumes lava for steady power—an excellent match for Create hose pulleys and train-delivered lava.',
                    '',
                    '&7Tip:&r Buffer lava in a Create Fluid Tank before feeding the generator.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=6,
                x=15.0,
                y=7.0,
                task='powah:solar_panel_starter',
                title='Solar Panel',
                desc=[
                    '&6Goal:&r Craft a Starter Solar Panel.',
                    '',
                    'Solar panels generate free daytime power with clear sky access. Combine sources rather than relying on one generator.',
                    '',
                    '&7Tip:&r Store daytime surplus in an Energy Cell for overnight use.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Powah · Generation',
            ),
            Quest(
                n=7,
                x=17.5,
                y=7.0,
                task='powah:energizing_orb',
                title='Energizing Orb',
                desc=[
                    '&6Goal:&r Craft an Energizing Orb.',
                    '',
                    "The Orb turns ordinary materials into Powah's tier crystals when Energizing Rods supply enough FE.",
                    '',
                    '&7Tip:&r Items can be inserted and removed with Create funnels, deployers, arms, Pipez, or RS interfaces.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Energizing',
            ),
            Quest(
                n=8,
                x=20.0,
                y=7.0,
                task='powah:energizing_rod_starter',
                title='Energizing Rod',
                desc=[
                    '&6Goal:&r Craft &62 Starter Energizing Rods&r.',
                    '',
                    'Point rods at the Orb with an unobstructed line of sight. More and better rods deliver recipes faster.',
                    '',
                    '&7Tip:&r Connect every rod to the same buffered power network.',
                ],
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Powah · Energizing',
            ),
            Quest(
                n=9,
                x=22.5,
                y=7.0,
                task='powah:steel_energized',
                title='Energized Steel',
                desc=[
                    '&6Goal:&r Produce &68 Energized Steel&r.',
                    '',
                    'This first energized material unlocks Basic-tier generators, cables, cells, batteries, and wireless devices.',
                    '',
                    '&7Tip:&r Encode the Orb recipe in Refined Storage once your processing autocrafting is ready.',
                ],
                task_count=8,
                deps=[8],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Basic',
            ),
            Quest(
                n=10,
                x=25.0,
                y=7.0,
                task='powah:crystal_blazing',
                title='Blazing Crystal',
                desc=[
                    '&6Goal:&r Produce &68 Blazing Crystals&r.',
                    '',
                    'Blazing tier raises generation, capacity, and transfer rates with Nether materials.',
                    '',
                    '&7Tip:&r Keep blaze products automated with a Create farm or bulk processing line.',
                ],
                task_count=8,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Blazing',
            ),
            Quest(
                n=11,
                x=0.0,
                y=9.5,
                task='powah:crystal_niotic',
                title='Niotic Crystal',
                desc=[
                    '&6Goal:&r Produce &68 Niotic Crystals&r.',
                    '',
                    'Niotic power uses diamonds and marks the jump into serious factory-scale FE.',
                    '',
                    '&7Tip:&r Upgrade bottlenecks together: generator, cell, and cable throughput.',
                ],
                task_count=8,
                deps=[10],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Niotic',
            ),
            Quest(
                n=12,
                x=2.5,
                y=9.5,
                task='powah:crystal_spirited',
                title='Spirited Crystal',
                desc=[
                    '&6Goal:&r Produce &68 Spirited Crystals&r.',
                    '',
                    'Spirited tier is an emerald-heavy late-game step suited to large RS autocrafting networks.',
                    '',
                    '&7Tip:&r Only upgrade machines whose capacity or rate you actually need.',
                ],
                task_count=8,
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Spirited',
            ),
            Quest(
                n=13,
                x=5.0,
                y=9.5,
                task='powah:crystal_nitro',
                title='Nitro Crystal',
                desc=[
                    '&6Goal:&r Produce &64 Nitro Crystals&r.',
                    '',
                    "Nitro is Powah's top survival tier and requires Nether Stars plus a major FE investment.",
                    '',
                    '&7Tip:&r A buffered reactor network prevents the energizing operation from starving your base.',
                ],
                task_count=4,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Powah · Tier: Nitro',
            ),
            Quest(
                n=14,
                x=7.5,
                y=9.5,
                task='powah:uraninite',
                title='Uraninite Supply',
                desc=[
                    '&6Goal:&r Process &616 Uraninite&r.',
                    '',
                    'Uraninite fuels Powah reactors. Mine its ore and energize or smelt it before building sustained reactor power.',
                    '',
                    '&7Tip:&r Stock coal, redstone, water, and dry ice too; reactors perform best with all required inputs.',
                ],
                task_count=16,
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=15,
                x=10.0,
                y=9.5,
                task='powah:reactor_starter',
                title='Starter Reactor',
                desc=[
                    '&6Goal:&r Craft and assemble a Starter Reactor.',
                    '',
                    'Reactors compactly generate continuous FE from uraninite and supporting resources. Configure inputs before enabling full production.',
                    '',
                    '&7Tip:&r Automate each consumable and send output through an Energy Cell.',
                ],
                deps=[14],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=16,
                x=12.5,
                y=9.5,
                task='powah:reactor_nitro',
                title='Nitro Reactor',
                desc=[
                    '&6Goal:&r Upgrade all the way to a Nitro Reactor.',
                    '',
                    'This is the endgame Powah generator: enormous output for RS autocrafting, jetpacks, and electrically driven Create factories.',
                    '',
                    '&7Tip:&r Monitor fuel and cooling; huge theoretical output is useless without automated supply.',
                ],
                deps=[13],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Reactors',
            ),
            Quest(
                n=17,
                x=15.0,
                y=9.5,
                task='powah:ender_cell_starter',
                title='Ender Cell',
                desc=[
                    '&6Goal:&r Craft a Starter Ender Cell.',
                    '',
                    'Ender Cells store power in a frequency-based wireless network shared by linked Ender Gates.',
                    '',
                    '&7Tip:&r Use separate channels for public infrastructure and critical machines.',
                ],
                deps=[9],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless network',
            ),
            Quest(
                n=18,
                x=17.5,
                y=9.5,
                task='powah:ender_gate_starter',
                title='Ender Gate',
                desc=[
                    '&6Goal:&r Craft &62 Starter Ender Gates&r.',
                    '',
                    'Attach gates to distant machines for cable-free FE access through the selected Ender Cell channel.',
                    '',
                    "&7Tip:&r A gate's transfer limit still depends on its tier.",
                ],
                task_count=2,
                deps=[17],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless network',
            ),
            Quest(
                n=19,
                x=20.0,
                y=9.5,
                task='powah:player_transmitter_starter',
                title='Player Transmitter',
                desc=[
                    '&6Goal:&r Craft a Starter Player Transmitter.',
                    '',
                    'Player Transmitters wirelessly charge carried equipment—especially Iron Jetpacks and Powah batteries.',
                    '',
                    '&7Tip:&r Bind yourself with the correct card and keep the transmitter supplied with FE.',
                ],
                deps=[18],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Powah · Wireless charging',
            ),
            Quest(
                n=20,
                x=22.5,
                y=9.5,
                task='powah:battery_starter',
                title='Portable Battery',
                desc=[
                    '&6Goal:&r Craft a Starter Battery.',
                    '',
                    'A battery carries FE between jobs and provides a simple test item for your Player Transmitter.',
                    '',
                    '&7Tip:&r Upgrade its tier alongside your wireless charging rate and equipment demand.',
                ],
                deps=[19],
                rewards=[xp_levels(2)],
                subtitle='Powah · Wireless charging',
            ),
        ],
    )

