"""5. Refined Storage quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_PRECISION


def chapter() -> Chapter:
    return Chapter(
        key='refined_storage',
        base=324,
        chapter_id='A200000000000006',
        icon='refinedstorage:controller',
        title='5. Refined Storage',
        subtitle='Digital item and fluid storage, Create integration, and autocrafting',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=7.0,
                task='refinedstorage:quartz_enriched_iron',
                title='Quartz-Enriched Iron',
                desc=[
                    '&6Goal:&r Craft &616 Quartz-Enriched Iron&r.',
                    '',
                    "This is Refined Storage's base material. Keep quartz, iron, redstone, and silicon processing close to your factory.",
                    '',
                    '&7Tip:&r Batch the processor ingredients now; every network device uses them.',
                ],
                task_count=16,
                links=require(C_PRECISION),
                rewards=[xp_levels(1)],
                subtitle='Core',
            ),
            Quest(
                n=1,
                x=2.5,
                y=7.0,
                task='refinedstorage:controller',
                title='Network Controller',
                desc=[
                    '&6Goal:&r Craft and power a Refined Storage Controller.',
                    '',
                    'The Controller is the network heart. Feed it FE from a Create Crafts & Additions alternator, diesel setup, or another generator.',
                    '',
                    '&7Tip:&r A lit controller means the network has power; every connected device consumes some FE.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Core',
            ),
            Quest(
                n=2,
                x=5.0,
                y=7.0,
                task='refinedstorage:cable',
                title='Run the Network',
                desc=[
                    '&6Goal:&r Craft &632 Refined Storage cables&r.',
                    '',
                    'Cables join every RS device into one network. Route them behind walls and under Create machines for clean service corridors.',
                    '',
                    '&7Tip:&r Devices can touch directly; use cable only where you need distance.',
                ],
                task_count=32,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Core',
            ),
            Quest(
                n=3,
                x=7.5,
                y=7.0,
                task='refinedstorage:disk_drive',
                title='Disk Drive',
                desc=[
                    '&6Goal:&r Craft a Disk Drive and connect it to the Controller.',
                    '',
                    'A drive holds up to eight item or fluid disks. It provides bays, not capacity—the disks do that.',
                    '',
                    '&7Tip:&r Keep spare bays for fluid and Extra Disks upgrades.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Items',
            ),
            Quest(
                n=4,
                x=10.0,
                y=7.0,
                task='refinedstorage:16k_storage_disk',
                title='16K Item Disk',
                desc=[
                    '&6Goal:&r Craft a 16K Item Storage Disk and place it in the drive.',
                    '',
                    'Item disks store many item types without chest-slot juggling. Upgrade through 64K before entering addon capacities.',
                    '',
                    '&7Tip:&r Use a Disk Manipulator later to migrate contents between tiers safely.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Items',
            ),
            Quest(
                n=5,
                x=12.5,
                y=7.0,
                task='refinedstorage:grid',
                title='Storage Grid',
                desc=[
                    '&6Goal:&r Craft a Grid and connect it to the network.',
                    '',
                    'The Grid is the unified view of every disk and attached external inventory. Search, insert, and extract from one screen.',
                    '',
                    '&7Tip:&r Build the Crafting Grid next so stored ingredients are usable directly.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Access',
            ),
            Quest(
                n=6,
                x=15.0,
                y=7.0,
                task='refinedstorage:crafting_grid',
                title='Crafting Grid + JEI',
                desc=[
                    '&6Goal:&r Upgrade to a Crafting Grid.',
                    '',
                    'The official RS JEI integration lets JEI transfer recipe ingredients into this grid from network storage.',
                    '',
                    '&7Tip:&r Open a JEI recipe and press the transfer button; missing ingredients stay highlighted.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='JEI addon',
            ),
            Quest(
                n=7,
                x=17.5,
                y=7.0,
                task='refinedstorage:4096b_fluid_storage_disk',
                title='Fluid Storage',
                desc=[
                    '&6Goal:&r Craft a 4096B Fluid Storage Disk.',
                    '',
                    'RS 2 shows items and fluids in the same Grid. Insert filled containers, or move fluids with importers and exporters.',
                    '',
                    '&7Tip:&r One bucket equals one bucket of disk capacity; reserve space before automating bulk liquids.',
                ],
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Fluids',
            ),
            Quest(
                n=8,
                x=20.0,
                y=7.0,
                task='refinedstorage:external_storage',
                title='Expose Create Storage',
                desc=[
                    '&6Goal:&r Craft &62 External Storage devices&r.',
                    '',
                    'Attach one to a Create Item Vault, Functional Storage controller, chest, or fluid tank so RS can use it without copying contents onto disks.',
                    '',
                    '&7Tip:&r Set priorities: high-priority drawers receive bulk items before general-purpose disks.',
                ],
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=9,
                x=22.5,
                y=7.0,
                task='refinedstorage:importer',
                title='Import Factory Output',
                desc=[
                    '&6Goal:&r Craft &62 Importers&r.',
                    '',
                    'An Importer pulls items or fluids from an adjacent inventory or tank into RS—ideal on the output buffer of a Create processing line.',
                    '',
                    '&7Tip:&r Add speed and stack upgrades for high-throughput crushing or washing lines.',
                ],
                task_count=2,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=10,
                x=25.0,
                y=7.0,
                task='refinedstorage:exporter',
                title='Export Ingredients',
                desc=[
                    '&6Goal:&r Craft &62 Exporters&r.',
                    '',
                    'An Exporter keeps selected items or fluids supplied to an adjacent machine, basin buffer, deployer chest, or Create tank.',
                    '',
                    '&7Tip:&r Use regulator upgrades when a machine should hold an exact stock instead of being flooded.',
                ],
                task_count=2,
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=11,
                x=0.0,
                y=9.5,
                task='refinedstorage:interface',
                title='Factory Interface',
                desc=[
                    '&6Goal:&r Craft &62 Interfaces&r.',
                    '',
                    'Interfaces expose filtered stock to outside automation. Create funnels, chutes, arms, belts, and Pipez can interact with their slots.',
                    '',
                    '&7Tip:&r Use interfaces as clean hand-off points between the digital network and physical factory logistics.',
                ],
                task_count=2,
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Outside automation',
            ),
            Quest(
                n=12,
                x=2.5,
                y=9.5,
                task='refinedstorage:pattern_grid',
                title='Pattern Grid',
                desc=[
                    '&6Goal:&r Craft a Pattern Grid.',
                    '',
                    'Encode crafting recipes and processing recipes onto patterns. Processing patterns describe inputs sent out and outputs expected back.',
                    '',
                    '&7Tip:&r Use processing patterns for Create crushing, mixing, pressing, deploying, and sequenced assembly.',
                ],
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Autocrafting',
            ),
            Quest(
                n=13,
                x=5.0,
                y=9.5,
                task='refinedstorage:pattern',
                title='Encode Patterns',
                desc=[
                    '&6Goal:&r Craft &68 blank Patterns&r and encode useful recipes.',
                    '',
                    'Start with common components, then encode Create processes. Put crafting patterns and processing patterns into the right autocrafters.',
                    '',
                    '&7Tip:&r Test one processing step before chaining a long production request.',
                ],
                task_count=8,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Autocrafting',
            ),
            Quest(
                n=14,
                x=7.5,
                y=9.5,
                task='refinedstorage:autocrafter',
                title='Autocrafter',
                desc=[
                    '&6Goal:&r Craft &62 Autocrafters&r.',
                    '',
                    'Autocrafters execute patterns. Point processing outputs toward an Interface so RS can detect returned products and finish the job.',
                    '',
                    '&7Tip:&r The Autocrafter Manager helps organize large walls of patterns.',
                ],
                task_count=2,
                deps=[13],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Autocrafting',
            ),
            Quest(
                n=15,
                x=10.0,
                y=9.5,
                task='refinedstorage:wireless_transmitter',
                title='Wireless Transmitter',
                desc=[
                    '&6Goal:&r Craft a Wireless Transmitter.',
                    '',
                    'Connect it to the network and install range upgrades to reach across your base.',
                    '',
                    '&7Tip:&r Wireless access still consumes network power and has a configured range.',
                ],
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Wireless',
            ),
            Quest(
                n=16,
                x=12.5,
                y=9.5,
                task='refinedstorage:wireless_grid',
                title='Wireless Grid + Curios',
                desc=[
                    '&6Goal:&r Craft and link a Wireless Grid.',
                    '',
                    'The official Curios integration adds dedicated RS slots, letting a linked portable or wireless grid travel equipped outside your inventory.',
                    '',
                    '&7Tip:&r Use the linking tool on the network, charge the grid, then equip it in its Curios slot.',
                ],
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Curios addon',
            ),
            Quest(
                n=17,
                x=15.0,
                y=9.5,
                task='extradisks:1024k_item_storage_disk',
                title='Extra Disks: 1024K',
                desc=[
                    '&6Goal:&r Craft a 1024K Item Storage Disk from Extra Disks.',
                    '',
                    'Extra Disks extends RS with enormous item and fluid tiers for mature factories. Upgrade gradually instead of crafting infinite storage early.',
                    '',
                    '&7Tip:&r Withering processors gate the highest tiers behind Nether progression.',
                ],
                deps=[16],
                rewards=[xp_levels(2)],
                subtitle='Extra Disks addon',
            ),
            Quest(
                n=18,
                x=17.5,
                y=9.5,
                task='extrastorage:advanced_importer',
                title='Advanced Importer',
                desc=[
                    '&6Goal:&r Craft an ExtraStorage Advanced Importer.',
                    '',
                    'Its larger filter and higher throughput suit multi-output Create farms and processing arrays.',
                    '',
                    '&7Tip:&r Filter explicitly so valuable outputs never loop back into the wrong line.',
                ],
                deps=[17],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=19,
                x=20.0,
                y=9.5,
                task='extrastorage:advanced_exporter',
                title='Advanced Exporter',
                desc=[
                    '&6Goal:&r Craft an ExtraStorage Advanced Exporter.',
                    '',
                    'Use the expanded filter to stock several ingredients at a shared factory input buffer.',
                    '',
                    '&7Tip:&r Pair it with a Create belt or mechanical arm to distribute ingredients physically.',
                ],
                deps=[18],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=20,
                x=22.5,
                y=9.5,
                task='extrastorage:netherite_crafter',
                title='Netherite Crafter',
                desc=[
                    "&6Goal:&r Craft ExtraStorage's Netherite Crafter.",
                    '',
                    'This top-tier crafter holds more patterns and processes requests faster—ideal for a dense late-game pattern hall.',
                    '',
                    '&7Tip:&r Spread processing recipes across crafters when several Create lines can run in parallel.',
                ],
                deps=[19],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=21,
                x=25.0,
                y=9.5,
                task='extrastorage:disk_1048576b_fluid',
                title='Million-Bucket Fluid Disk',
                desc=[
                    "&6Goal:&r Craft ExtraStorage's 1,048,576B Fluid Storage Disk.",
                    '',
                    'Use this endgame tank for diesel products, liquid experience, chocolate, honey, lava, or any other factory-scale fluid.',
                    '',
                    '&7Tip:&r External Storage is still better when you want the fluid visibly stored in Create tanks.',
                ],
                deps=[20],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='ExtraStorage addon',
            ),
        ],
    )

