"""5. Refined Storage quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import C_PRECISION
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='refined_storage',
        base=324,
        chapter_id='0200000000000006',
        icon='refinedstorage:controller',
        title='5. Refined Storage',
        subtitle='Digital item and fluid storage, Create integration, and autocrafting',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=7.0,
                task='refinedstorage:quartz_enriched_iron',
                title='Quartz-Enriched Iron',
                desc=tutorial(
                    'Craft &616 Quartz-Enriched Iron&r.',
                    why="This is Refined Storage's base metal — processors, cables, and nearly every network block consume it.",
                    steps=[
                        'Gather iron, quartz, and redstone (and silicon once you need processors).',
                        'Craft Quartz-Enriched Iron in a crafting table or Create mechanical crafter.',
                        'Stockpile a chest or drawer of it before the machine rush.',
                    ],
                    tip='Batch processor ingredients now; every network device uses them.',
                    nxt='Craft and power a Controller.',
                ),
                task_count=16,
                links=require(C_PRECISION),
                rewards=[xp_levels(1)],
                subtitle='Core',
            ),
            Quest(
                n=1,
                x=2.5,
                y=7.0,
                task='refinedstorage:controller',
                title='Network Controller',
                desc=tutorial(
                    'Craft and power a Refined Storage Controller.',
                    why='The Controller is the network heart — no power, no storage, no grids.',
                    steps=[
                        'Place the Controller where you want the digital hub.',
                        'Feed it FE from a Create Crafts & Additions alternator, diesel setup, Powah, or another generator.',
                        'Confirm the Controller lights up; that means the network is online.',
                    ],
                    tip='Every connected device draws some FE — buffer power before growing the network.',
                    nxt='Run cables to expand the network.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='Core',
            ),
            Quest(
                n=2,
                x=5.0,
                y=7.0,
                task='refinedstorage:cable',
                title='Run the Network',
                desc=tutorial(
                    'Craft &632 Refined Storage cables&r.',
                    why='Cables join every RS device into one network across your factory.',
                    steps=[
                        'Place cable from the Controller toward machine and storage rooms.',
                        'Route behind walls or under Create lines for clean service corridors.',
                        'Touch devices to cable (or to each other) so they join the same network.',
                    ],
                    tip='Devices can touch directly; use cable only where you need distance.',
                    nxt='Add a Disk Drive for storage bays.',
                ),
                task_count=32,
                deps=[1],
                rewards=[xp_levels(1)],
                subtitle='Core',
            ),
            Quest(
                n=3,
                x=7.5,
                y=7.0,
                task='refinedstorage:disk_drive',
                title='Disk Drive',
                desc=tutorial(
                    'Craft a Disk Drive and connect it to the Controller.',
                    why='A drive holds up to eight item or fluid disks — it provides bays, not capacity.',
                    steps=[
                        'Place the Disk Drive adjacent to cable (or touching the Controller).',
                        'Open the drive GUI and confirm it shows as part of the network.',
                        'Leave spare bays for fluid disks and future upgrades.',
                    ],
                    tip='Keep empty bays ready for Extra Disks tiers later.',
                    nxt='Craft a 16K Item Storage Disk.',
                ),
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='Items',
            ),
            Quest(
                n=4,
                x=10.0,
                y=7.0,
                task='refinedstorage:16k_storage_disk',
                title='16K Item Disk',
                desc=tutorial(
                    'Craft a 16K Item Storage Disk and place it in the drive.',
                    why='Item disks store many item types without chest-slot juggling.',
                    steps=[
                        'Craft the 16K Item Storage Disk (parts → housing → disk).',
                        'Put the finished disk into an empty Disk Drive bay.',
                        'Insert a few test items through a Grid (next) or by dropping into network importers later.',
                    ],
                    tip='Use a Disk Manipulator later to migrate contents between tiers safely.',
                    nxt='Add a Storage Grid to browse the network.',
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='Items',
            ),
            Quest(
                n=5,
                x=12.5,
                y=7.0,
                task='refinedstorage:grid',
                title='Storage Grid',
                desc=tutorial(
                    'Craft a Grid and connect it to the network.',
                    why='The Grid is the unified view of every disk and attached external inventory.',
                    steps=[
                        'Place the Grid on the RS cable network.',
                        'Open it and search for an item you inserted onto disks.',
                        'Pull and push items from this one screen instead of opening chests.',
                    ],
                    tip='Build the Crafting Grid next so stored ingredients are usable directly.',
                    nxt='Upgrade to a Crafting Grid.',
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                subtitle='Access',
            ),
            Quest(
                n=6,
                x=15.0,
                y=7.0,
                task='refinedstorage:crafting_grid',
                title='Crafting Grid + JEI',
                desc=tutorial(
                    'Upgrade to a Crafting Grid.',
                    why='Craft from network storage in place — JEI can transfer recipes into this grid.',
                    steps=[
                        'Replace or place a Crafting Grid on the network.',
                        'Open a JEI recipe and use the transfer button to pull ingredients from RS.',
                        'Craft the result; leftovers return to network storage.',
                    ],
                    tip='Missing ingredients stay highlighted after transfer — fill those first.',
                    nxt='Add fluid storage for liquids.',
                ),
                deps=[5],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='JEI addon',
            ),
            Quest(
                n=7,
                x=17.5,
                y=7.0,
                task='refinedstorage:4096b_fluid_storage_disk',
                title='Fluid Storage',
                desc=tutorial(
                    'Craft a 4096B Fluid Storage Disk.',
                    why='RS 2 shows items and fluids in the same Grid — one place for buckets and tanks.',
                    steps=[
                        'Craft the fluid disk and slot it into a free Disk Drive bay.',
                        'Insert filled buckets/containers via the Grid, or pipe fluids with importers later.',
                        'Check the Grid fluid tab to confirm capacity.',
                    ],
                    tip='One bucket equals one bucket of disk capacity; reserve space before automating bulk liquids.',
                    nxt='Expose Create vaults with External Storage.',
                ),
                deps=[6],
                rewards=[xp_levels(1)],
                subtitle='Fluids',
            ),
            Quest(
                n=8,
                x=20.0,
                y=7.0,
                task='refinedstorage:external_storage',
                title='Expose Create Storage',
                desc=tutorial(
                    'Craft &62 External Storage devices&r.',
                    why='Attach RS to Create Item Vaults, Functional Storage, chests, or tanks without copying contents onto disks.',
                    steps=[
                        'Place External Storage against the inventory or tank face you want to expose.',
                        'Connect it to the RS cable network.',
                        'Set priority so high-priority drawers receive bulk items before general disks.',
                    ],
                    tip='Use External Storage for visible Create tanks; keep disks for mixed junk.',
                    nxt='Import factory output into the network.',
                ),
                task_count=2,
                deps=[7],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=9,
                x=22.5,
                y=7.0,
                task='refinedstorage:importer',
                title='Import Factory Output',
                desc=tutorial(
                    'Craft &62 Importers&r.',
                    why='Importers pull items or fluids from an adjacent inventory or tank into RS.',
                    steps=[
                        'Place an Importer on the output buffer of a Create line (chest, basin, tank).',
                        'Connect it to cable and open the filter GUI.',
                        'Whitelist outputs you want sucked in; add speed/stack upgrades for high throughput.',
                    ],
                    tip='Filter trash and loop materials so your network stays clean.',
                    nxt='Export ingredients back to machines.',
                ),
                task_count=2,
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=10,
                x=25.0,
                y=7.0,
                task='refinedstorage:exporter',
                title='Export Ingredients',
                desc=tutorial(
                    'Craft &62 Exporters&r.',
                    why='Exporters keep selected items or fluids supplied to an adjacent machine or buffer.',
                    steps=[
                        'Place an Exporter on a machine, basin chest, deployer buffer, or Create tank.',
                        'Configure the filter with the ingredients that machine needs.',
                        'Add a regulator upgrade when you need an exact stock level instead of flooding.',
                    ],
                    tip='Pair exporters with Create funnels/arms for physical distribution.',
                    nxt='Add Interfaces for outside automation hand-offs.',
                ),
                task_count=2,
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='Create integration',
            ),
            Quest(
                n=11,
                x=0.0,
                y=9.5,
                task='refinedstorage:interface',
                title='Factory Interface',
                desc=tutorial(
                    'Craft &62 Interfaces&r.',
                    why='Interfaces expose filtered stock to Create funnels, chutes, arms, belts, and Pipez.',
                    steps=[
                        'Place an Interface on the cable network at a factory hand-off point.',
                        'Configure export slots with items the physical line should pull.',
                        'Point Create logistics at the Interface instead of digging into disk drives.',
                    ],
                    tip='Interfaces are the clean boundary between digital RS and physical Create logistics.',
                    nxt='Unlock autocrafting with a Pattern Grid.',
                ),
                task_count=2,
                deps=[10],
                rewards=[xp_levels(1)],
                subtitle='Outside automation',
            ),
            Quest(
                n=12,
                x=2.5,
                y=9.5,
                task='refinedstorage:pattern_grid',
                title='Pattern Grid',
                desc=tutorial(
                    'Craft a Pattern Grid.',
                    why='Encode crafting and processing recipes onto patterns for autocrafting.',
                    steps=[
                        'Place the Pattern Grid on the network.',
                        'Choose crafting mode for table recipes, or processing mode for machine steps.',
                        'For Create: set inputs that leave the network and outputs you expect back.',
                    ],
                    tip='Use processing patterns for crushing, mixing, pressing, deploying, and sequenced assembly.',
                    nxt='Craft blank Patterns and encode recipes.',
                ),
                deps=[11],
                rewards=[xp_levels(2)],
                subtitle='Autocrafting',
            ),
            Quest(
                n=13,
                x=5.0,
                y=9.5,
                task='refinedstorage:pattern',
                title='Encode Patterns',
                desc=tutorial(
                    'Craft &68 blank Patterns&r and encode useful recipes.',
                    why='Patterns are the recipes Autocrafters execute — start simple, then chain Create steps.',
                    steps=[
                        'Craft blank Patterns and open the Pattern Grid.',
                        'Encode common components first (gears, sheets, casings).',
                        'Encode one Create processing step and test it before chaining a long request.',
                    ],
                    tip='Put crafting patterns and processing patterns into the right Autocrafters.',
                    nxt='Build Autocrafters to run those patterns.',
                ),
                task_count=8,
                deps=[12],
                rewards=[xp_levels(2)],
                subtitle='Autocrafting',
            ),
            Quest(
                n=14,
                x=7.5,
                y=9.5,
                task='refinedstorage:autocrafter',
                title='Autocrafter',
                desc=tutorial(
                    'Craft &62 Autocrafters&r.',
                    why='Autocrafters execute patterns — crafting in-world or sending processing jobs to machines.',
                    steps=[
                        'Place Autocrafters on the network and insert encoded patterns.',
                        'For processing: Autocrafter pushes inputs out; route products back via an Interface or Importer.',
                        'Request a craft from the Grid and watch the job complete end-to-end.',
                    ],
                    tip='The Autocrafter Manager helps organize large walls of patterns.',
                    nxt='Go wireless with a Wireless Transmitter.',
                ),
                task_count=2,
                deps=[13],
                rewards=[xp_levels(2)],
                size=1.5,
                subtitle='Autocrafting',
            ),
            Quest(
                n=15,
                x=10.0,
                y=9.5,
                task='refinedstorage:wireless_transmitter',
                title='Wireless Transmitter',
                desc=tutorial(
                    'Craft a Wireless Transmitter.',
                    why='Extends network access across your base for wireless grids and tools.',
                    steps=[
                        'Place the Wireless Transmitter on the cable network.',
                        'Install range upgrades until coverage reaches your work areas.',
                        'Keep the network powered — wireless still draws FE.',
                    ],
                    tip='Coverage is a sphere from the transmitter; raise it for multi-floor bases.',
                    nxt='Link a Wireless Grid (Curios slot friendly).',
                ),
                deps=[14],
                rewards=[xp_levels(2)],
                subtitle='Wireless',
            ),
            Quest(
                n=16,
                x=12.5,
                y=9.5,
                task='refinedstorage:wireless_grid',
                title='Wireless Grid + Curios',
                desc=tutorial(
                    'Craft and link a Wireless Grid.',
                    why='Portable network access — Curios adds a dedicated RS slot so it can travel equipped.',
                    steps=[
                        'Craft the Wireless Grid and a Network/Security Card if required by your version.',
                        'Link it to your network (use the linking tool on the Controller or transmitter).',
                        'Charge the grid, then equip it in its Curios slot for on-the-go access.',
                    ],
                    tip='Stay inside transmitter range or the wireless grid goes dark.',
                    nxt='Scale capacity with Extra Disks.',
                ),
                deps=[15],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Curios addon',
            ),
            Quest(
                n=17,
                x=15.0,
                y=9.5,
                task='extradisks:1024k_item_storage_disk',
                title='Extra Disks: 1024K',
                desc=tutorial(
                    'Craft a 1024K Item Storage Disk from Extra Disks.',
                    why='Extra Disks adds enormous item and fluid tiers for mature factories.',
                    steps=[
                        'Check JEI for the Extra Disks crafting chain (advanced parts + processors).',
                        'Craft the 1024K disk and insert it into a Disk Drive bay.',
                        'Migrate bulk stock from smaller disks with a Disk Manipulator when ready.',
                    ],
                    tip='Withering processors gate the highest tiers behind Nether progression.',
                    nxt='Speed up logistics with Advanced Importers.',
                ),
                deps=[16],
                rewards=[xp_levels(2)],
                subtitle='Extra Disks addon',
            ),
            Quest(
                n=18,
                x=17.5,
                y=9.5,
                task='extrastorage:advanced_importer',
                title='Advanced Importer',
                desc=tutorial(
                    "Craft ExtraStorage's Advanced Importer.",
                    why='Larger filters and higher throughput suit multi-output Create farms.',
                    steps=[
                        'Replace a busy Importer with the Advanced Importer on the output buffer.',
                        'Fill the expanded filter with every product that line produces.',
                        'Add upgrades and confirm nothing valuable loops back into the wrong chest.',
                    ],
                    tip='Filter explicitly — advanced speed without filters will vacuum everything.',
                    nxt='Stock inputs with an Advanced Exporter.',
                ),
                deps=[17],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=19,
                x=20.0,
                y=9.5,
                task='extrastorage:advanced_exporter',
                title='Advanced Exporter',
                desc=tutorial(
                    "Craft ExtraStorage's Advanced Exporter.",
                    why='Expanded filters stock several ingredients at a shared factory input buffer.',
                    steps=[
                        'Place the Advanced Exporter on a shared Create input chest or basin buffer.',
                        'List every ingredient that buffer should keep stocked.',
                        'Use a belt or mechanical arm to distribute those items to machines.',
                    ],
                    tip='Regulator upgrades prevent overfilling shared buffers.',
                    nxt='Upgrade autocrafting with a Netherite Crafter.',
                ),
                deps=[18],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=20,
                x=22.5,
                y=9.5,
                task='extrastorage:netherite_crafter',
                title='Netherite Crafter',
                desc=tutorial(
                    "Craft ExtraStorage's Netherite Crafter.",
                    why='Top-tier crafter: more patterns and faster requests for a dense pattern hall.',
                    steps=[
                        'Place the Netherite Crafter on the autocrafting wall.',
                        'Move high-traffic patterns into it from slower Autocrafters.',
                        'Spread processing recipes across crafters when several Create lines can run in parallel.',
                    ],
                    tip='Parallel Create lines need parallel crafters — one block is not a whole factory.',
                    nxt='Cap fluid storage with a million-bucket disk.',
                ),
                deps=[19],
                rewards=[xp_levels(2)],
                subtitle='ExtraStorage addon',
            ),
            Quest(
                n=21,
                x=25.0,
                y=9.5,
                task='extrastorage:disk_1048576b_fluid',
                title='Million-Bucket Fluid Disk',
                desc=tutorial(
                    "Craft ExtraStorage's 1,048,576B Fluid Storage Disk.",
                    why='Endgame tank capacity for diesel, liquid XP, chocolate, honey, lava, and more.',
                    steps=[
                        'Craft the mega fluid disk via ExtraStorage recipes.',
                        'Install it in a Disk Drive and verify the Grid fluid capacity.',
                        'Point fluid importers/exporters at factory liquids you want digitized.',
                    ],
                    tip='External Storage is still better when you want fluids visibly stored in Create tanks.',
                    nxt='Your RS hub is complete — grow patterns and power as the factory expands.',
                ),
                deps=[20],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='ExtraStorage addon',
            ),
        ],
    )
