"""7. RFTools quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import POWAH_ENERGY_CELL


def chapter() -> Chapter:
    return Chapter(
        key='rftools',
        base=445,
        chapter_id='A200000000000008',
        icon='rftoolsbase:machine_frame',
        title='7. RFTools',
        subtitle='Power, automation, storage scanning, teleportation, and dimensions',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=12.5,
                task='rftoolsbase:machine_frame',
                title='RFTools Framework',
                desc=[
                    '&6Goal:&r Craft &64 RFTools Machine Frames&r.',
                    '',
                    'Machine Frames are the common chassis for the entire RFTools suite.',
                    '',
                    '&7Tip:&r Keep a batch in Refined Storage; nearly every branch consumes them.',
                ],
                task_count=4,
                links=require(POWAH_ENERGY_CELL),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Foundation',
            ),
            Quest(
                n=1,
                x=2.5,
                y=12.5,
                task='rftoolsbase:smartwrench',
                title='Smart Wrench',
                desc=[
                    '&6Goal:&r Craft an RFTools Smart Wrench.',
                    '',
                    'The wrench rotates, configures, links, and safely moves through RFTools setups.',
                    '',
                    '&7Tip:&r Carry it before placing machines whose facing or links matter.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Tools',
            ),
            Quest(
                n=2,
                x=5.0,
                y=12.5,
                task='rftoolspower:coalgenerator',
                title='Coal Generator',
                desc=[
                    '&6Goal:&r Craft an RFTools Coal Generator.',
                    '',
                    'This compact generator is a fallback FE source and a clear introduction to RFTools Power.',
                    '',
                    '&7Tip:&r Feed the same power bus as Powah, but let Powah handle serious base generation.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power',
            ),
            Quest(
                n=3,
                x=7.5,
                y=12.5,
                task='rftoolspower:cell1',
                title='Power Cell',
                desc=[
                    '&6Goal:&r Craft a Level 1 Power Cell.',
                    '',
                    'Power Cells buffer FE locally and can grow into linked power networks.',
                    '',
                    '&7Tip:&r Place one beside bursty machines so cable demand stays smooth.',
                ],
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power',
            ),
            Quest(
                n=4,
                x=10.0,
                y=12.5,
                task='rftoolspower:powercell_card',
                title='Powercell Card',
                desc=[
                    '&6Goal:&r Craft a Powercell Card.',
                    '',
                    'Cards link compatible RFTools power cells and dimensional cells into a shared network.',
                    '',
                    '&7Tip:&r Name cards or networks by purpose to avoid cross-wiring factories.',
                ],
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power networking',
            ),
            Quest(
                n=5,
                x=12.5,
                y=12.5,
                task='rftoolspower:dimensionalcell',
                title='Dimensional Cell',
                desc=[
                    '&6Goal:&r Craft a Dimensional Cell.',
                    '',
                    'Dimensional Cells move FE across distance and dimensions without running physical cables.',
                    '',
                    '&7Tip:&r Use Powah generation to charge the network that supports teleporters and dimensions.',
                ],
                deps=[4],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Power networking',
            ),
            Quest(
                n=6,
                x=15.0,
                y=12.5,
                task='rftoolsutility:crafter1',
                title='Automated Crafter',
                desc=[
                    '&6Goal:&r Craft a Tier 1 RFTools Crafter.',
                    '',
                    'RFTools Crafters continuously process buffered recipes, ideal for compact material loops.',
                    '',
                    '&7Tip:&r Use Create or Pipez to supply ingredients and export results to Refined Storage.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Automation',
            ),
            Quest(
                n=7,
                x=17.5,
                y=12.5,
                task='rftoolsutility:crafter3',
                title='Tier 3 Crafter',
                desc=[
                    '&6Goal:&r Upgrade to a Tier 3 RFTools Crafter.',
                    '',
                    'The top crafter handles many recipes in one block and can retain intermediates internally.',
                    '',
                    '&7Tip:&r Use remembered outputs carefully to prevent recipe loops from clogging.',
                ],
                deps=[6],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Automation',
            ),
            Quest(
                n=8,
                x=20.0,
                y=12.5,
                task='rftoolsutility:screen',
                title='Information Screen',
                desc=[
                    '&6Goal:&r Craft an RFTools Screen.',
                    '',
                    'Screens present power, inventory, fluid, machine, and text data through installable modules.',
                    '',
                    '&7Tip:&r Build the module that matches the system you actually need to monitor.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=9,
                x=22.5,
                y=12.5,
                task='rftoolsutility:screen_controller',
                title='Screen Controller',
                desc=[
                    '&6Goal:&r Craft a Screen Controller.',
                    '',
                    'A controller supplies power and data to nearby screens for a clean factory dashboard.',
                    '',
                    '&7Tip:&r Keep its range and FE use in mind when laying out a control room.',
                ],
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=10,
                x=25.0,
                y=12.5,
                task='rftoolspower:power_monitor',
                title='Power Monitor',
                desc=[
                    '&6Goal:&r Craft a Power Monitor.',
                    '',
                    'Monitor stored energy and emit redstone at useful thresholds before the factory browns out.',
                    '',
                    '&7Tip:&r Connect the signal to backup Powah generators or nonessential machine shutoffs.',
                ],
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=11,
                x=27.5,
                y=12.5,
                task='rftoolsutility:matter_transmitter',
                title='Matter Transmitter',
                desc=[
                    '&6Goal:&r Craft a Matter Transmitter.',
                    '',
                    'Matter transmitters send players to linked receivers and form the travel backbone of RFTools Dimensions.',
                    '',
                    '&7Tip:&r Teleportation needs reliable FE; buffer it rather than trusting live generation.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=12,
                x=30.0,
                y=12.5,
                task='rftoolsutility:matter_receiver',
                title='Matter Receiver',
                desc=[
                    '&6Goal:&r Craft a Matter Receiver.',
                    '',
                    'A receiver creates a destination for transmitters, including in distant or custom dimensions.',
                    '',
                    '&7Tip:&r Power and protect the destination before dialing it.',
                ],
                deps=[11],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=13,
                x=0.0,
                y=15.0,
                task='rftoolsutility:dialing_device',
                title='Dialing Device',
                desc=[
                    '&6Goal:&r Craft a Dialing Device.',
                    '',
                    'The dialer discovers nearby transmitters and receivers and connects the selected route.',
                    '',
                    '&7Tip:&r Give destinations clear names so travel remains safe and predictable.',
                ],
                deps=[12],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=14,
                x=2.5,
                y=15.0,
                task='rftoolsutility:environmental_controller',
                title='Environmental Controller',
                desc=[
                    '&6Goal:&r Craft an Environmental Controller.',
                    '',
                    'With modules installed, this powered machine applies useful effects across a configurable area.',
                    '',
                    '&7Tip:&r Its ongoing FE cost rises with range and modules, so measure before expanding.',
                ],
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Utility',
            ),
            Quest(
                n=15,
                x=5.0,
                y=15.0,
                task='rftoolsstorage:storage_module1',
                title='Storage Module',
                desc=[
                    '&6Goal:&r Craft a Tier 1 Storage Module.',
                    '',
                    'Storage Modules determine the capacity of Modular Storage blocks.',
                    '',
                    '&7Tip:&r This is complementary local storage; keep bulk searchable stock in Refined Storage.',
                ],
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=16,
                x=7.5,
                y=15.0,
                task='rftoolsstorage:modular_storage',
                title='Modular Storage',
                desc=[
                    '&6Goal:&r Craft Modular Storage and install your module.',
                    '',
                    "One compact block exposes the module's inventory with filtering and a convenient interface.",
                    '',
                    '&7Tip:&r Use it for work cells whose contents should stay separate from the main network.',
                ],
                deps=[15],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=17,
                x=10.0,
                y=15.0,
                task='rftoolsstorage:storage_scanner',
                title='Storage Scanner',
                desc=[
                    '&6Goal:&r Craft a Storage Scanner.',
                    '',
                    'The scanner searches and accesses nearby inventories from one interface without replacing them.',
                    '',
                    '&7Tip:&r Scan Create vaults and local chests, then use RS for globally managed storage.',
                ],
                deps=[16],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=18,
                x=12.5,
                y=15.0,
                task='rftoolsstorage:tablet_scanner',
                title='Remote Storage Tablet',
                desc=[
                    '&6Goal:&r Craft a Storage Scanner Tablet.',
                    '',
                    'The tablet gives portable access to a linked scanner when it has power and connectivity.',
                    '',
                    '&7Tip:&r Keep it charged with Powah wireless charging before long expeditions.',
                ],
                deps=[17],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=19,
                x=15.0,
                y=15.0,
                task='rftoolsstorage:crafting_manager',
                title='Crafting Manager',
                desc=[
                    '&6Goal:&r Craft an RFTools Crafting Manager.',
                    '',
                    'The manager coordinates RFTools storage and crafting resources from a central interface.',
                    '',
                    '&7Tip:&r Use it for self-contained production cells; RS remains best for pack-wide autocrafting.',
                ],
                deps=[18],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage automation',
            ),
            Quest(
                n=20,
                x=17.5,
                y=15.0,
                task='rftoolsbase:dimensionalshard',
                title='Dimensional Shards',
                desc=[
                    '&6Goal:&r Collect &68 Dimensional Shards&r.',
                    '',
                    'These rare materials gate advanced RFTools machinery and the custom-dimension path.',
                    '',
                    "&7Tip:&r Check JEI's ore-height display and dimension sources before committing to a mining trip.",
                ],
                task_count=8,
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=21,
                x=20.0,
                y=15.0,
                task='rftoolsdim:dimlet_workbench',
                title='Dimlet Workbench',
                desc=[
                    '&6Goal:&r Craft a Dimlet Workbench.',
                    '',
                    'The workbench assembles researched parts into dimlets that describe terrain, biomes, blocks, and features.',
                    '',
                    '&7Tip:&r Start with a simple, low-cost world before combining expensive effects.',
                ],
                deps=[20],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=22,
                x=22.5,
                y=15.0,
                task='rftoolsdim:researcher',
                title='Dimlet Researcher',
                desc=[
                    '&6Goal:&r Craft a Dimlet Researcher.',
                    '',
                    'Research turns lost knowledge into usable information for building custom dimlets.',
                    '',
                    '&7Tip:&r Automate its inputs only after understanding the rarity tiers.',
                ],
                deps=[21],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=23,
                x=25.0,
                y=15.0,
                task='rftoolsdim:enscriber',
                title='Dimension Enscriber',
                desc=[
                    '&6Goal:&r Craft a Dimension Enscriber.',
                    '',
                    'The Enscriber combines selected dimlets with a dimension tab to define a realizable world.',
                    '',
                    '&7Tip:&r Read the projected maintenance cost and avoid unstable combinations.',
                ],
                deps=[22],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=24,
                x=27.5,
                y=15.0,
                task='rftoolsdim:dimension_builder',
                title='Dimension Builder',
                desc=[
                    '&6Goal:&r Craft a Dimension Builder.',
                    '',
                    'The Builder realizes and continuously powers your designed dimension.',
                    '',
                    '&7Tip:&r Supply a large Powah/RFTools energy buffer, then place a powered receiver before exploring.',
                ],
                deps=[23],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Dimensions',
            ),
        ],
    )

