"""7. RFTools quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, require, xp_levels
from ftb_quests.ids import POWAH_ENERGY_CELL
from ftb_quests.text import tutorial


def chapter() -> Chapter:
    return Chapter(
        key='rftools',
        base=445,
        chapter_id='A200000000000008',
        icon='rftoolsbase:machine_frame',
        title='7. RFTools',
        subtitle='Power, automation, storage scanning, teleportation, and dimensions',
        quests=[
            Quest(
                n=0,
                x=0.0,
                y=12.5,
                task='rftoolsbase:machine_frame',
                title='RFTools Framework',
                desc=tutorial(
                    'Craft &64 RFTools Machine Frames&r.',
                    why='Machine Frames are the common chassis for the entire RFTools suite.',
                    steps=[
                        'Gather iron and the other JEI ingredients for Machine Frames.',
                        'Craft at least four frames to start Power, Utility, and Storage branches.',
                        'Stock extras in Refined Storage — nearly every branch consumes them.',
                    ],
                    tip='Batch frames once; rebuilding every machine from scratch hurts.',
                    nxt='Craft a Smart Wrench before placing machines.',
                ),
                task_count=4,
                links=require(POWAH_ENERGY_CELL),
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Foundation',
            ),
            Quest(
                n=1,
                x=2.5,
                y=12.5,
                task='rftoolsbase:smartwrench',
                title='Smart Wrench',
                desc=tutorial(
                    'Craft an RFTools Smart Wrench.',
                    why='Rotates, configures, links, and safely moves RFTools setups.',
                    steps=[
                        'Craft the Smart Wrench and keep it on your hotbar.',
                        'Sneak-click / mode-cycle to switch rotate vs pick-up modes as needed.',
                        'Use it when placing machines whose facing or card links matter.',
                    ],
                    tip='Pick up machines with the wrench to keep modules and settings intact.',
                    nxt='Optional: Coal Generator, or jump into crafters/screens from frames.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Tools',
            ),
            Quest(
                n=2,
                x=5.0,
                y=12.5,
                task='rftoolspower:coalgenerator',
                title='Coal Generator',
                desc=tutorial(
                    'Craft an RFTools Coal Generator.',
                    why='Compact fallback FE and a clear intro to RFTools Power — Powah still handles serious generation.',
                    steps=[
                        'Place the Coal Generator near a Power Cell.',
                        'Insert coal and cable FE into your RFTools/Powah bus.',
                        'Use it as backup, not as your only base generator.',
                    ],
                    tip='Feed the same power bus as Powah so tools and cells share one buffer.',
                    nxt='Craft a Level 1 Power Cell.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power',
            ),
            Quest(
                n=3,
                x=7.5,
                y=12.5,
                task='rftoolspower:cell1',
                title='Power Cell',
                desc=tutorial(
                    'Craft a Level 1 Power Cell.',
                    why='Buffers FE locally and can grow into linked power networks with cards.',
                    steps=[
                        'Place the Power Cell beside bursty machines (crafters, teleporters).',
                        'Cable generation in and consumers out; note input/output faces in the GUI.',
                        'Upgrade or link cells later instead of starring every machine to live gen.',
                    ],
                    tip='Local buffers keep cable demand smooth under teleport spikes.',
                    nxt='Craft a Powercell Card to link cells.',
                ),
                deps=[2],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power',
            ),
            Quest(
                n=4,
                x=10.0,
                y=12.5,
                task='rftoolspower:powercell_card',
                title='Powercell Card',
                desc=tutorial(
                    'Craft a Powercell Card.',
                    why='Cards link compatible RFTools power cells and dimensional cells into a shared network.',
                    steps=[
                        'Craft the card and open a Power Cell GUI.',
                        'Insert matching cards (or link per GUI instructions) on every cell that should share FE.',
                        'Name cards/networks by purpose — Factory, Dims, Backup.',
                    ],
                    tip='Mismatched or blank names cause accidental cross-wiring on multiplayer.',
                    nxt='Add a Dimensional Cell for cross-dimension FE.',
                ),
                deps=[3],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Power networking',
            ),
            Quest(
                n=5,
                x=12.5,
                y=12.5,
                task='rftoolspower:dimensionalcell',
                title='Dimensional Cell',
                desc=tutorial(
                    'Craft a Dimensional Cell.',
                    why='Moves FE across distance and dimensions without running physical cables.',
                    steps=[
                        'Place a Dimensional Cell in the overworld next to your main buffer.',
                        'Link it with a Powercell Card to the same network as your Power Cells.',
                        'Place another linked cell in remote bases or future dimensions; charge from Powah.',
                    ],
                    tip='Use Powah generation to charge the network that supports teleporters and dimensions.',
                    nxt='Matter Transmitters need this kind of reliable FE.',
                ),
                deps=[4],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Power networking',
            ),
            Quest(
                n=6,
                x=15.0,
                y=12.5,
                task='rftoolsutility:crafter1',
                title='Automated Crafter',
                desc=tutorial(
                    'Craft a Tier 1 RFTools Crafter.',
                    why='Continuously processes buffered recipes — compact material loops beside Create lines.',
                    steps=[
                        'Place the Crafter and power it with FE.',
                        'Open the GUI, set a recipe, and define input/output sides.',
                        'Pipe ingredients in with Create or Pipez; export results to Refined Storage.',
                    ],
                    tip='Start with one high-volume craft (plates, gears) before multi-recipe setups.',
                    nxt='Upgrade to Tier 3 for multi-recipe crafting.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Automation',
            ),
            Quest(
                n=7,
                x=17.5,
                y=12.5,
                task='rftoolsutility:crafter3',
                title='Tier 3 Crafter',
                desc=tutorial(
                    'Upgrade to a Tier 3 RFTools Crafter.',
                    why='Handles many recipes in one block and can retain intermediates internally.',
                    steps=[
                        'Craft/upgrade to Crafter Tier 3 and reinstall your recipes.',
                        'Enable remembered/internal buffers only for steps that need them.',
                        'Watch for recipe loops — disable retain on outputs that re-enter as inputs.',
                    ],
                    tip='Use remembered outputs carefully to prevent clogging loops.',
                    nxt='Build Screens to monitor the factory.',
                ),
                deps=[6],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Automation',
            ),
            Quest(
                n=8,
                x=20.0,
                y=12.5,
                task='rftoolsutility:screen',
                title='Information Screen',
                desc=tutorial(
                    'Craft an RFTools Screen.',
                    why='Presents power, inventory, fluid, machine, and text data through installable modules.',
                    steps=[
                        'Place the Screen on a wall in your control room.',
                        'Craft the module that matches what you need (energy, fluid, inventory, etc.).',
                        'Install the module and link it to the target machine or cell with the wrench/GUI.',
                    ],
                    tip='Build modules for systems you actually monitor — empty screens are just art.',
                    nxt='Add a Screen Controller for powered dashboards.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=9,
                x=22.5,
                y=12.5,
                task='rftoolsutility:screen_controller',
                title='Screen Controller',
                desc=tutorial(
                    'Craft a Screen Controller.',
                    why='Supplies power and data to nearby screens for a clean factory dashboard.',
                    steps=[
                        'Place the Screen Controller within range of your Screens.',
                        'Cable FE into the controller.',
                        'Confirm screens update; expand the room only within controller range.',
                    ],
                    tip='Keep range and FE use in mind — huge control rooms need power and proximity.',
                    nxt='Add a Power Monitor for redstone thresholds.',
                ),
                deps=[8],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=10,
                x=25.0,
                y=12.5,
                task='rftoolspower:power_monitor',
                title='Power Monitor',
                desc=tutorial(
                    'Craft a Power Monitor.',
                    why='Watches stored energy and emits redstone at useful thresholds before brownouts.',
                    steps=[
                        'Place the Power Monitor near your main Power/Dimensional Cell.',
                        'Link it to the cell and set low/high thresholds in the GUI.',
                        'Wire the redstone signal to backup Powah generators or nonessential shutoffs.',
                    ],
                    tip='A low-power signal that starts Magmators beats discovering a dead RS network.',
                    nxt='With power solid, build Matter Transmitters.',
                ),
                deps=[9],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Monitoring',
            ),
            Quest(
                n=11,
                x=27.5,
                y=12.5,
                task='rftoolsutility:matter_transmitter',
                title='Matter Transmitter',
                desc=tutorial(
                    'Craft a Matter Transmitter.',
                    why='Sends players to linked receivers — the travel backbone for RFTools Dimensions.',
                    steps=[
                        'Place the Matter Transmitter on a safe pad with clear standing space.',
                        'Cable a large FE buffer into it (Dimensional Cell recommended).',
                        'Do not dial destinations until a powered receiver exists.',
                    ],
                    tip='Teleportation needs buffered FE — never trust live generation alone.',
                    nxt='Craft a Matter Receiver destination.',
                ),
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=12,
                x=30.0,
                y=12.5,
                task='rftoolsutility:matter_receiver',
                title='Matter Receiver',
                desc=tutorial(
                    'Craft a Matter Receiver.',
                    why='Creates a destination for transmitters, including in distant or custom dimensions.',
                    steps=[
                        'Place the receiver at the destination with clear landing space.',
                        'Power it and protect the area (lighting, walls, no lava pits).',
                        'Note its name/location for the Dialing Device.',
                    ],
                    tip='Power and protect the destination before dialing it.',
                    nxt='Link routes with a Dialing Device.',
                ),
                deps=[11],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=13,
                x=0.0,
                y=15.0,
                task='rftoolsutility:dialing_device',
                title='Dialing Device',
                desc=tutorial(
                    'Craft a Dialing Device.',
                    why='Discovers nearby transmitters and receivers and connects the selected route.',
                    steps=[
                        'Place the Dialing Device near your Matter Transmitter.',
                        'Open it, select transmitter → receiver, and dial the route.',
                        'Give destinations clear names so travel stays safe and predictable.',
                    ],
                    tip='Rename “Receiver” to “Factory / Mining / Dim Hub” before you have twelve of them.',
                    nxt='Optional utility: Environmental Controller — then Dimensions path.',
                ),
                deps=[12],
                rewards=[xp_levels(1)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Teleportation',
            ),
            Quest(
                n=14,
                x=2.5,
                y=15.0,
                task='rftoolsutility:environmental_controller',
                title='Environmental Controller',
                desc=tutorial(
                    'Craft an Environmental Controller.',
                    why='With modules installed, applies useful effects across a configurable area.',
                    steps=[
                        'Place and power the Environmental Controller in the target area.',
                        'Craft and insert modules (regen, flight, haste, etc. per JEI).',
                        'Set radius and filters; measure FE cost before expanding range.',
                    ],
                    tip='Ongoing FE cost rises with range and modules — start small.',
                    nxt='Storage Scanner branch for local inventory access.',
                ),
                deps=[5],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Utility',
            ),
            Quest(
                n=15,
                x=5.0,
                y=15.0,
                task='rftoolsstorage:storage_module1',
                title='Storage Module',
                desc=tutorial(
                    'Craft a Tier 1 Storage Module.',
                    why='Storage Modules set the capacity of Modular Storage blocks.',
                    steps=[
                        'Craft the Tier 1 Storage Module.',
                        'Keep higher-tier modules for later capacity upgrades.',
                        'Treat this as complementary local storage — bulk searchable stock stays in RS.',
                    ],
                    tip='Modules are swappable — upgrade capacity without rebuilding the block.',
                    nxt='Install it in Modular Storage.',
                ),
                deps=[0],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=16,
                x=7.5,
                y=15.0,
                task='rftoolsstorage:modular_storage',
                title='Modular Storage',
                desc=tutorial(
                    'Craft Modular Storage and install your module.',
                    why="One compact block exposes the module's inventory with filtering and a convenient UI.",
                    steps=[
                        'Place Modular Storage at a work cell.',
                        'Insert the Storage Module in the GUI.',
                        'Configure filters so this inventory stays separate from the main RS network.',
                    ],
                    tip='Great for work-cell kits that should not dump into digital storage.',
                    nxt='Scan nearby inventories with a Storage Scanner.',
                ),
                deps=[15],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=17,
                x=10.0,
                y=15.0,
                task='rftoolsstorage:storage_scanner',
                title='Storage Scanner',
                desc=tutorial(
                    'Craft a Storage Scanner.',
                    why='Searches and accesses nearby inventories from one interface without replacing them.',
                    steps=[
                        'Place the Storage Scanner near Create vaults, chests, and Modular Storage.',
                        'Power it and scan/radius-configure until target inventories appear.',
                        'Pull and push items from the scanner UI; keep global stock in RS.',
                    ],
                    tip='Scan Create vaults and local chests — RS remains pack-wide storage.',
                    nxt='Craft a Storage Scanner Tablet for remote access.',
                ),
                deps=[16],
                rewards=[xp_levels(1)],
                size=1.5,
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=18,
                x=12.5,
                y=15.0,
                task='rftoolsstorage:tablet_scanner',
                title='Remote Storage Tablet',
                desc=tutorial(
                    'Craft a Storage Scanner Tablet.',
                    why='Portable access to a linked scanner when it has power and connectivity.',
                    steps=[
                        'Craft the tablet and link it to your Storage Scanner.',
                        'Keep the tablet charged (Powah Player Transmitter works well).',
                        'Open it in the field to pull from the linked scanner inventories.',
                    ],
                    tip='Charge before expeditions — a dead tablet is a fancy brick.',
                    nxt='Optional Crafting Manager, then Dimensions.',
                ),
                deps=[17],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage',
            ),
            Quest(
                n=19,
                x=15.0,
                y=15.0,
                task='rftoolsstorage:crafting_manager',
                title='Crafting Manager',
                desc=tutorial(
                    'Craft an RFTools Crafting Manager.',
                    why='Coordinates RFTools storage and crafting resources from a central interface.',
                    steps=[
                        'Place the Crafting Manager near Modular Storage and crafters.',
                        'Link storage/crafting resources in its GUI.',
                        'Use it for self-contained production cells; keep pack-wide autocrafting in RS.',
                    ],
                    tip='RFTools crafting cells complement RS — they do not replace pattern halls.',
                    nxt='Collect Dimensional Shards for custom worlds.',
                ),
                deps=[18],
                rewards=[xp_levels(1)],
                subtitle='RFTools · Storage automation',
            ),
            Quest(
                n=20,
                x=17.5,
                y=15.0,
                task='rftoolsbase:dimensionalshard',
                title='Dimensional Shards',
                desc=tutorial(
                    'Collect &68 Dimensional Shards&r.',
                    why='Rare materials that gate advanced RFTools machinery and the custom-dimension path.',
                    steps=[
                        "Check JEI's ore-height display and dimension sources.",
                        'Mine or process shards until you have eight.',
                        'Store them for the Dimlet Workbench chain.',
                    ],
                    tip='Bring a Waystone and FE tools — shard hunts are long trips.',
                    nxt='Craft a Dimlet Workbench.',
                ),
                task_count=8,
                deps=[13],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=21,
                x=20.0,
                y=15.0,
                task='rftoolsdim:dimlet_workbench',
                title='Dimlet Workbench',
                desc=tutorial(
                    'Craft a Dimlet Workbench.',
                    why='Assembles researched parts into dimlets that describe terrain, biomes, blocks, and features.',
                    steps=[
                        'Place and power the Dimlet Workbench.',
                        'Craft or research dimlet parts, then assemble a simple low-cost world dimlet set.',
                        'Avoid stacking expensive effects on your first world.',
                    ],
                    tip='Start simple — a boring safe world beats an unstable expensive one.',
                    nxt='Research knowledge with a Dimlet Researcher.',
                ),
                deps=[20],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=22,
                x=22.5,
                y=15.0,
                task='rftoolsdim:researcher',
                title='Dimlet Researcher',
                desc=tutorial(
                    'Craft a Dimlet Researcher.',
                    why='Turns lost knowledge into usable information for building custom dimlets.',
                    steps=[
                        'Place the Researcher and supply FE.',
                        'Insert researchable knowledge items per JEI.',
                        'Automate inputs only after you understand rarity tiers and waste rates.',
                    ],
                    tip='Read rarity before dumping stacks — expensive knowledge is easy to burn.',
                    nxt='Combine dimlets in a Dimension Enscriber.',
                ),
                deps=[21],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=23,
                x=25.0,
                y=15.0,
                task='rftoolsdim:enscriber',
                title='Dimension Enscriber',
                desc=tutorial(
                    'Craft a Dimension Enscriber.',
                    why='Combines selected dimlets with a dimension tab to define a realizable world.',
                    steps=[
                        'Place the Enscriber and insert your chosen dimlets plus a dimension tab.',
                        'Read the projected maintenance cost and stability before confirming.',
                        'Avoid unstable combinations until you can afford continuous FE.',
                    ],
                    tip='If maintenance cost looks scary, remove fancy dimlets and retry.',
                    nxt='Realize the world with a Dimension Builder.',
                ),
                deps=[22],
                rewards=[xp_levels(2)],
                subtitle='RFTools · Dimensions',
            ),
            Quest(
                n=24,
                x=27.5,
                y=15.0,
                task='rftoolsdim:dimension_builder',
                title='Dimension Builder',
                desc=tutorial(
                    'Craft a Dimension Builder.',
                    why='Realizes and continuously powers your designed dimension.',
                    steps=[
                        'Place the Dimension Builder and cable a large Powah/RFTools energy buffer into it.',
                        'Insert the enscribed dimension tab and start realization.',
                        'Place a powered Matter Receiver in the new dimension before exploring deep.',
                    ],
                    tip='Dimensions idle-cost FE forever — budget generation before tourism.',
                    nxt='RFTools path complete — Flux Networks can wireless your FE grid next.',
                ),
                deps=[23],
                rewards=[xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='RFTools · Dimensions',
            ),
        ],
    )
