"""3. Bags & Blades quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import F_IRON


def chapter() -> Chapter:
    return Chapter(
        key='storage_gear',
        base=300,
        chapter_id='A200000000000003',
        icon='sophisticatedbackpacks:backpack',
        title='3. Bags & Blades',
        subtitle='Backpacks, drawers, pipes, Silent Gear, building tools',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='sophisticatedbackpacks:backpack',
                title='Backpack',
                desc=[
                    '&6Goal:&r Craft a Sophisticated Backpack.',
                    '',
                    'Upgrade it with stack, magnet, feeding, and tool-swap upgrades — your inventory becomes a workshop.',
                    '',
                    '&7Tip:&r Right-click to open. Craft upgrades and install them in the backpack GUI.',
                    '&7Next:&r Iron backpack + stack upgrade, then drawers for bulk materials.',
                ],
                links=require(F_IRON),
                rewards=[item('minecraft:leather', 16), item('minecraft:string', 16), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Carry more',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='sophisticatedbackpacks:iron_backpack',
                title='Iron Backpack',
                desc=[
                    '&6Goal:&r Upgrade to an Iron Backpack.',
                    '',
                    'More slots for long cave runs and factory wiring sessions.',
                ],
                deps=[0],
                rewards=[item('minecraft:iron_ingot', 16), xp_levels(1)],
                subtitle='Carry more',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='sophisticatedbackpacks:stack_upgrade_tier_1',
                title='Stack Upgrade',
                desc=[
                    '&6Goal:&r Craft a stack upgrade (tier 1) for your backpack.',
                    '',
                    'Carry fewer slot types and more of what matters — alloy, sheets, mechanisms.',
                ],
                deps=[1],
                rewards=[item('sophisticatedbackpacks:pickup_upgrade'), xp_levels(1)],
                subtitle='Carry more',
            ),
            Quest(
                n=3,
                x=2.5,
                y=2.5,
                task='functionalstorage:oak_1',
                title='Drawers',
                desc=[
                    '&6Goal:&r Craft &64 Functional Storage drawers&r.',
                    '',
                    'Drawers compact a huge count of one item — perfect for cobble, andesite alloy, and ingots.',
                    '',
                    '&7Next:&r Add a storage controller to talk to many drawers at once.',
                ],
                task_count=4,
                deps=[1],
                rewards=[item('minecraft:chest', 8)],
                subtitle='Storage',
            ),
            Quest(
                n=4,
                x=5,
                y=2.5,
                task='functionalstorage:storage_controller',
                title='Drawer Controller',
                desc=[
                    '&6Goal:&r Craft a Functional Storage controller.',
                    '',
                    'Access a whole drawer wall from one block — pipe into the controller, not every drawer.',
                ],
                deps=[3],
                rewards=[item('minecraft:redstone', 16), xp_levels(1)],
                size=1.5,
                subtitle='Storage',
            ),
            Quest(
                n=5,
                x=7.5,
                y=2.5,
                task='functionalstorage:compacting_drawer',
                title='Compacting Drawer',
                desc=[
                    '&6Goal:&r Craft a compacting drawer.',
                    '',
                    'Auto-crafts nuggets ↔ ingots ↔ blocks. Perfect for iron, gold, and Create metals.',
                ],
                deps=[4],
                rewards=[item('minecraft:iron_ingot', 32)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=5,
                y=-2.5,
                task='sophisticatedstorage:iron_chest',
                title='Sophisticated Chest',
                desc=[
                    '&6Goal:&r Craft a Sophisticated Storage iron chest.',
                    '',
                    'Upgradeable chests/barrels with the same upgrade ecosystem as backpacks — filters, compacting, and more.',
                ],
                deps=[1],
                rewards=[item('minecraft:chest', 4), xp_levels(1)],
                subtitle='Storage',
            ),
            Quest(
                n=7,
                x=7.5,
                y=-2.5,
                task='sophisticatedstorage:controller',
                title='Storage Controller',
                desc=[
                    '&6Goal:&r Craft a Sophisticated Storage controller.',
                    '',
                    'Network nearby sophisticated containers for combined access.',
                ],
                deps=[6],
                rewards=[item('minecraft:ender_pearl', 2), xp_levels(1)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=8,
                x=10,
                y=0,
                task='toms_storage:inventory_connector',
                title="Tom's Storage Hub",
                desc=[
                    "&6Goal:&r Craft Tom's Inventory Connector.",
                    '',
                    'Link nearby inventories and browse them from a terminal — lightweight digital storage without AE2.',
                    '',
                    '&7Tip:&r Keep linked chests close; use cables for larger bases.',
                    '&7Next:&r Add a crafting terminal for JEI-friendly crafting from the network.',
                ],
                deps=[4],
                rewards=[item('minecraft:ender_pearl', 4), xp_levels(1)],
                size=1.5,
                subtitle='Storage',
            ),
            Quest(
                n=9,
                x=12.5,
                y=0,
                task='toms_storage:crafting_terminal',
                title='Crafting Terminal',
                desc=[
                    "&6Goal:&r Craft Tom's Crafting Terminal.",
                    '',
                    'Craft using everything the Inventory Connector can see. Pair with Pipez or Create for restocking.',
                ],
                deps=[8],
                rewards=[item('minecraft:crafting_table'), xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Storage',
            ),
            Quest(
                n=10,
                x=10,
                y=2.5,
                task='pipez:item_pipe',
                title='Item Pipes',
                desc=[
                    '&6Goal:&r Craft &632 Pipez item pipes&r.',
                    '',
                    'Chest-to-chest logistics with filters — simpler than Create belts for bulk sorting.',
                    '',
                    '&7Tip:&r Configure with a wrench. Upgrades raise speed.',
                ],
                task_count=32,
                deps=[3],
                rewards=[item('minecraft:iron_ingot', 16), item('pipez:wrench')],
                subtitle='Pipes',
            ),
            Quest(
                n=11,
                x=12.5,
                y=2.5,
                task='pipez:fluid_pipe',
                title='Fluid Pipes',
                desc=[
                    '&6Goal:&r Craft &616 fluid pipes&r.',
                    '',
                    'Move water, lava, chocolate, diesel, and Create fluids between tanks and machines.',
                ],
                task_count=16,
                deps=[10],
                rewards=[item('minecraft:copper_ingot', 16), xp_levels(1)],
                subtitle='Pipes',
            ),
            Quest(
                n=12,
                x=15,
                y=2.5,
                task='pipez:energy_pipe',
                title='Energy Pipes',
                desc=[
                    '&6Goal:&r Craft &616 energy pipes&r.',
                    '',
                    'Move FE between Create Crafts & Additions machines, jetpack chargers, and electric addons.',
                ],
                task_count=16,
                deps=[11],
                rewards=[item('minecraft:redstone', 32)],
                optional=True,
                subtitle='Pipes',
                hide_until_deps=True,
            ),
            Quest(
                n=13,
                x=15,
                y=0,
                task='ironchest:gold_chest',
                title='Gold Chest',
                desc=[
                    '&6Goal:&r Upgrade to a Gold Chest.',
                    '',
                    "When drawer networks aren't enough for mixed junk storage.",
                ],
                deps=[9],
                rewards=[item('minecraft:gold_ingot', 16)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=15,
                y=-2.5,
                task='ironfurnaces:gold_furnace',
                title='Gold Furnace',
                desc=[
                    '&6Goal:&r Craft a Gold Furnace.',
                    '',
                    'Big smelting speed jump. Diamond / netherite tiers wait in Beyond Brass.',
                ],
                deps=[13],
                rewards=[item('minecraft:gold_ingot', 16), item('minecraft:coal_block', 4)],
                optional=True,
                subtitle='Smelting',
                hide_until_deps=True,
            ),
            Quest(
                n=15,
                x=2.5,
                y=-2.5,
                task='silentgear:blueprint_paper',
                title='Blueprint Paper',
                desc=[
                    '&6Goal:&r Craft &64 Silent Gear blueprint papers&r.',
                    '',
                    'Blueprints let you stamp modular tool recipes. Mix materials for mining speed, durability, and harvest level.',
                ],
                task_count=4,
                deps=[2],
                rewards=[item('silentgear:template_board', 4), xp_levels(1)],
                subtitle='Gear',
            ),
            Quest(
                n=16,
                x=5,
                y=-4.5,
                task='silentgear:pickaxe_blueprint',
                title='Pickaxe Blueprint',
                desc=[
                    '&6Goal:&r Craft a Silent Gear pickaxe blueprint.',
                    '',
                    'Build modular pickaxes — head, rod, and tip materials each matter.',
                    '',
                    '&7Tip:&r JEI shows material traits. Upgrade tips as you find better metals.',
                ],
                deps=[15],
                rewards=[item('minecraft:iron_ingot', 16), xp_levels(1)],
                subtitle='Gear',
            ),
            Quest(
                n=17,
                x=7.5,
                y=-4.5,
                task='silentgear:sword_blueprint',
                title='Sword Blueprint',
                desc=[
                    '&6Goal:&r Craft a Silent Gear sword blueprint.',
                    '',
                    'Optional combat path — match materials to your mining set for style points.',
                ],
                deps=[16],
                rewards=[item('minecraft:iron_sword')],
                optional=True,
                subtitle='Gear',
                hide_until_deps=True,
            ),
            Quest(
                n=18,
                x=10,
                y=-4.5,
                task='constructionstick:iron_stick',
                title='Construction Stick',
                desc=[
                    '&6Goal:&r Craft an Iron Construction Stick.',
                    '',
                    'Extend walls and platforms in one click — faster base building before Building Gadgets.',
                ],
                deps=[1],
                rewards=[item('minecraft:iron_ingot', 16)],
                subtitle='Building',
            ),
            Quest(
                n=19,
                x=12.5,
                y=-4.5,
                task='buildinggadgets2:gadget_building',
                title='Building Gadget',
                desc=[
                    '&6Goal:&r Craft a Building Gadget 2.',
                    '',
                    'Copy / build / exchange blocks in bulk — perfect for factories and railways.',
                    '',
                    '&7Tip:&r Exchanging and copy-paste gadgets are worth unlocking next.',
                ],
                deps=[18],
                rewards=[item('minecraft:redstone', 32), xp_levels(2)],
                size=1.5,
                subtitle='Building',
            ),
            Quest(
                n=20,
                x=15,
                y=-4.5,
                task='buildinggadgets2:gadget_copy_paste',
                title='Copy-Paste Gadget',
                desc=[
                    '&6Goal:&r Craft the Copy-Paste Gadget.',
                    '',
                    'Save a structure and stamp it elsewhere — repeated factory modules become trivial.',
                ],
                deps=[19],
                rewards=[item('buildinggadgets2:template'), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=17.5,
                y=0,
                task='artifacts:umbrella',
                title='Artifact Hunt',
                desc=[
                    '&6Goal:&r Find an Artifacts umbrella (or any artifact you prefer — umbrella is the checklist item).',
                    '',
                    'Trinkets drop from chests, mobs, and exploration. Equip them in Curios slots.',
                    '',
                    '&7Tip:&r Truly optional scavenger hunt — skip if RNG hates you.',
                ],
                deps=[2],
                rewards=[item('minecraft:phantom_membrane', 4), xp_levels(2)],
                optional=True,
                subtitle='Trinkets',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=2.5,
                task='minecraft:ender_eye',
                title='Structure Scout',
                desc=[
                    '&6Goal:&r Craft an Eye of Ender.',
                    '',
                    'Stronghold energy is optional this early — mostly a reminder that &6Lootr&r makes structure chests per-player.',
                    '',
                    '&7Tip:&r Raid structures with friends without loot drama.',
                ],
                deps=[21],
                rewards=[item('minecraft:emerald', 8), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=17.5,
                y=-2.5,
                task='supplementaries:faucet',
                title='Faucet',
                desc=[
                    '&6Goal:&r Craft a Supplementaries faucet.',
                    '',
                    'Pour fluids from tanks/cauldrons — handy QoL beside Create pumps.',
                ],
                deps=[8],
                rewards=[item('supplementaries:jar', 4)],
                optional=True,
                subtitle='QoL',
                hide_until_deps=True,
            ),
        ],
    )

