"""3. Bags & Blades quest chapter."""
from __future__ import annotations

from ftb_quests.ast import Chapter, Quest, item, require, xp_levels
from ftb_quests.ids import F_IRON
from ftb_quests.text import overview, tutorial


def chapter() -> Chapter:
    return Chapter(
        key='storage_gear',
        base=300,
        chapter_id='A200000000000003',
        icon='sophisticatedbackpacks:backpack',
        title='3. Bags & Blades',
        subtitle='Backpacks, drawers, pipes, Silent Gear, building tools',
        quests=[
            Quest(
                n=0,
                x=0,
                y=0,
                task='sophisticatedbackpacks:backpack',
                title='Backpack',
                desc=overview(
                    'Upgradeable carry storage — stack, magnet, feeding, and tool-swap upgrades turn your inventory into a workshop.',
                    you_will=[
                        'Craft a Sophisticated Backpack and open it with right-click',
                        'Install upgrades from the backpack GUI',
                        'Graduate to drawers, Pipez, and Tom\'s Storage for base logistics',
                    ],
                    tip='Iron backpack + stack upgrade first, then drawers for bulk materials.',
                )
                + [""]
                + tutorial(
                    'Craft a Sophisticated Backpack.',
                    why='Your first expandable inventory — mining trips and factory wiring stop fighting a 36-slot limit.',
                    steps=[
                        'Craft the basic backpack (leather + chest materials — check JEI).',
                        'Right-click to open it; wear it in the chest/back slot if your UI supports it.',
                        'Open the upgrade tab and note empty upgrade slots for later stack/magnet upgrades.',
                    ],
                    tip='Do not throw the backpack away when upgrading — higher tiers usually upgrade in place.',
                    nxt='Iron backpack for more slots, then drawers for bulk ore.',
                ),
                links=require(F_IRON),
                rewards=[item('minecraft:leather', 16), item('minecraft:string', 16), xp_levels(1)],
                size=2.0,
                shape='gear',
                subtitle='Carry more',
            ),
            Quest(
                n=1,
                x=2.5,
                y=0,
                task='sophisticatedbackpacks:iron_backpack',
                title='Iron Backpack',
                desc=tutorial(
                    'Upgrade to an Iron Backpack.',
                    why='More slots for long cave runs and factory wiring sessions.',
                    steps=[
                        'Craft the iron backpack upgrade / recipe from JEI.',
                        'Apply it to your basic backpack (crafting grid or upgrade UI).',
                        'Re-equip and confirm the extra slots before your next mining trip.',
                    ],
                ),
                deps=[0],
                rewards=[item('minecraft:iron_ingot', 16), xp_levels(1)],
                subtitle='Carry more',
            ),
            Quest(
                n=2,
                x=5,
                y=0,
                task='sophisticatedbackpacks:stack_upgrade_tier_1',
                title='Stack Upgrade',
                desc=tutorial(
                    'Craft a stack upgrade (tier 1) for your backpack.',
                    why='Carry fewer slot types and more of what matters — alloy, sheets, mechanisms.',
                    steps=[
                        'Craft a tier-1 stack upgrade.',
                        'Open the backpack GUI and place the upgrade in an upgrade slot.',
                        'Fill stacks of alloy / ingots to see the higher stack size.',
                    ],
                    tip='Pickup and magnet upgrades pair well for crushing-wheel cleanup.',
                ),
                deps=[1],
                rewards=[item('sophisticatedbackpacks:pickup_upgrade'), xp_levels(1)],
                subtitle='Carry more',
            ),
            Quest(
                n=3,
                x=2.5,
                y=2.5,
                task='functionalstorage:oak_1',
                title='Drawers',
                desc=tutorial(
                    'Craft &64 Functional Storage drawers&r.',
                    why='Drawers compact a huge count of one item — perfect for cobble, andesite alloy, and ingots.',
                    steps=[
                        'Craft 4 oak (or any wood) 1×1 drawers.',
                        'Place them on a wall near your factory inputs.',
                        'Right-click with an item to lock / fill that drawer\'s type.',
                        'Label mentally: cobble, alloy, iron, copper — one type each.',
                    ],
                    nxt='Add a storage controller to talk to many drawers at once.',
                ),
                task_count=4,
                deps=[1],
                rewards=[item('minecraft:chest', 8)],
                subtitle='Storage',
            ),
            Quest(
                n=4,
                x=5,
                y=2.5,
                task='functionalstorage:storage_controller',
                title='Drawer Controller',
                desc=tutorial(
                    'Craft a Functional Storage controller.',
                    why='Access a whole drawer wall from one block — pipe into the controller, not every drawer.',
                    steps=[
                        'Craft a storage controller.',
                        'Place it touching your drawer cluster (same contiguous wall).',
                        'Open the controller to browse all linked drawers.',
                        'Point Pipez / funnels at the controller for bulk import/export.',
                    ],
                ),
                deps=[3],
                rewards=[item('minecraft:redstone', 16), xp_levels(1)],
                size=1.5,
                subtitle='Storage',
            ),
            Quest(
                n=5,
                x=7.5,
                y=2.5,
                task='functionalstorage:compacting_drawer',
                title='Compacting Drawer',
                desc=tutorial(
                    'Craft a compacting drawer.',
                    why='Auto-crafts nuggets ↔ ingots ↔ blocks. Perfect for iron, gold, and Create metals.',
                    steps=[
                        'Craft a compacting drawer and place it in your drawer wall.',
                        'Insert iron (or another compactable metal) — watch nuggets/ingots/blocks convert.',
                        'Link it through the storage controller with the rest of the wall.',
                        'Pipe forge outputs here to auto-compress storage.',
                    ],
                ),
                deps=[4],
                rewards=[item('minecraft:iron_ingot', 32)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=6,
                x=5,
                y=-2.5,
                task='sophisticatedstorage:iron_chest',
                title='Sophisticated Chest',
                desc=tutorial(
                    'Craft a Sophisticated Storage iron chest.',
                    why='Upgradeable chests/barrels with the same upgrade ecosystem as backpacks — filters, compacting, and more.',
                    steps=[
                        'Craft a Sophisticated Storage iron chest.',
                        'Place it and open the upgrade slots in its GUI.',
                        'Install filters / pickup / compacting upgrades as needed.',
                        'Use for mixed junk that does not belong in single-item drawers.',
                    ],
                ),
                deps=[1],
                rewards=[item('minecraft:chest', 4), xp_levels(1)],
                subtitle='Storage',
            ),
            Quest(
                n=7,
                x=7.5,
                y=-2.5,
                task='sophisticatedstorage:controller',
                title='Storage Controller',
                desc=tutorial(
                    'Craft a Sophisticated Storage controller.',
                    why='Network nearby sophisticated containers for combined access.',
                    steps=[
                        'Craft a Sophisticated Storage controller.',
                        'Place it within range of your sophisticated chests/barrels.',
                        'Open the controller to access the networked containers together.',
                        'Optional: link to pipes for a second storage bus beside drawers.',
                    ],
                ),
                deps=[6],
                rewards=[item('minecraft:ender_pearl', 2), xp_levels(1)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=8,
                x=10,
                y=0,
                task='toms_storage:inventory_connector',
                title="Tom's Storage Hub",
                desc=tutorial(
                    "Craft Tom's Inventory Connector.",
                    why='Link nearby inventories and browse them from a terminal — lightweight digital storage without AE2.',
                    steps=[
                        "Craft Tom's Inventory Connector and place it centrally.",
                        'Ensure chests/drawers you want linked are within range (use cables for larger bases).',
                        'Open the connector / attached terminal to browse combined inventories.',
                        'Add more storage in range rather than running across the base.',
                    ],
                    tip='Keep linked chests close; use cables for larger bases.',
                    nxt='Add a crafting terminal for JEI-friendly crafting from the network.',
                ),
                deps=[4],
                rewards=[item('minecraft:ender_pearl', 4), xp_levels(1)],
                size=1.5,
                subtitle='Storage',
            ),
            Quest(
                n=9,
                x=12.5,
                y=0,
                task='toms_storage:crafting_terminal',
                title='Crafting Terminal',
                desc=tutorial(
                    "Craft Tom's Crafting Terminal.",
                    why='Craft using everything the Inventory Connector can see. Pair with Pipez or Create for restocking.',
                    steps=[
                        'Craft a Crafting Terminal.',
                        'Attach / place it on the Inventory Connector network.',
                        'Open it and craft with JEI transfer from networked items.',
                        'Restock ingredients via Pipez into connector-linked chests.',
                    ],
                ),
                deps=[8],
                rewards=[item('minecraft:crafting_table'), xp_levels(2)],
                size=1.5,
                shape='hexagon',
                subtitle='Storage',
            ),
            Quest(
                n=10,
                x=10,
                y=2.5,
                task='pipez:item_pipe',
                title='Item Pipes',
                desc=tutorial(
                    'Craft &632 Pipez item pipes&r.',
                    why='Chest-to-chest logistics with filters — simpler than Create belts for bulk sorting.',
                    steps=[
                        'Craft 32 item pipes and a Pipez wrench if you lack one.',
                        'Connect a source chest to a destination (drawer controller works great).',
                        'Use the wrench to set extract/insert sides and distribution mode.',
                        'Add filter upgrades so only the right items move.',
                    ],
                    tip='Configure with a wrench. Upgrades raise speed.',
                ),
                task_count=32,
                deps=[3],
                rewards=[item('minecraft:iron_ingot', 16), item('pipez:wrench')],
                subtitle='Pipes',
            ),
            Quest(
                n=11,
                x=12.5,
                y=2.5,
                task='pipez:fluid_pipe',
                title='Fluid Pipes',
                desc=tutorial(
                    'Craft &616 fluid pipes&r.',
                    why='Move water, lava, chocolate, diesel, and Create fluids between tanks and machines.',
                    steps=[
                        'Craft 16 fluid pipes.',
                        'Connect a fluid tank or cauldron to a machine/tank destination.',
                        'Wrench-configure extract on the source and insert on the sink.',
                        'Use filters when multiple fluids share a pipe network.',
                    ],
                ),
                task_count=16,
                deps=[10],
                rewards=[item('minecraft:copper_ingot', 16), xp_levels(1)],
                subtitle='Pipes',
            ),
            Quest(
                n=12,
                x=15,
                y=2.5,
                task='pipez:energy_pipe',
                title='Energy Pipes',
                desc=tutorial(
                    'Craft &616 energy pipes&r.',
                    why='Move FE between Create Crafts & Additions machines, jetpack chargers, and electric addons.',
                    steps=[
                        'Craft 16 energy pipes.',
                        'Connect an FE source (alternator buffer, diesel gens, etc.) to a consumer.',
                        'Wrench sides to extract from batteries and insert into machines.',
                        'Upgrade transfer rate if chargers starve.',
                    ],
                ),
                task_count=16,
                deps=[11],
                rewards=[item('minecraft:redstone', 32)],
                optional=True,
                subtitle='Pipes',
                hide_until_deps=True,
            ),
            Quest(
                n=13,
                x=15,
                y=0,
                task='ironchest:gold_chest',
                title='Gold Chest',
                desc=tutorial(
                    'Upgrade to a Gold Chest.',
                    why="When drawer networks aren't enough for mixed junk storage.",
                    steps=[
                        'Craft / upgrade to a Gold Chest from JEI.',
                        'Place it near your crafting terminal for overflow misc items.',
                        'Keep ores and bulk mats in drawers — gold chests for mixed loot.',
                    ],
                ),
                deps=[9],
                rewards=[item('minecraft:gold_ingot', 16)],
                optional=True,
                subtitle='Storage',
                hide_until_deps=True,
            ),
            Quest(
                n=14,
                x=15,
                y=-2.5,
                task='ironfurnaces:gold_furnace',
                title='Gold Furnace',
                desc=tutorial(
                    'Craft a Gold Furnace.',
                    why='Big smelting speed jump. Diamond / netherite tiers wait in Beyond Brass.',
                    steps=[
                        'Craft a Gold Furnace (upgrade path from iron — check JEI).',
                        'Move your smelting line over and keep it fueled.',
                        'Pipe ore in / ingots out with Pipez for a hands-off smeltery.',
                    ],
                ),
                deps=[13],
                rewards=[item('minecraft:gold_ingot', 16), item('minecraft:coal_block', 4)],
                optional=True,
                subtitle='Smelting',
                hide_until_deps=True,
            ),
            Quest(
                n=15,
                x=2.5,
                y=-2.5,
                task='silentgear:blueprint_paper',
                title='Blueprint Paper',
                desc=tutorial(
                    'Craft &64 Silent Gear blueprint papers&r.',
                    why='Blueprints let you stamp modular tool recipes. Mix materials for mining speed, durability, and harvest level.',
                    steps=[
                        'Craft 4 blueprint papers from JEI.',
                        'Keep them for tool blueprints (pickaxe next).',
                        'Skim JEI material traits so you know which metals to save.',
                    ],
                ),
                task_count=4,
                deps=[2],
                rewards=[item('silentgear:template_board', 4), xp_levels(1)],
                subtitle='Gear',
            ),
            Quest(
                n=16,
                x=5,
                y=-4.5,
                task='silentgear:pickaxe_blueprint',
                title='Pickaxe Blueprint',
                desc=tutorial(
                    'Craft a Silent Gear pickaxe blueprint.',
                    why='Build modular pickaxes — head, rod, and tip materials each matter.',
                    steps=[
                        'Craft a pickaxe blueprint.',
                        'Use it at the Silent Gear crafting station / recipe to assemble head + rod (+ tip).',
                        'Pick materials for harvest level and durability (iron/diamond early; better metals later).',
                        'Repair / swap parts as you unlock stronger materials.',
                    ],
                    tip='JEI shows material traits. Upgrade tips as you find better metals.',
                ),
                deps=[15],
                rewards=[item('minecraft:iron_ingot', 16), xp_levels(1)],
                subtitle='Gear',
            ),
            Quest(
                n=17,
                x=7.5,
                y=-4.5,
                task='silentgear:sword_blueprint',
                title='Sword Blueprint',
                desc=tutorial(
                    'Craft a Silent Gear sword blueprint.',
                    why='Optional combat path — match materials to your mining set for style points.',
                    steps=[
                        'Craft a sword blueprint.',
                        'Assemble a sword with the same material family as your pickaxe.',
                        'Test damage / durability; re-part if a better metal drops.',
                    ],
                ),
                deps=[16],
                rewards=[item('minecraft:iron_sword')],
                optional=True,
                subtitle='Gear',
                hide_until_deps=True,
            ),
            Quest(
                n=18,
                x=10,
                y=-4.5,
                task='constructionstick:iron_stick',
                title='Construction Stick',
                desc=tutorial(
                    'Craft an Iron Construction Stick.',
                    why='Extend walls and platforms in one click — faster base building before Building Gadgets.',
                    steps=[
                        'Craft an Iron Construction Stick.',
                        'Select a building block and aim at a surface.',
                        'Extend floors/walls in the stick\'s placement mode (scroll / keys per mod).',
                        'Undo mistakes with the stick\'s undo if available — practice on a test wall.',
                    ],
                ),
                deps=[1],
                rewards=[item('minecraft:iron_ingot', 16)],
                subtitle='Building',
            ),
            Quest(
                n=19,
                x=12.5,
                y=-4.5,
                task='buildinggadgets2:gadget_building',
                title='Building Gadget',
                desc=tutorial(
                    'Craft a Building Gadget 2.',
                    why='Copy / build / exchange blocks in bulk — perfect for factories and railways.',
                    steps=[
                        'Craft a Building Gadget and charge / fuel it if required.',
                        'Set the block type and build mode (wall, surface, etc.).',
                        'Hold enough blocks in inventory, then click to place large sections.',
                        'Use it to stamp Create factory footprints quickly.',
                    ],
                    tip='Exchanging and copy-paste gadgets are worth unlocking next.',
                ),
                deps=[18],
                rewards=[item('minecraft:redstone', 32), xp_levels(2)],
                size=1.5,
                subtitle='Building',
            ),
            Quest(
                n=20,
                x=15,
                y=-4.5,
                task='buildinggadgets2:gadget_copy_paste',
                title='Copy-Paste Gadget',
                desc=tutorial(
                    'Craft the Copy-Paste Gadget.',
                    why='Save a structure and stamp it elsewhere — repeated factory modules become trivial.',
                    steps=[
                        'Craft the Copy-Paste Gadget.',
                        'Select a region of your factory module and copy it.',
                        'Paste at a new location with the required blocks in inventory.',
                        'Save templates for belt lines, steam setups, or station buildings.',
                    ],
                ),
                deps=[19],
                rewards=[item('buildinggadgets2:template'), xp_levels(1)],
                optional=True,
                subtitle='Building',
                hide_until_deps=True,
            ),
            Quest(
                n=21,
                x=17.5,
                y=0,
                task='artifacts:umbrella',
                title='Artifact Hunt',
                desc=tutorial(
                    'Find an Artifacts umbrella (or any artifact you prefer — umbrella is the checklist item).',
                    why='Trinkets drop from chests, mobs, and exploration. Equip them in Curios slots.',
                    steps=[
                        'Explore structures / defeat mobs that drop Artifacts.',
                        'Pick up an umbrella (or keep hunting until one drops).',
                        'Equip it in a Curios slot and test its effect.',
                    ],
                    tip='Truly optional scavenger hunt — skip if RNG hates you.',
                ),
                deps=[2],
                rewards=[item('minecraft:phantom_membrane', 4), xp_levels(2)],
                optional=True,
                subtitle='Trinkets',
                hide_until_deps=True,
            ),
            Quest(
                n=22,
                x=17.5,
                y=2.5,
                task='minecraft:ender_eye',
                title='Structure Scout',
                desc=tutorial(
                    'Craft an Eye of Ender.',
                    why='Stronghold energy is optional this early — mostly a reminder that &6Lootr&r makes structure chests per-player.',
                    steps=[
                        'Craft an Eye of Ender (blaze powder + ender pearl).',
                        'Optional: throw it to locate a stronghold when you are ready.',
                        'Raid structures with friends — each player gets their own Lootr chests.',
                    ],
                    tip='Raid structures with friends without loot drama.',
                ),
                deps=[21],
                rewards=[item('minecraft:emerald', 8), xp_levels(1)],
                optional=True,
                subtitle='Exploration',
                hide_until_deps=True,
            ),
            Quest(
                n=23,
                x=17.5,
                y=-2.5,
                task='supplementaries:faucet',
                title='Faucet',
                desc=tutorial(
                    'Craft a Supplementaries faucet.',
                    why='Pour fluids from tanks/cauldrons — handy QoL beside Create pumps.',
                    steps=[
                        'Craft a Supplementaries faucet.',
                        'Place it on the side of a tank, jar, or cauldron.',
                        'Activate to pour fluid into the block below (cauldron, basin, etc.).',
                        'Use for small kitchen / XP bottle setups without a full pipe network.',
                    ],
                ),
                deps=[8],
                rewards=[item('supplementaries:jar', 4)],
                optional=True,
                subtitle='QoL',
                hide_until_deps=True,
            ),
        ],
    )
